Repository trento-project/web, pull requests merged in 2022-06, with the labels that each got.

#618 Provide a proper name for Target Infrastructure related APIs
  lib/trento_web/controllers/cluster_controller.ex
  lib/trento_web/controllers/health_overview_controller.ex
  lib/trento_web/controllers/host_controller.ex
  lib/trento_web/controllers/sap_system_controller.ex
  lib/trento_web/openapi/api_spec.ex
Labels: documentation, enhancement

#619 Handle empty list in from_list function
  lib/trento/support/type.ex
  test/trento/support/type_test.exs
Labels: bug

#623 Use NavLink in the navigation elements
  assets/js/components/Layout/Layout.jsx
  test/e2e/cypress/integration/host_details.js
  test/e2e/cypress/integration/hosts_overview.js
Labels: bug

#622 Persist cib last written field
  lib/trento/application/integration/discovery/protocol/enrich_register_cluster_host.ex
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/application/usecases/clusters/cluster_enrichment_data.ex
  lib/trento/application/usecases/clusters/clusters.ex
  lib/trento_web/openapi/schema/cluster.ex
  priv/repo/migrations/20220601162519_create_clusters_enrichment_data_table.exs
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
  test/e2e/cypress/integration/hana_cluster_details.js
  test/support/factory.ex
  test/trento/application/integration/discovery/protocol/enrich_register_cluster_host_test.exs
  test/trento/application/usecases/clusters_test.exs
Labels: bug

#650 Display aws metadata frontend
  .photofinish.toml
  assets/js/components/HostDetails/AwsDetails.jsx
  assets/js/components/HostDetails/AzureDetails.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/ProviderDetails.jsx
  test/e2e/cypress/fixtures/host-details/host_details.feature
  test/e2e/cypress/fixtures/host-details/selected_host.js
  test/e2e/cypress/integration/host_details.js
  test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_aws.json
  test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_unknown.json
Labels: enhancement

#654 Handle gcp details
  lib/trento/application/integration/discovery/payloads/cloud_discovery_payload.ex
  lib/trento/application/integration/discovery/policies/host_policy.ex
  lib/trento/domain/host/commands/update_provider.ex
  lib/trento/domain/host/events/provider_updated.ex
  lib/trento/domain/host/host.ex
  lib/trento/domain/value_objects/gcp_provider.ex
  lib/trento_web/openapi/schema/provider.ex
  test/fixtures/discovery/cloud_discovery_gcp.json
  test/trento/application/integration/discovery/policies/host_policy_test.exs
  test/trento/application/projectors/host_projector_test.exs
  test/trento/domain/host/host_test.exs
Labels: enhancement

#662 Display gcp metadata frontend
  .photofinish.toml
  assets/js/components/HostDetails/GcpDetails.jsx
  assets/js/components/HostDetails/ProviderDetails.jsx
  test/e2e/cypress/fixtures/host-details/host_details.feature
  test/e2e/cypress/fixtures/host-details/selected_host.js
  test/e2e/cypress/integration/host_details.js
  test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_gcp.json
Labels: enhancement
