Repository trento-project/web, pull requests merged in 2022-10, with the labels that each got.

#869 Enable single pipe check on credo
  .credo.exs
  lib/trento/application/integration/checks/adapter/runner.ex
  lib/trento/application/integration/discovery/payloads/cloud_discovery_payload.ex
  lib/trento/application/integration/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/application/integration/discovery/payloads/cluster/sbd_discovery_payload.ex
  lib/trento/application/integration/discovery/payloads/sap_system_discovery_payload.ex
  lib/trento/application/integration/discovery/policies/cluster_policy.ex
  lib/trento/application/integration/discovery/policies/sap_system_policy.ex
  lib/trento/application/integration/grafana/grafana.ex
  lib/trento/application/projectors/check_result_projector.ex
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento/application/projectors/telemetry_projector.ex
  lib/trento/application/usecases/alerting/alerting.ex
  lib/trento/application/usecases/hosts/heartbeats.ex
  lib/trento/application/usecases/hosts/host_connection_settings.ex
  lib/trento/application/usecases/sap_systems/health_summary_service.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/support/mix/tasks/dump_scenario.ex
  lib/trento/support/mix/tasks/helper.ex
  lib/trento_web/controllers/catalog_controller.ex
  lib/trento_web/controllers/host_controller.ex
  lib/trento_web/controllers/sap_system_controller.ex
  lib/trento_web/controllers/settings_controller.ex
  lib/trento_web/openapi/api_spec.ex
  test/trento/application/integration/checks/checks_test.exs
  test/trento/application/integration/discovery/discovery_test.exs
  test/trento/application/usecases/hosts_test.exs
  test/trento_web/controllers/catalog_controller_test.exs
Labels: tech debt

#855 Add tag validation
  assets/js/components/Tags/Tags.jsx
  lib/trento/application/usecases/tags/tag.ex
  test/trento_web/controllers/tags_controller_test.exs
Labels: bug, enhancement

#872 Add mix deps.unlock --check-unused to CI
  .github/workflows/ci.yaml
  mix.lock
Labels: chore

#873 Move the check for unused deps to static code analysis step
  .github/workflows/ci.yaml
Labels: chore

#878 Health summary with clusters and databases
  lib/trento/application/usecases/sap_systems/dto/health_summary_dto.ex
  lib/trento/application/usecases/sap_systems/health_summary_service.ex
  test/support/factory.ex
  test/trento/application/usecases/health_summary_service_test.exs
  test/trento_web/controllers/health_overview_controller_test.exs
Labels: enhancement, elixir

#890 Make Database status icon interactive
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
Labels: enhancement, javascript

#891 Checks results refactor
  assets/js/components/ChecksResults/ChecksResultFilters.jsx
  assets/js/components/ChecksResults/ChecksResults.jsx
  assets/js/components/ChecksResults/ChecksSelectionHints.jsx
  assets/js/components/ChecksResults/ExecutionIcon.jsx
  assets/js/components/ChecksResults/index.js
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterDetails/index.js
  assets/js/components/Tooltip/Tooltip.jsx
  assets/js/components/Tooltip/index.js
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.jsx
  assets/js/components/TriggerChecksExecutionRequest/index.js
  assets/js/trento.jsx
Labels: chore

#896 Lift off rabbitmq
  .github/workflows/ci.yaml
  config/test.exs
  config/wanda.exs
  docker-compose.yaml
  lib/trento/application/integration/checks/adapter/wanda/messaging/amqp/consumer.ex
  lib/trento/application/integration/checks/adapter/wanda/messaging/amqp/processor.ex
  lib/trento/infrastructure/messaging/adapters/amqp.ex
  lib/trento/infrastructure/messaging/adapters/amqp/publisher.ex
  lib/trento/infrastructure/messaging/adapters/behaviour.ex
  lib/trento/infrastructure/messaging/messaging.ex
  mix.exs
  mix.lock
  test/test_helper.exs
  test/trento/application/integration/checks/wanda/messaging/amqp/consumer_test.exs
Labels: enhancement

#905 Initial proposal for a collapsed sidebar.
  assets/js/components/Layout/EosKeyboardDoubleArrowLeft.jsx
  assets/js/components/Layout/Layout.jsx
  assets/tailwind.config.js
Labels: ux

#906 Publish execution requested
  config/wanda.exs
  lib/trento/application/integration/checks/adapter/wanda/wanda.ex
  lib/trento/infrastructure/messaging/adapters/amqp.ex
  lib/trento/infrastructure/messaging/adapters/amqp/publisher.ex
  lib/trento/infrastructure/messaging/mapper.ex
  mix.exs
  mix.lock
  test/trento/application/integration/checks/wanda/wanda_test.exs
  test/trento/infrastructure/messaging/mapper_test.exs
Labels: enhancement

#914 General browser fixes for collapsed sidebar
  assets/js/components/Layout/EosKeyboardDoubleArrowLeft.jsx
  assets/js/components/Layout/Layout.jsx
Labels: bug, ux

#915 Added Clear button to Filter component when one or more values are selected.
  assets/js/components/Table/Filter.jsx
Labels: enhancement, ux

#924 Checks results refactor part two
  assets/jest.config.js
  assets/js/components/ChecksResults/CheckResult.jsx
  assets/js/components/ChecksResults/ChecksResults.jsx
  assets/js/components/ChecksResults/HostResultsWrapper.jsx
  assets/js/components/ChecksResults/ResultsContainer.jsx
  assets/js/components/ChecksResults/ResultsContainer.test.jsx
  assets/js/components/ChecksResults/checksUtils.js
  assets/js/lib/test-utils/index.jsx
  assets/mocks/fileMock.js
  assets/mocks/remarkPlugin.js
Labels: chore

#925 Frontend table filters from query string
  assets/js/components/HostsList.jsx
  assets/js/components/Table/Table.jsx
  assets/js/components/Table/filters.jsx
  test/e2e/cypress/integration/hosts_overview.js
Labels: enhancement, ux, javascript

#926 Removed restart strategy from docker-compose file
  docker-compose.yaml
Labels: chore

#932 Encapsulated About content with a white container
  assets/js/components/AboutPage/AboutPage.jsx
Labels: ux

#908 Add filtering through search params
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  test/e2e/cypress/integration/dashboard.js
Labels: enhancement, javascript, proposal
