Repository trento-project/web, pull requests merged in 2022-05, with the labels that each got.

#476 Include cluster field in the host details view
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/state/selectors/index.js
Labels: bug

#492 Use get-latest action to avoid issues with git after CVE-2022-24765
  .github/workflows/ci.yaml
Labels: bug

#497 Handle unnamed cluster event
  .photofinish.toml
  assets/js/components/ClusterDetails/ChecksResults.jsx
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterLink.jsx
  assets/js/components/ClustersList.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/cluster/commands/register_cluster_host.ex
  test/e2e/cypress/fixtures/clusters-overview/available_clusters.js
  test/e2e/cypress/integration/clusters_overview.js
  test/fixtures/discovery/ha_cluster_discovery_unnamed.json
  test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_unnamed.json
  test/trento/application/integration/discovery/policies/cluster_policy_test.exs
Labels: bug

#504 Include premium field handling
  .github/workflows/ci.yaml
  lib/trento/application/integration/checks/dto/check_dto.ex
  lib/trento/application/integration/checks/dto/flat_check_dto.ex
  test/fixtures/runner/catalog.json
  test/trento/application/integration/checks/checks_test.exs
  test/trento_web/controllers/catalog_controller_test.exs
Labels: bug

#517 Correct log replication and log operation mode names
  assets/js/components/ClusterDetails/ClusterDetails.jsx
Labels: bug

#525 Migrate sap overview e2e
  test/e2e/cypress/fixtures/sap-systems-overview/available_sap_systems.js
  test/e2e/cypress/fixtures/sap-systems-overview/sap_systems_overview.feature
  test/e2e/cypress/integration/sap_systems_overview.js
  test/fixtures/scenarios/sap-systems-overview/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery_GRAY.json
  test/fixtures/scenarios/sap-systems-overview/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery_YELLOW.json
Labels: ci

#532 Use ExMachina as test data generation factory for host telemetry
  mix.exs
  mix.lock
  test/support/factory.ex
  test/test_helper.exs
  test/trento/application/integration/telemetry/telemetry_test.exs
Labels: dx

#529 Sap system details e2e
  .photofinish.toml
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/HostLink.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  assets/js/components/SapSystemDetails/tableConfigs.jsx
  test/e2e/cypress/fixtures/sap-system-details/sap_system_details.feature
  test/e2e/cypress/fixtures/sap-system-details/selected_system.js
  test/e2e/cypress/fixtures/sap-systems-overview/sap_systems_overview.feature
  test/e2e/cypress/integration/sap_system_details.js
  test/fixtures/scenarios/sap-system-details/1b0e9297-97dd-55d6-9874-8efde4d84c90_sap_system_discovery_new.json
Labels: enhancement, ci

#536 Checks catalog openapi
  lib/trento_web/controllers/catalog_controller.ex
  lib/trento_web/openapi/api_spec.ex
  lib/trento_web/openapi/schema/checks_catalog.ex
  lib/trento_web/openapi/schema/provider.ex
Labels: documentation, enhancement

#543 Add HANA details page e2e tests
  .photofinish.toml
  assets/js/components/DatabaseDetails/DatabaseDetails.jsx
  test/e2e/cypress/fixtures/hana-database-details/hana_database_details.feature
  test/e2e/cypress/fixtures/hana-database-details/selected_database.js
  test/e2e/cypress/integration/hana_database_details.js
  test/fixtures/scenarios/hana-database-details/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_sap_system_discovery_new.json
Labels: ci

#555 Cluster health when no checks are selected
  lib/trento/domain/cluster/cluster.ex
  test/e2e/cypress/integration/dashboard.js
  test/e2e/cypress/support/commands.js
  test/support/factory.ex
  test/trento/domain/cluster/cluster_test.exs
Labels: enhancement

#570 Adds openapi doc for ApiKey retriveal
  lib/trento_web/controllers/installation_controller.ex
  lib/trento_web/openapi/api_spec.ex
Labels: documentation, enhancement

#579 Add SapSystems Health overview OpenApi spec
  lib/trento_web/controllers/health_overview_controller.ex
  lib/trento_web/openapi/schema/sap_system.ex
Labels: documentation, enhancement

#581 Add Accept Eula openapi spec
  lib/trento_web/controllers/settings_controller.ex
Labels: documentation, enhancement

#584 Adds Platform Settings OpenApi spec
  lib/trento_web/controllers/settings_controller.ex
  lib/trento_web/openapi/schema/platform.ex
Labels: documentation, enhancement

#585 Hosts overview e2e
  assets/js/components/HealthSummary/HealthSummary.jsx
  test/e2e/cypress/fixtures/hosts-overview/available_hosts.js
  test/e2e/cypress/fixtures/hosts-overview/hosts_overview.feature
  test/e2e/cypress/integration/dashboard.js
  test/e2e/cypress/integration/host_details.js
  test/e2e/cypress/integration/hosts_overview.js
  test/e2e/cypress/integration/sap_systems_overview.js
  test/e2e/cypress/plugins/index.js
  test/e2e/cypress/support/commands.js
Labels: ci

#545 About page e2e
  lib/trento/support/mix/tasks/version.ex
  test/e2e/cypress/fixtures/about/about.feature
  test/e2e/cypress/integration/about.js
Labels: ci

#542 Dump discarded discovery events
  hack/dump_scenario_from_k8.sh
  lib/trento/application/integration/discovery/discarded_discovery_event.ex
  lib/trento/application/integration/discovery/discovery.ex
  lib/trento/support/mix/tasks/dump_scenario.ex
  lib/trento/support/mix/tasks/prune_events.ex
  priv/repo/migrations/20220518074335_add_discarded_discovery_event_table.exs
  test/support/factory.ex
  test/trento/application/integration/discovery/discovery_test.exs
  test/trento_web/controllers/prometheus_controller_test.exs
Labels: enhancement

#586 About openapi
  lib/trento_web/controllers/about_controller.ex
  lib/trento_web/openapi/schema/platform.ex
Labels: documentation, enhancement

#601 Add the possibility to decode lists of items with deftype
  lib/trento/support/type.ex
  test/trento/support/type_test.exs
Labels: tech debt

#516 Upgrade to React 18
  assets/jest.config.js
  assets/js/components/Button/Button.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ProviderSelection.jsx
  assets/js/trento.jsx
  assets/package-lock.json
  assets/package.json
  test/e2e/cypress/integration/checks_catalog.js
Labels: tech debt, chore
