Repository trento-project/web, pull requests merged in 2022-09, with the labels that each got.

#728 Add installation_source field to the host telemetry
  lib/trento/application/integration/discovery/payloads/host_discovery_payload.ex
  lib/trento/application/integration/discovery/policies/host_policy.ex
  lib/trento/application/integration/telemetry/adapter/suse.ex
  lib/trento/application/projectors/telemetry_projector.ex
  lib/trento/application/read_models/host_telemetry_read_model.ex
  lib/trento/domain/host/commands/register_host.ex
  lib/trento/domain/host/events/host_details_updated.ex
  lib/trento/domain/host/events/host_registered.ex
  lib/trento/domain/host/host.ex
  priv/repo/migrations/20220729073320_add_installation_source_host_telemetry_read_model.exs
  test/fixtures/discovery/host_discovery_with_installation_source.json
  test/support/factory.ex
  test/trento/application/integration/discovery/policies/host_policy_test.exs
  test/trento/domain/host/events/host_details_updated_test.exs
  test/trento/domain/host/events/host_registered_test.exs
  test/trento/domain/host/host_test.exs
Labels: enhancement

#845 Changed Warning border to 8px
  assets/js/components/Banners/WarningBanner.jsx
Labels: ux

#848 Fix active style matching inside navlink usage
  assets/js/components/Layout/Layout.jsx
Labels: bug

#850 Added margin to the bottom of each result/host container.
  assets/js/components/ClusterDetails/ChecksResults.jsx
Labels: ux

#854 Community eula
  assets/js/components/Eula/Community.jsx
  assets/js/components/Eula/Eula.jsx
  assets/js/components/Eula/Eula.test.jsx
  assets/js/components/Eula/Premium.jsx
  assets/js/state/sagas/index.js
  assets/js/state/settings.js
  assets/package-lock.json
  assets/package.json
Labels: enhancement

#849 Add provider enum
  lib/trento/application/integration/checks/dto/flat_check_dto.ex
  lib/trento/application/integration/checks/dto/provider_dto.ex
  lib/trento/application/integration/discovery/payloads/cloud_discovery_payload.ex
  lib/trento/application/integration/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/application/integration/discovery/policies/cluster_policy.ex
  lib/trento/application/integration/discovery/policies/host_policy.ex
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento/application/read_models/host_telemetry_read_model.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/cluster/commands/register_cluster_host.ex
  lib/trento/domain/cluster/events/checks_execution_requested.ex
  lib/trento/domain/cluster/events/cluster_details_updated.ex
  lib/trento/domain/cluster/events/cluster_registered.ex
  lib/trento/domain/cluster/events/cluster_rolled_up.ex
  lib/trento/domain/enums/enum.ex
  lib/trento/domain/enums/provider.ex
  lib/trento/domain/host/commands/update_provider.ex
  lib/trento/domain/host/events/provider_updated.ex
  lib/trento/domain/host/host.ex
  lib/trento_web/openapi/schema/checks_catalog.ex
  lib/trento_web/openapi/schema/provider.ex
  test/support/factory.ex
  test/trento/application/integration/discovery/policies/cluster_policy_test.exs
  test/trento/application/integration/discovery/policies/host_policy_test.exs
  test/trento/application/projectors/host_projector_test.exs
Labels: tech debt, proposal

#860 Rename .Enum.* to .Enums.* in module paths for consistency
  lib/trento/application/integration/discovery/payloads/cloud_discovery_payload.ex
  lib/trento/application/integration/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/application/integration/discovery/policies/cluster_policy.ex
  lib/trento/application/integration/discovery/policies/host_policy.ex
  lib/trento/application/read_models/application_instance_read_model.ex
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/application/read_models/database_instance_read_model.ex
  lib/trento/application/read_models/database_read_model.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento/application/read_models/host_telemetry_read_model.ex
  lib/trento/application/read_models/sap_system_read_model.ex
  lib/trento/application/usecases/clusters/clusters.ex
  lib/trento/application/usecases/sap_systems/dto/health_summary_dto.ex
  lib/trento/application/usecases/sap_systems/health_summary_service.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/cluster/commands/register_cluster_host.ex
  lib/trento/domain/cluster/events/checks_execution_completed.ex
  lib/trento/domain/cluster/events/checks_execution_requested.ex
  lib/trento/domain/cluster/events/cluster_details_updated.ex
  lib/trento/domain/cluster/events/cluster_discovered_health_changed.ex
  lib/trento/domain/cluster/events/cluster_health_changed.ex
  lib/trento/domain/cluster/events/cluster_registered.ex
  lib/trento/domain/cluster/events/cluster_rolled_up.ex
  lib/trento/domain/enums/cluster_type.ex
  lib/trento/domain/enums/health.ex
  lib/trento/domain/enums/provider.ex
  lib/trento/domain/host/commands/update_provider.ex
  lib/trento/domain/host/events/provider_updated.ex
  lib/trento/domain/host/host.ex
  lib/trento/domain/sap_system/commands/register_application_instance.ex
  lib/trento/domain/sap_system/commands/register_database_instance.ex
  lib/trento/domain/sap_system/database.ex
  lib/trento/domain/sap_system/events/application_instance_health_changed.ex
  lib/trento/domain/sap_system/events/application_instance_registered.ex
  lib/trento/domain/sap_system/events/database_health_changed.ex
  lib/trento/domain/sap_system/events/database_instance_health_changed.ex
  lib/trento/domain/sap_system/events/database_instance_registered.ex
  lib/trento/domain/sap_system/events/database_registered.ex
  lib/trento/domain/sap_system/events/sap_system_health_changed.ex
  lib/trento/domain/sap_system/events/sap_system_registered.ex
  lib/trento/domain/sap_system/instance.ex
  lib/trento/domain/sap_system/sap_system.ex
  lib/trento/domain/services/health_service.ex
  lib/trento/support/enum.ex
  lib/trento_web/openapi/schema/cluster.ex
  lib/trento_web/openapi/schema/health.ex
  lib/trento_web/openapi/schema/provider.ex
  test/support/factory.ex
  test/trento/application/integration/discovery/policies/cluster_policy_test.exs
  test/trento/application/integration/discovery/policies/host_policy_test.exs
  test/trento/application/projectors/host_projector_test.exs
Labels: tech debt
