Repository trento-project/web, pull requests merged in 2022-11, with the labels that each got.

#941 Remove container name from rabbitmq container in docker compose
  docker-compose.yaml
Labels: chore

#943 Enable query string filtering in existing views
  assets/jest.config.js
  assets/js/components/ClustersList.jsx
  assets/js/components/ClustersList.test.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.test.jsx
  assets/js/components/Table/Filter.jsx
  assets/js/lib/test-utils/data/clusters.js
  assets/js/lib/test-utils/data/hosts.js
  assets/js/lib/test-utils/data/sapSystems.js
  assets/js/lib/test-utils/index.jsx
Labels: enhancement, ux, javascript

#946 Replace mock usage for dispatch
  config/config.exs
  config/test.exs
  lib/trento/application/event_handlers/rollup_event_handler.ex
  lib/trento/application/integration/checks/checks.ex
  lib/trento/application/integration/discovery/discovery.ex
  lib/trento/application/usecases/clusters/clusters.ex
  lib/trento/application/usecases/hosts/heartbeats.ex
  test/support/factory.ex
  test/test_helper.exs
  test/trento/application/integration/checks/checks_test.exs
  test/trento/application/usecases/clusters_test.exs
  test/trento/application/usecases/heartbeats_test.exs
Labels: tech debt

#944 Ui restyle of Health box in HealthSummary
  assets/js/components/HealthSummary/HealthSummary.jsx
  assets/js/components/HealthSummary/HealthSummaryBox.jsx
  test/e2e/cypress/integration/dashboard.js
Labels: ux, javascript

#947 Mock DateTime using a custom date service and mox
  lib/trento/application/usecases/hosts/heartbeats.ex
  lib/trento/support/date.ex
  mix.exs
  mix.lock
  test/test_helper.exs
  test/trento/application/usecases/heartbeats_test.exs
Labels: tech debt

#942 Add a test using Fishery and Faker
  assets/js/components/ChecksResults/CheckResult.test.jsx
  assets/js/lib/test-utils/factories.js
  assets/package-lock.json
  assets/package.json
Labels: chore

#949 Use uuid format for id fields
  lib/trento/domain/cluster/commands/select_checks.ex
  lib/trento/domain/cluster/events/checks_selected.ex
  lib/trento/domain/cluster/events/cluster_details_updated.ex
  lib/trento/domain/cluster/events/cluster_discovered_health_changed.ex
  lib/trento/domain/cluster/events/cluster_health_changed.ex
  lib/trento/domain/cluster/events/cluster_registered.ex
  lib/trento/domain/cluster/events/cluster_rolled_up.ex
  lib/trento/domain/cluster/events/host_added_to_cluster.ex
  lib/trento/domain/cluster/events/host_checks_execution_completed.ex
  lib/trento/domain/host/commands/update_heartbeat.ex
  lib/trento/domain/sap_system/commands/register_application_instance.ex
  lib/trento/domain/sap_system/commands/register_database_instance.ex
  lib/trento/domain/sap_system/sap_system.ex
Labels: tech debt, chore

#918 Remove events from checks execution
  config/config.exs
  config/wanda.exs
  lib/trento/application/usecases/clusters/adapters/gen.ex
  lib/trento/application/usecases/clusters/adapters/runner.ex
  lib/trento/application/usecases/clusters/adapters/wanda.ex
  lib/trento/application/usecases/clusters/clusters.ex
  test/support/factory.ex
  test/trento/application/integration/checks/wanda/messaging/amqp/consumer_test.exs
  test/trento/application/usecases/clusters_test.exs
Labels: enhancement

#922 Process execution completed
  lib/trento/application/integration/checks/adapter/wanda/messaging/amqp/processor.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/cluster/commands/complete_checks_execution_wanda.ex
  lib/trento/domain/cluster/events/cluster_checks_health_changed.ex
  lib/trento/infrastructure/router.ex
  test/trento/application/integration/checks/wanda/messaging/amqp/processor_test.exs
  test/trento/domain/cluster/cluster_test.exs
Labels: enhancement

#950 Enable box health filters on Dashboard
  assets/js/components/ClustersList.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.jsx
  assets/js/components/HealthSummary/ComponentHealthSummary.jsx
  assets/js/components/HealthSummary/HealthSummary.jsx
  assets/js/components/HealthSummary/HealthSummaryBox.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/components/HealthSummary/index.js
  assets/js/components/HealthSummary/summarySelection.js
  assets/js/components/HostsList.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
  assets/js/hooks/useQueryStringValues.js
  assets/js/lib/test-utils/factories.js
  test/e2e/cypress/integration/dashboard.js
Labels: ux, javascript

#956 Include missing file for CI
  hack/gh_release_to_obs_changeset.py
Labels: bug

#959 Add hover style to health icon
  assets/js/components/Health/HealthIcon.jsx
Labels: ux, javascript

#958 Add the possibility to add environment configuration to the bundle
  .gitignore
  assets/.env.example
  assets/build.js
  assets/package-lock.json
  assets/package.json
Labels: chore

#960 Catalog from wanda
  assets/.eslintrc.js
  assets/js/components/ChecksCatalog/CatalogContainer.jsx
  assets/js/components/ChecksCatalog/CatalogContainer.test.jsx
  assets/js/components/ChecksCatalog/CheckItem.jsx
  assets/js/components/ChecksCatalog/CheckItem.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogNew.jsx
  assets/js/components/ChecksCatalog/index.js
  assets/js/lib/test-utils/factories.js
  assets/js/trento.jsx
Labels: enhancement

#961 Make SAP Instances status icon interactive
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/lib/test-utils/factories.js
  assets/js/state/healthSummary.js
Labels: enhancement, javascript, test

#970 Use mocked redux store
  assets/js/components/ClustersList.test.jsx
  assets/js/components/Eula/Eula.test.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.test.jsx
  assets/js/lib/test-utils/index.jsx
  assets/package-lock.json
  assets/package.json
Labels: test

#981 Setup elixir docs generation
  .github/workflows/ci.yaml
  mix.exs
  mix.lock
Labels: documentation

#975 Fix tagging test in hosts overview e2e suite
  test/e2e/cypress/integration/clusters_overview.js
  test/e2e/cypress/integration/hosts_overview.js
  test/e2e/cypress/integration/sap_systems_overview.js
  test/e2e/cypress/support/commands.js
Labels: bug

#963 Phoenix views refactoring
  lib/trento/application/integration/prometheus/prometheus.ex
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento/application/usecases/hosts/hosts.ex
  lib/trento/application/usecases/sap_systems/dto/health_summary_dto.ex
  lib/trento/application/usecases/sap_systems/health_summary_service.ex
  lib/trento/application/usecases/sap_systems/sap_systems.ex
  lib/trento_web/controllers/about_controller.ex
  lib/trento_web/controllers/cluster_controller.ex
  lib/trento_web/controllers/health_overview_controller.ex
  lib/trento_web/controllers/host_controller.ex
  lib/trento_web/controllers/installation_controller.ex
  lib/trento_web/controllers/prometheus_controller.ex
  lib/trento_web/controllers/sap_system_controller.ex
  lib/trento_web/controllers/settings_controller.ex
  lib/trento_web/openapi/schema/cluster.ex
  lib/trento_web/openapi/schema/database.ex
  lib/trento_web/openapi/schema/health.ex
  lib/trento_web/openapi/schema/host.ex
  lib/trento_web/openapi/schema/provider.ex
  lib/trento_web/openapi/schema/sap_system.ex
  lib/trento_web/views/about_view.ex
  lib/trento_web/views/cluster_view.ex
  lib/trento_web/views/health_overview_view.ex
  lib/trento_web/views/host_view.ex
  lib/trento_web/views/installation_view.ex
  lib/trento_web/views/prometheus_view.ex
  lib/trento_web/views/sap_system_view.ex
  lib/trento_web/views/settings_view.ex
  test/support/factory.ex
  test/trento/application/usecases/health_summary_service_test.exs
  test/trento/application/usecases/hosts_test.exs
  test/trento/application/usecases/sap_systems_test.exs
  test/trento_web/controllers/cluster_controller_test.exs
  test/trento_web/controllers/health_overview_controller_test.exs
  test/trento_web/controllers/host_controller_test.exs
  test/trento_web/controllers/installation_controller_test.exs
  test/trento_web/controllers/prometheus_controller_test.exs
  test/trento_web/controllers/sap_system_controller_test.exs
  test/trento_web/controllers/settings_controller_test.exs
  test/trento_web/views/health_overview_view_test.exs
  test/trento_web/views/sap_system_view_test.exs
Labels: tech debt, elixir

#985 Document the cluster aggregate module
  lib/trento/domain/cluster/cluster.ex
Labels: documentation

#986 Tests refactoring
  test/trento/application/integration/discovery/discovery_test.exs
  test/trento/application/usecases/clusters_test.exs
  test/trento/application/usecases/hosts_test.exs
  test/trento/application/usecases/sap_systems_test.exs
  test/trento_web/controllers/cluster_controller_test.exs
  test/trento_web/controllers/health_overview_controller_test.exs
  test/trento_web/controllers/host_controller_test.exs
  test/trento_web/controllers/installation_controller_test.exs
  test/trento_web/controllers/prometheus_controller_test.exs
  test/trento_web/controllers/sap_system_controller_test.exs
  test/trento_web/controllers/settings_controller_test.exs
  test/trento_web/controllers/tags_controller_test.exs
Labels: tech debt, elixir

#989 Add coveralls
  .github/workflows/ci.yaml
  coveralls.json
  mix.exs
  mix.lock
Labels: chore, dx, test

#992 Bump asdf erlang version to 24.3.4
  .tool-versions
Labels: chore

#988 Document SAP system aggregate
  lib/trento/domain/sap_system/commands/register_application_instance.ex
  lib/trento/domain/sap_system/sap_system.ex
Labels: documentation

#991 Phoenix channels broadcasting testing
  lib/trento/application/projectors/check_result_projector.ex
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento_web/views/checks_result_view.ex
  lib/trento_web/views/cluster_view.ex
  lib/trento_web/views/host_view.ex
  test/trento/application/event_handlers/checks_event_handler_test.exs
  test/trento/application/integration/discovery/protocol/enrich_register_cluster_host_test.exs
  test/trento/application/projectors/check_result_projector_test.exs
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento/application/projectors/database_projector_test.exs
  test/trento/application/projectors/host_projector_test.exs
  test/trento/application/projectors/sap_system_projector_test.exs
  test/trento/application/projectors/sles_subscriptions_projector_test.exs
Labels: tech debt, elixir

#987 Checks results coming from Wanda
  assets/.storybook/main.js
  assets/js/components/ChecksResults/CheckResult.jsx
  assets/js/components/ChecksResults/checksUtils.js
  assets/js/components/ChecksResults/checksUtils.test.js
  assets/js/components/ChecksResults/index.js
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.stories.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/ExecutionResults/index.js
  assets/js/lib/api/wanda.js
  assets/js/lib/test-utils/factories.js
  assets/js/trento.jsx
Labels: enhancement

#1005 Help tailwind's JIT figure which classes we need
  assets/js/components/ClusterDetails/ChecksResultOverview.jsx
Labels: bug, ux, javascript

#1007 Disable link to unavailable pacemaker cluster detail in home/health summary
  assets/js/components/Health/HealthIcon.jsx
  assets/js/components/Health/HealthIcon.test.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
Labels: bug

#968 Improve catalog container usability
  assets/js/components/ChecksCatalog/CatalogContainer.jsx
  assets/js/components/ChecksCatalog/CatalogContainer.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogNew.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogNew.test.jsx
  assets/js/lib/api/wanda.js
  assets/js/lib/network/index.js
  assets/js/lib/test-utils/index.jsx
  assets/js/state/catalogNew.js
  assets/js/state/catalogNew.test.js
  assets/js/state/index.js
  assets/js/state/sagas/catalog.js
  assets/js/state/sagas/catalog.test.js
  assets/js/state/sagas/index.js
  assets/js/state/selectors/catalog.js
  assets/js/state/selectors/catalog.test.js
  assets/package-lock.json
  assets/package.json
Labels: enhancement

#1013 Add test and refactor the AboutPage component
  assets/js/components/AboutPage/AboutPage.jsx
  assets/js/components/AboutPage/AboutPage.test.jsx
  assets/js/components/AboutPage/AboutPageLogo.jsx
  assets/js/components/AboutPage/AboutPageText.jsx
  assets/js/lib/api/about.js
  assets/js/lib/test-utils/factories.js
Labels: tech debt, javascript

#1012 Add photofinish to the cache
  .github/workflows/ci.yaml
Labels: ci, github_actions

#976 Checks selection from wanda
  assets/js/components/ChecksCatalog/ChecksCatalogNew.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogNew.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionGroup.jsx
  assets/js/components/ClusterDetails/ChecksSelectionGroup.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
  assets/js/components/ClusterDetails/ChecksSelectionNew.test.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/lib/test-utils/factories.js
  assets/js/state/actions/catalog.js
  assets/js/state/actions/cluster.js
  assets/js/state/sagas/catalog.js
  assets/js/state/sagas/index.js
  assets/js/trento.jsx
Labels: enhancement

#996 Add SBD_OPTS to cluster discovery events
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_up.json
  test/fixtures/discovery/ha_cluster_discovery_unnamed.json
  test/fixtures/scenarios/aws-landscape/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_ha_cluster_discovery.json
  test/fixtures/scenarios/aws-landscape/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery.json
  test/fixtures/scenarios/aws-landscape/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_ha_cluster_discovery.json
  test/fixtures/scenarios/aws-landscape/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_ha_cluster_discovery.json
  test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_1_SFAIL.json
  test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_1_SOK.json
  test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_4_SFAIL.json
  test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_4_SOK.json
  test/fixtures/scenarios/clusters-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery_unnamed.json
  test/fixtures/scenarios/gcp-landscape/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_ha_cluster_discovery.json
  test/fixtures/scenarios/gcp-landscape/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery.json
  test/fixtures/scenarios/gcp-landscape/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_ha_cluster_discovery.json
  test/fixtures/scenarios/gcp-landscape/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_kvm_provider.json
  test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_nutanix_provider.json
  test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_unknown_provider.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/116d49bd-85e1-5e59-b820-83f66db8800c_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/21de186a-e38f-5804-b643-7f4ef22fecfd_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/25677e37-fd33-5005-896c-9275b1284534_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/3711ea88-9ccc-5b07-8f9d-042be449d72b_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/422686d6-b2d1-5092-93e8-a744854f5085_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/4b30a6af-4b52-5bda-bccb-f2248a12c992_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/927901fa-2c87-524e-b18c-3ef5187f504f_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9cd46919-5f19-59aa-993e-cf3736c71053_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/a09d9cf3-46c1-505c-8fb8-4b0a71a9114e_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/ddcb7992-2ffb-5c10-8b39-80685f6eaaba_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/e0c182db-32ff-55c6-a9eb-2b82dd21bc8b_ha_cluster_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_ha_cluster_discovery.json
Labels: enhancement
