Repository trento-project/web, pull requests merged in 2022-12, with the labels that each got.

#1023 Broadcast execution completed
  assets/js/state/index.js
  assets/js/state/registerSocketEvents.js
  lib/trento/application/integration/checks/adapter/wanda/messaging/amqp/processor.ex
  test/trento/application/integration/checks/wanda/messaging/amqp/processor_test.exs
Labels: enhancement

#1031 Fix AboutPage test console error output
  assets/js/components/AboutPage/AboutPage.test.jsx
Labels: bug, javascript, test

#1054 Fix ESLint warning about unnamed function
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
Labels: chore

#1047 Read `ExecutionResults` state from Redux store
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/lib/test-utils/factories/index.js
  assets/js/lib/test-utils/index.jsx
  assets/js/trento.jsx
Labels: javascript

#1056 Transition start execution running
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
  assets/js/components/ClusterDetails/ClusterDetailsNew.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.test.jsx
  assets/js/lib/serialization/index.js
  assets/js/lib/serialization/index.test.js
  assets/js/lib/test-utils/factories/index.js
  assets/js/state/actions/cluster.js
  assets/js/state/actions/lastExecutions.js
  assets/js/state/lastExecutions.js
  assets/js/state/lastExecutions.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/lastExecutions.js
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
  assets/js/trento.jsx
Labels: enhancement

#1071 Add ChecksSelectionHints in the ExecutionResults
  assets/js/components/ChecksResults/ChecksSelectionHints.jsx
  assets/js/components/ChecksResults/ResultsContainer.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
Labels: enhancement, javascript
