Repository trento-project/web, pull requests merged in 2023-07, with the labels that each got.

#1579 ApplicationInstanceMoved FE side-effects
  assets/js/state/channels.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
Labels: enhancement, javascript

#1570 Project broadcast application instance moved
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sapSystems.js
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento_web/views/v1/sap_system_view.ex
  test/trento/application/projectors/sap_system_projector_test.exs
Labels: enhancement, elixir

#1567 Update contracts usage
  lib/trento/application/integration/checks/checks.ex
  mix.exs
  mix.lock
Labels: enhancement

#1580 Pin correct contracts version
  mix.exs
  mix.lock
Labels: bug, dependencies

#1552 Add application cluster column to health summary view
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.stories.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/lib/test-utils/factories/index.js
Labels: enhancement

#1599 Add cleanup button component
  assets/js/components/CleanUpButton/CleanUpButton.jsx
  assets/js/components/CleanUpButton/CleanUpButton.stories.jsx
  assets/js/components/CleanUpButton/CleanUpButton.test.jsx
  assets/js/components/CleanUpButton/index.js
Labels: enhancement

#1587 Add ability to mark Hosts as `deregisterable`
  assets/js/lib/test-utils/factories/hosts.js
  assets/js/state/hosts.js
  assets/js/state/hosts.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
  lib/trento_web/templates/page/index.html.heex
Labels: javascript

#1602 Broadcast tags and value objects in restore events
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento_web/views/v1/host_view.ex
  lib/trento_web/views/v1/sap_system_view.ex
  lib/trento_web/views/v2/cluster_view.ex
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento/application/projectors/database_projector_test.exs
  test/trento/application/projectors/host_projector_test.exs
  test/trento/application/projectors/sap_system_projector_test.exs
Labels: enhancement

#1600 Load selectable checks for a host
  assets/js/components/ChecksSelection/ChecksSelection.jsx
  assets/js/components/ChecksSelection/ChecksSelection.stories.jsx
  assets/js/components/ChecksSelection/ChecksSelection.test.jsx
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.stories.jsx
  assets/js/components/HostDetails/HostChecksSelection.test.jsx
  assets/js/components/HostDetails/HostInfoBox.jsx
  assets/js/components/HostDetails/HostInfoBox.test.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/components/HostDetails/HostSettingsPage.test.jsx
  assets/js/components/HostDetails/index.js
  assets/js/lib/test-utils/factories/hosts.js
  assets/js/lib/test-utils/index.jsx
  assets/js/trento.jsx
Labels: enhancement, user story, javascript

#1616 Fix application instance deletion after_update
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
  test/trento/application/projectors/database_projector_test.exs
  test/trento/application/projectors/sap_system_projector_test.exs
Labels: bug

#1611 Only broadcast `HostRemovedFromCluster` when a host is part of a cluster
  lib/trento/application/projectors/host_projector.ex
  test/trento/application/projectors/host_projector_test.exs
Labels: elixir

#1601 Deregister hosts list frontend
  assets/js/components/HostsList.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/state/hosts.js
  assets/js/state/hosts.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
Labels: enhancement

#1624 Projectors refactor
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
Labels: elixir

#1618 Host Checks selection saga
  assets/js/components/ChecksSelection/ChecksSelection.jsx
  assets/js/components/ChecksSelection/ChecksSelection.test.jsx
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/lib/test-utils/index.jsx
  assets/js/state/actions/cluster.js
  assets/js/state/clusters.js
  assets/js/state/hostChecksSelection.js
  assets/js/state/hostChecksSelection.test.js
  assets/js/state/hosts.js
  assets/js/state/hosts.test.js
  assets/js/state/index.js
  assets/js/state/sagas/clusters.js
  assets/js/state/sagas/clusters.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
  assets/js/state/selectors/hostChecksSelection.js
  assets/js/state/selectors/hostChecksSelection.test.js
Labels: enhancement, user story, javascript

#1635 Refactor check selection saga
  assets/js/lib/test-utils/index.jsx
  assets/js/state/checksSelection.js
  assets/js/state/checksSelection.test.js
  assets/js/state/sagas/checksSelection.js
  assets/js/state/sagas/checksSelection.test.js
  assets/js/state/selectors/checksSelection.js
  assets/js/state/selectors/checksSelection.test.js
Labels: enhancement, javascript

#1639 Fix database sid display
  assets/js/components/ClusterDetails/ClusterDetailsPage.test.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/lib/test-utils/data/databases.js
  assets/js/lib/test-utils/index.jsx
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
Labels: bug

#1629 Add test to check for Clean up button visibility
  assets/js/components/CleanUpButton/CleanUpButton.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.jsx
  test/e2e/cypress/e2e/hosts_overview.cy.js
Labels: javascript, test

#1646 Remove obsolete live feed FE code
  assets/js/components/LiveFeed/LiveFeed.jsx
  assets/js/components/LiveFeed/index.js
  assets/js/state/index.js
  assets/js/state/liveFeed.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/sapSystems.js
Labels: chore

#1641 Use centralized checks selection for both hosts and clusters
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/lib/test-utils/index.jsx
  assets/js/state/checksSelection.js
  assets/js/state/clusterChecksSelection.js
  assets/js/state/hostChecksSelection.js
  assets/js/state/hostChecksSelection.test.js
  assets/js/state/index.js
  assets/js/state/sagas/checksSelection.js
  assets/js/state/sagas/checksSelection.test.js
  assets/js/state/sagas/clusters.js
  assets/js/state/sagas/clusters.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
  assets/js/state/selectors/checksSelection.js
  assets/js/state/selectors/checksSelection.test.js
  assets/js/state/selectors/hostChecksSelection.js
  assets/js/state/selectors/hostChecksSelection.test.js
Labels: enhancement, user story, chore, javascript

#1650 Upgrade Storybook to 7.1
  assets/package-lock.json
  assets/package.json
Labels: chore

#1649 Add end-to-end deregistration tests for Host Details page
  assets/js/components/CleanUpButton/CleanUpButton.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.jsx
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
Labels: javascript, test

#1672 Remove app db instances state
  assets/js/state/databases.js
  assets/js/state/databases.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
Labels: bug

#1659 Cluster settings page refactor
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionGroup.jsx
  assets/js/components/ClusterDetails/ChecksSelectionGroup.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.test.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterDetails/index.js
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/components/ClusterSettingsPage/index.js
  assets/js/trento.jsx
Labels: chore

#1678 Return whole host read model in registered projection
  lib/trento/application/projectors/host_projector.ex
  test/trento/application/projectors/host_projector_test.exs
Labels: bug
