Repository trento-project/web, pull requests merged in 2023-02, with the labels that each got.

#1171 Disable CronJobs when run from IEx in `dev`
  config/dev.exs
Labels: tech debt, elixir

#1137 Remove legacy runner backend
  config/config.exs
  config/demo.exs
  config/dev.exs
  config/runtime.exs
  config/test.exs
  config/wanda.exs
  lib/trento/application.ex
  lib/trento/application/integration/checks/adapter/gen.ex
  lib/trento/application/integration/checks/adapter/mock_runner.ex
  lib/trento/application/integration/checks/adapter/runner.ex
  lib/trento/application/integration/checks/adapter/wanda/messaging/amqp/consumer.ex
  lib/trento/application/integration/checks/adapter/wanda/wanda.ex
  lib/trento/application/integration/checks/checks.ex
  lib/trento/application/integration/checks/dto/catalog_dto.ex
  lib/trento/application/integration/checks/dto/check_dto.ex
  lib/trento/application/integration/checks/dto/execution_completed_event_dto.ex
  lib/trento/application/integration/checks/dto/flat_catalog_dto.ex
  lib/trento/application/integration/checks/dto/flat_check_dto.ex
  lib/trento/application/integration/checks/dto/group_dto.ex
  lib/trento/application/integration/checks/dto/provider_dto.ex
  lib/trento/application/usecases/clusters/adapters/gen.ex
  lib/trento/application/usecases/clusters/adapters/runner.ex
  lib/trento/application/usecases/clusters/adapters/wanda.ex
  lib/trento/application/usecases/clusters/clusters.ex
  lib/trento_web/controllers/catalog_controller.ex
  lib/trento_web/controllers/cluster_controller.ex
  lib/trento_web/controllers/mock_runner_controller.ex
  lib/trento_web/openapi/schema/runner.ex
  lib/trento_web/router.ex
  test/fixtures/runner/catalog.json
  test/trento/application/integration/checks/checks_test.exs
  test/trento/application/usecases/clusters_test.exs
  test/trento_web/controllers/catalog_controller_test.exs
  test/trento_web/controllers/cluster_controller_test.exs
Labels: removal

#1170 Remove legacy runner events
  lib/trento/application/event_handlers/checks_event_handler.ex
  lib/trento/application/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/application/integration/checks/adapter/wanda/messaging/amqp/processor.ex
  lib/trento/application/projectors/check_result_projector.ex
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/read_models/check_result_read_model.ex
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/application/read_models/host_checks_executions_read_model.ex
  lib/trento/application/usecases/clusters/clusters.ex
  lib/trento/application/usecases/hosts/host_connection_settings.ex
  lib/trento/application/usecases/hosts/hosts.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/cluster/commands/complete_checks_execution.ex
  lib/trento/domain/cluster/commands/complete_checks_execution_wanda.ex
  lib/trento/domain/cluster/commands/request_checks_execution.ex
  lib/trento/domain/cluster/commands/start_checks_execution.ex
  lib/trento/domain/cluster/events/legacy/checks_execution_completed.ex
  lib/trento/domain/cluster/events/legacy/checks_execution_requested.ex
  lib/trento/domain/cluster/events/legacy/checks_execution_started.ex
  lib/trento/domain/cluster/events/legacy/host_checks_execution_completed.ex
  lib/trento/domain/value_objects/legacy/check_result.ex
  lib/trento/domain/value_objects/legacy/host_execution.ex
  lib/trento/infrastructure/event_handlers_supervisor.ex
  lib/trento/infrastructure/projectors_supervisor.ex
  lib/trento/infrastructure/router.ex
  lib/trento_web/openapi/schema/checks.ex
  lib/trento_web/openapi/schema/cluster.ex
  priv/repo/migrations/20230123162618_remove_host_connection_settings.exs
  priv/repo/migrations/20230123162816_remove_check_result_read_model.exs
  priv/repo/migrations/20230123162928_remove_host_checks_executions_read_model.exs
  test/support/factory.ex
  test/trento/application/event_handlers/checks_event_handler_test.exs
  test/trento/application/integration/checks/wanda/messaging/amqp/processor_test.exs
  test/trento/application/projectors/check_result_projector_test.exs
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento/application/usecases/hosts_test.exs
  test/trento/domain/cluster/cluster_test.exs
Labels: removal

#1179 Run CI `test` step on different versions of Elixir & OTP
  .github/workflows/ci.yaml
  .tool-versions
Labels: tech debt, elixir

#1185 Remove architecture docs
  guides/architecture/trento-architecture.md
  guides/assets/event-sourcing-cqrs.png
  guides/assets/trento-architecture.png
  guides/authentication/spa_flow.md
  guides/monitoring/monitoring.md
Labels: documentation, removal

#1186 Fix docs creation
  README.md
  mix.exs
Labels: documentation, chore

#1150 Update the Readme and hack_on_trento guide
  README.md
  guides/development/hack_on_the_trento.md
Labels: documentation

#1197 Fix css bugs
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/Table/Filter.jsx
Labels: bug

#1205 Fix home page filters background color on selected
  assets/js/components/HealthSummary/HealthSummaryBox.jsx
Labels: bug

#1198 Check base url injected into the client via global config object
  assets/build.js
  assets/jest.config.js
  assets/js/lib/api/checks.js
  assets/package.json
  config/dev.exs
  config/runtime.exs
  guides/development/hack_on_the_trento.md
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/templates/page/index.html.heex
Labels: javascript, elixir

#1202 Fix Check selection hint style
  assets/js/components/ExecutionResults/ChecksSelectionHints.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/ResultsContainer.test.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.jsx
Labels: bug, enhancement, chore

#1206 Fix start execution interaction
  assets/js/components/ClusterDetails/ChecksResultOverview.jsx
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.test.jsx
  assets/js/lib/api/checks.js
  assets/js/lib/test-utils/index.jsx
  assets/js/state/actions/lastExecutions.js
  assets/js/state/actions/notifications.js
  assets/js/state/lastExecutions.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/lastExecutions.js
  assets/js/state/sagas/lastExecutions.test.js
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
Labels: bug, enhancement

#1201 Add new demo-deploy dispatch action
  .github/workflows/ci.yaml
Labels: ci

#1210 Cleanup Cluster selectors
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
  assets/js/state/selectors/index.js
Labels: enhancement, chore

#1214 Fix flag short option in the dump script
  hack/dump_scenario_from_k8.sh
Labels: bug

#1216 Add generic Table filtering tests on jest
  assets/js/components/Table/Table.test.jsx
Labels: test
