Repository trento-project/web, pull requests merged in 2023-04, with the labels that each got.

#1293 Visually identify premium checks in the ExecutionResults view
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/checksUtils.js
  assets/js/components/ExecutionResults/checksUtils.test.js
Labels: enhancement, javascript

#1280 Cluster deregistered side effects
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/application/usecases/clusters/clusters.ex
  priv/repo/migrations/20230323161309_add_deregistered_at_to_cluster_read_model.exs
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento/application/projectors/host_projector_test.exs
  test/trento/application/usecases/clusters_test.exs
Labels: elixir

#1304 Add a story for the WarningBanner component
  assets/js/components/Banners/WarningBanner.stories.jsx
Labels: enhancement, javascript

#1307 Added Tooltip story
  assets/js/components/Tooltip/Tooltip.stories.jsx
Labels: chore, ux

#1310 Add stories for the AboutPage components
  assets/js/components/AboutPage/AboutPage.stories.jsx
Labels: enhancement, chore, javascript

#1317 Fact value primitive types
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.test.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/FactValue.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/FactValue.test.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/GatheredFacts.jsx
  assets/js/lib/test-utils/factories/executions.js
  assets/js/lib/test-utils/factories/index.js
Labels: bug

#1327 Idempotent user seeding
  priv/repo/seeds.exs
Labels: chore, elixir

#1335 Make api key enablement configurable in runtime
  config/config.exs
  config/dev.exs
  config/runtime.exs
  config/test.exs
  lib/trento_web/router.ex
  mix.exs
  mix.lock
Labels: chore

#1326 Database registration changes
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: elixir

#1314 Add SAP System deregistration commands & events
  lib/trento/domain/sap_system/commands/deregister_application_instance.ex
  lib/trento/domain/sap_system/commands/deregister_database_instance.ex
  lib/trento/domain/sap_system/events/application_instance_deregistered.ex
  lib/trento/domain/sap_system/events/database_deregistered.ex
  lib/trento/domain/sap_system/events/database_instance_deregistered.ex
  lib/trento/domain/sap_system/events/sap_system_deregistered.ex
Labels: elixir

#1325 Clean up legacy code
  assets/js/components/ExecutionResults/CheckResult.jsx
  assets/js/components/ExecutionResults/CheckResult.test.jsx
  assets/js/components/ExecutionResults/ChecksResultFilters.jsx
  assets/js/components/ExecutionResults/ExecutionIcon.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/HostResultsWrapper.jsx
  assets/js/components/ExecutionResults/checksUtils.js
  assets/js/components/ExecutionResults/checksUtils.test.js
Labels: chore

#1368 Release 2.0.0
  CHANGELOG.md
  mix.exs
  test/e2e/package-lock.json
  test/e2e/package.json
Labels: release

#1364 Add url error handling for the CheckResultDetailPage
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetailPage.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetailPage.test.jsx
  assets/js/components/NotFound/NotFound.jsx
  assets/js/components/NotFound/NotFound.stories.jsx
  assets/js/components/NotFound/NotFound.test.jsx
  assets/js/lib/model/index.js
  assets/js/lib/test-utils/factories/executions.js
Labels: enhancement, chore, javascript
