Repository trento-project/web, pull requests merged in 2023-01, with the labels that each got.

#1080 Tooltip, SomethingWentWrong unit tests
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/components/SapSystemDetails/Features.jsx
  assets/js/components/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/components/SapSystemDetails/GenericSystemDetails.test.jsx
  assets/js/components/SapSystemDetails/InstanceStatus.jsx
  assets/js/components/SapSystemDetails/index.js
  assets/js/components/SapSystemDetails/tableConfigs.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.test.jsx
  assets/js/components/SomethingWentWrong/SomethingWentWrong.test.jsx
  assets/js/components/Tooltip/Tooltip.test.jsx
  assets/js/lib/test-utils/factories/hosts.js
  assets/js/lib/test-utils/factories/index.js
  assets/js/lib/test-utils/factories/sapSystems.js
Labels: chore

#1097 Add provider icon host views
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterDetailsNew.jsx
  assets/js/components/ClusterDetails/ClusterInfoBox.jsx
  assets/js/components/HostDetails/ProviderDetails.jsx
  assets/js/components/HostDetails/ProviderDetails.test.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/components/ProviderLabel/ProviderLabel.jsx
  assets/js/components/ProviderLabel/ProviderLabel.test.jsx
  assets/js/components/ProviderLabel/index.js
  test/e2e/cypress/fixtures/host-details/selected_host.js
  test/e2e/cypress/fixtures/hosts-overview/available_hosts.js
Labels: enhancement

#1094 Remove connection settings when using wanda
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
  assets/js/components/ClusterDetails/ChecksSelectionNew.test.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterDetails/ClusterSettingsNew.jsx
  assets/js/components/ClusterDetails/ClusterSettingsNew.test.jsx
  assets/js/components/ClusterDetails/index.js
  assets/js/lib/test-utils/index.jsx
  assets/js/trento.jsx
Labels: enhancement

#1105 Fix e2e
  assets/js/components/Table/Filter.jsx
  test/e2e/cypress/e2e/clusters_overview.cy.js
Labels: chore

#1098 Allow getCatalog wanda call to filter by provider
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
  assets/js/lib/api/wanda.js
  assets/js/state/actions/catalog.js
  assets/js/state/sagas/catalog.js
  assets/js/state/sagas/catalog.test.js
Labels: enhancement, javascript

#1109 Socket Initialization on user login
  assets/js/lib/api/wanda.js
  assets/js/lib/network/socket.js
  assets/js/state/actions/catalog.js
  assets/js/state/channels.js
  assets/js/state/index.js
  assets/js/state/sagas/index.js
Labels: bug, javascript

#1114 Add remediation content
  assets/js/components/ChecksResults/checksUtils.js
  assets/js/components/ChecksResults/checksUtils.test.js
  assets/js/components/ChecksResults/index.js
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/Modal/Modal.jsx
Labels: enhancement

#1115 Add premium pill to the check selection view
  assets/js/components/ChecksCatalog/CheckItem.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
  assets/js/components/Pill/Pill.jsx
  assets/js/components/Pill/Pill.test.jsx
  assets/js/components/PremiumPill.jsx
  assets/js/lib/test-utils/factories/index.js
Labels: enhancement

#1076 Remove redux logic from TriggerChecksExecutionRequest component
  assets/js/components/ChecksResults/ChecksResults.jsx
  assets/js/components/ChecksResults/ChecksSelectionHints.jsx
  assets/js/components/ChecksResults/ResultsContainer.jsx
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterDetailsNew.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterDetails/ConnectionSettings.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.test.jsx
Labels: enhancement, javascript

#1120 Adjust markdown component in execution results
  assets/js/components/ExecutionResults/ExecutionResults.jsx
Labels: chore

#1121 Fix prettier checker
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/package.json
Labels: bug, chore

#1116 Add Authentication Documentation as ExDoc guide
  guides/assets/trento-spa-login.png
  guides/assets/trento-spa-refresh-failed.png
  guides/assets/trento-spa-refresh.png
  guides/authentication/jwt_specification.md
  guides/authentication/spa_flow.md
  guides/development/environment_variables.md
  mix.exs
Labels: documentation

#1129 Freeze demo deployment stages in ci
  .github/workflows/ci.yaml
Labels: chore

#1130 Bump BCI base image to 15.4
  Dockerfile
  packaging/suse/Dockerfile
Labels: enhancement

#1138 Fix layout rendering when not logged-in
  assets/js/trento.jsx
Labels: bug

#1136 Add a checks provider filter for catalog_new view
  assets/js/components/ChecksCatalog/ChecksCatalogNew.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogNew.test.jsx
  assets/js/components/ProviderLabel/ProviderLabel.jsx
  assets/js/components/ProviderLabel/ProviderLabel.test.jsx
Labels: enhancement, javascript

#1134 Remove legacy catalog frontend
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogNew.jsx
  assets/js/components/ChecksCatalog/index.js
  assets/js/components/ClusterDetails/ChecksSelectionNew.test.jsx
  assets/js/components/ClusterDetails/ClusterSettingsNew.test.jsx
  assets/js/state/actions/catalog.js
  assets/js/state/catalog.js
  assets/js/state/catalog.test.js
  assets/js/state/catalogNew.js
  assets/js/state/index.js
  assets/js/state/sagas/catalog.js
  assets/js/state/sagas/catalog.test.js
  assets/js/state/sagas/index.js
  assets/js/state/selectors/catalog.js
  assets/js/state/selectors/catalog.test.js
  assets/js/trento.jsx
  test/e2e/cypress/e2e/checks_catalog.cy.js
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/fixtures/checks-catalog/available_checks.js
  test/e2e/cypress/fixtures/checks-catalog/checks_catalog.feature
  test/e2e/cypress/plugins/index.js
  test/e2e/package-lock.json
  test/e2e/package.json
  test/e2e/webpack.config.js
Labels: removal

#1147 Remove legacy cluster details
  assets/js/components/ChecksResults/ChecksResults.jsx
  assets/js/components/ChecksResults/index.js
  assets/js/components/ClusterDetails/ChecksResultOverview.jsx
  assets/js/components/ClusterDetails/ChecksResultOverview.test.jsx
  assets/js/components/ClusterDetails/ChecksResultOverviewNew.jsx
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionNew.jsx
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterDetailsNew.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterDetails/ClusterSettings.test.jsx
  assets/js/components/ClusterDetails/ClusterSettingsNew.jsx
  assets/js/components/ClusterDetails/ConnectionSettings.jsx
  assets/js/components/ClusterDetails/index.js
  assets/js/components/ExecutionResults/CheckResult.jsx
  assets/js/components/ExecutionResults/CheckResult.test.jsx
  assets/js/components/ExecutionResults/ChecksResultFilters.jsx
  assets/js/components/ExecutionResults/ChecksSelectionHints.jsx
  assets/js/components/ExecutionResults/ExecutionIcon.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/HostResultsWrapper.jsx
  assets/js/components/ExecutionResults/ResultsContainer.jsx
  assets/js/components/ExecutionResults/ResultsContainer.test.jsx
  assets/js/components/ExecutionResults/checksUtils.js
  assets/js/components/ExecutionResults/checksUtils.test.js
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.jsx
  assets/js/components/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.test.jsx
  assets/js/state/clusterConnectionSettings.js
  assets/js/state/index.js
  assets/js/state/sagas/index.js
  assets/js/trento.jsx
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
Labels: removal

#1141 Page components enhancements
  assets/js/components/BackButton/BackButton.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClustersList.jsx
  assets/js/components/DatabaseDetails/DatabaseDetails.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.jsx
  assets/js/components/Health/HealthIcon.jsx
  assets/js/components/HealthSummary/HealthSummaryBox.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/StatusPill.jsx
  assets/js/components/HostDetails/StatusPill.test.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/Layout/Layout.jsx
  assets/js/components/PageHeader/PageHeader.jsx
  assets/js/components/PageHeader/PageHeader.test.jsx
  assets/js/components/PageHeader/index.js
  assets/js/components/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/components/SapSystemDetails/SapSystemDetails.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
  assets/js/components/Settings/Settings.jsx
  assets/js/components/Table/Filter.jsx
  assets/js/components/Table/Pagination.jsx
  assets/js/components/Table/Table.jsx
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
Labels: enhancement, ux, javascript

#1140 Execution started event
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/state/channels.js
  assets/js/state/lastExecutions.js
  assets/js/state/lastExecutions.test.js
  lib/trento/application/integration/checks/adapter/wanda/messaging/amqp/processor.ex
  mix.exs
  mix.lock
  test/trento/application/integration/checks/wanda/messaging/amqp/processor_test.exs
Labels: javascript, elixir
