Repository trento-project/web, pull requests merged in 2023-08, with the labels that each got.

#1687 Fix SR status broadcast on database instance registration
  lib/trento/application/projectors/database_projector.ex
  lib/trento/domain/sap_system/sap_system.ex
  lib/trento_web/views/v1/sap_system_view.ex
  test/e2e/cypress/e2e/databases_overview.cy.js
  test/trento/application/projectors/database_projector_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: bug

#1688 Prepare for relase 2.1.0
  CHANGELOG.md
  mix.exs
  test/e2e/package-lock.json
  test/e2e/package.json
Labels: release

#1682 Make checks selection great again
  assets/js/components/Button/Button.jsx
  assets/js/components/Button/Button.stories.jsx
  assets/js/components/Button/Button.test.jsx
  assets/js/components/ChecksSelection/ChecksSelection.jsx
  assets/js/components/ChecksSelection/ChecksSelection.test.jsx
  assets/js/components/ChecksSelection/index.js
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.test.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/components/HostDetails/HostSettingsPage.test.jsx
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
Labels: enhancement

#1669 Host Checks selection
  assets/css/app.css
  assets/css/tooltip.scss
  assets/js/components/Button/Button.jsx
  assets/js/components/Button/Button.stories.jsx
  assets/js/components/Button/Button.test.jsx
  assets/js/components/ChecksSelection/ChecksSelection.jsx
  assets/js/components/ChecksSelection/ChecksSelection.test.jsx
  assets/js/components/ChecksSelection/index.js
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionGroup.jsx
  assets/js/components/ClusterDetails/ChecksSelectionGroup.test.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.jsx
  assets/js/components/ClusterDetails/ChecksSelectionItem.test.jsx
  assets/js/components/ClusterDetails/ClusterNodeLink.jsx
  assets/js/components/ClusterDetails/ClusterNodeLink.test.jsx
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterDetails/index.js
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/components/ClusterSettingsPage/index.js
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.test.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/components/HostDetails/HostSettingsPage.test.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/components/Pill/Pill.stories.jsx
  assets/js/components/Tooltip/Tooltip.jsx
  assets/js/components/Tooltip/Tooltip.stories.jsx
  assets/js/components/Tooltip/Tooltip.test.jsx
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
  assets/js/trento.jsx
  assets/package-lock.json
  assets/package.json
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
Labels: enhancement

#1690 Add API backward compatibility check in pipeline
  .github/workflows/ci.yaml
Labels: enhancement, ci

#1704 Pull request environment
  .github/workflows/pr_env.yaml
  .github/workflows/pr_env_close.yaml
Labels: enhancement, env

#1706 Restore a SAP system only when the database is present
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: bug, env

#1717 Upgrade to Storybook 7.3.1
  assets/package-lock.json
  assets/package.json
Labels: chore

#1710 Fix host checks selection ui
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.test.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  assets/js/state/selectors/host.js
  assets/js/state/selectors/host.test.js
  assets/js/state/selectors/index.js
Labels: javascript, env

#1707 Add wanda demo to pr env
  .github/workflows/pr_env.yaml
  .github/workflows/pr_env_close.yaml
Labels: enhancement, env

#1738 Use ProviderLabel on sap and db detail views
  assets/js/components/SapSystemDetails/tableConfigs.jsx
  test/e2e/cypress/fixtures/hana-database-details/selected_database.js
  test/e2e/cypress/fixtures/sap-system-details/selected_system.js
Labels: bug

#1733 Forbid not registered instances deregistration
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: enhancement

#1745 Refactor sap system and database reducers
  assets/js/state/databases.js
  assets/js/state/databases.test.js
  assets/js/state/instances.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
Labels: chore, env

#1739 Bump contracts version to latest containing target type
  mix.exs
  mix.lock
Labels: enhancement, dependencies

#1737 Allow additional classes to be specified on the clean up button
  assets/js/components/Button/Button.jsx
  assets/js/components/Button/Button.stories.jsx
  assets/js/components/CleanUpButton/CleanUpButton.jsx
  assets/js/components/CleanUpButton/CleanUpButton.stories.jsx
  assets/js/components/HostsList.jsx
Labels: enhancement, ux, javascript

#1730 Instance deregistration endpoint
  lib/trento/application/read_models/application_instance_read_model.ex
  lib/trento/application/read_models/database_instance_read_model.ex
  lib/trento/application/usecases/sap_systems/sap_systems.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/sap_system_controller.ex
  lib/trento_web/router.ex
  priv/repo/migrations/20230822144338_add_absent_at_application_instance_read_model.exs
  priv/repo/migrations/20230822144348_add_absent_at_database_instance_read_model.exs
  test/support/factory.ex
  test/trento/application/usecases/sap_systems_test.exs
  test/trento_web/controllers/v1/sap_system_controller_test.exs
Labels: enhancement

#1758 Refactor sap system selectors
  assets/js/components/ClustersList.jsx
  assets/js/components/DatabaseDetails/DatabaseDetails.jsx
  assets/js/components/DatabaseDetails/DatabaseDetails.stories.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/components/SapSystemDetails/SapSystemDetails.jsx
  assets/js/components/SapSystemDetails/SapSystemDetails.stories.jsx
  assets/js/components/SapSystemDetails/tableConfigs.jsx
  assets/js/lib/test-utils/factories/sapSystems.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/index.js
  assets/js/state/selectors/index.test.js
  assets/js/state/selectors/sapSystem.js
  assets/js/state/selectors/sapSystem.test.js
Labels: tech debt, chore, env

#1746 Instance deregistration sagas
  assets/js/state/databases.js
  assets/js/state/databases.test.js
  assets/js/state/hosts.js
  assets/js/state/hosts.test.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/databases.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
Labels: enhancement

#1740 Host checks execution api
  lib/trento/application/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/application/integration/checks/amqp/processor.ex
  lib/trento/application/integration/checks/checks.ex
  lib/trento/application/integration/checks/host_executions_env.ex
  lib/trento/application/integration/checks/target_type.ex
  lib/trento/application/usecases/clusters/clusters.ex
  lib/trento/application/usecases/hosts/hosts.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/cluster_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/router.ex
  test/support/factory.ex
  test/trento/application/integration/checks/checks_test.exs
  test/trento/application/integration/checks/processor_test.exs
  test/trento/application/usecases/clusters_test.exs
  test/trento/application/usecases/hosts_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement, user story, elixir

#1764 SapSystemsOverview and DatabasesOverview storybook
  assets/js/components/DatabasesOverview/DatabasesOverview.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.stories.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.test.jsx
  assets/js/components/DatabasesOverview/DatabasesOverviewPage.jsx
  assets/js/components/DatabasesOverview/index.js
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.stories.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.test.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverviewPage.jsx
  assets/js/components/SapSystemsOverview/index.js
  assets/js/lib/test-utils/factories/databases.js
  assets/js/trento.jsx
Labels: tech debt

#1753 Host checks execution frontend
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.stories.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/components/HostDetails/HostSettingsPage.test.jsx
  assets/js/lib/api/checks.js
  assets/js/state/actions/lastExecutions.js
  assets/js/state/lastExecutions.js
  assets/js/state/lastExecutions.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/lastExecutions.js
  assets/js/state/sagas/lastExecutions.test.js
Labels: enhancement, javascript, env

#1752 Node details label for ASCS/ERS cluster details
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/components/ClusterDetails/AttributesDetails.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.test.jsx
Labels: bug, chore

#1731 Add ability to mark instances as absent
  lib/trento/application/integration/discovery/policies/sap_system_policy.ex
  lib/trento/domain/sap_system/commands/mark_application_instance_absent.ex
  lib/trento/domain/sap_system/commands/mark_database_instance_absent.ex
  lib/trento/domain/sap_system/events/application_instance_marked_absent.ex
  lib/trento/domain/sap_system/events/application_instance_marked_present.ex
  lib/trento/domain/sap_system/events/database_instance_marked_absent.ex
  lib/trento/domain/sap_system/events/database_instance_marked_present.ex
  lib/trento/domain/sap_system/instance.ex
  lib/trento/domain/sap_system/sap_system.ex
  test/support/factory.ex
  test/trento/application/integration/discovery/policies/sap_system_policy_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: enhancement, elixir, env

#1772 Update deregistration modal to include instances content
  assets/js/components/DeregistrationModal/DeregistrationModal.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.stories.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.test.jsx
Labels: enhancement

#1747 Implement instance style changes on absent case
  assets/js/components/CleanUpButton/CleanUpButton.jsx
  assets/js/components/CleanUpButton/CleanUpButton.stories.jsx
  assets/js/components/DatabasesOverview/DatabaseItemOverview.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.stories.jsx
  assets/js/components/Health/HealthIcon.jsx
  assets/js/components/Health/HealthIcon.stories.jsx
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  assets/js/components/InstanceOverview/InstanceOverview.test.jsx
  assets/js/components/SapSystemsOverview/SapSystemItemOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.stories.jsx
  assets/js/components/Table/CollapsibleTableRow.jsx
  assets/js/components/Table/Table.jsx
Labels: enhancement, ux, env
