Repository trento-project/web, pull requests merged in 2023-09, with the labels that each got.

#1781 rowKey function for table rows
  assets/js/components/Table/Table.jsx
  assets/js/components/Table/Table.test.jsx
  assets/js/components/Table/defaultRowKey.js
Labels: chore

#1782 Use rowKey in sap system and database overview tables
  assets/js/components/DatabasesOverview/DatabasesOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
Labels: bug

#1780 Host checks execution scheduler
  config/config.exs
  config/demo.exs
  config/dev.exs
  config/runtime.exs
  lib/trento/application/usecases/hosts/hosts.ex
  test/trento/application/usecases/clusters_test.exs
  test/trento/application/usecases/hosts_test.exs
Labels: elixir, test, env

#1779 Make frontend listen for events when instances' presence changes
  assets/js/lib/test-utils/factories/databases.js
  assets/js/lib/test-utils/factories/sapSystems.js
  assets/js/state/channels.js
  assets/js/state/databases.js
  assets/js/state/databases.test.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/databases.test.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
Labels: enhancement, javascript

#1771 Clean up e2e tests from unnecessary content
  test/e2e/cypress/fixtures/about/about.feature
  test/e2e/cypress/fixtures/hana-cluster-details/hana_cluster_details.feature
  test/e2e/cypress/fixtures/hana-database-details/hana_database_details.feature
  test/e2e/cypress/fixtures/host-details/host_details.feature
  test/e2e/cypress/fixtures/hosts-overview/hosts_overview.feature
  test/e2e/cypress/fixtures/sap-system-details/sap_system_details.feature
  test/e2e/cypress/fixtures/sap-systems-overview/sap_systems_overview.feature
  test/fixtures/scenarios/about/about.feature
  test/fixtures/scenarios/checks-catalog/catalog.json
  test/fixtures/scenarios/checks-catalog/checks_catalog.feature
  test/fixtures/scenarios/clusters-overview/checks_results_critical.json
  test/fixtures/scenarios/clusters-overview/checks_results_passing.json
  test/fixtures/scenarios/clusters-overview/checks_results_warning.json
  test/fixtures/scenarios/clusters-overview/clusters_overview.feature
  test/fixtures/scenarios/hana-cluster-details/checks_results.json
  test/fixtures/scenarios/hana-database-details/hana_database_details.feature
  test/fixtures/scenarios/host-details/host_details.feature
  test/fixtures/scenarios/hosts-overview/hosts_overview.feature
  test/fixtures/scenarios/sap-system-details/sap_system_details.feature
  test/fixtures/scenarios/sap-systems-overview/sap_systems_overview.feature
Labels: chore, removal

#1793 Host details storybook
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.stories.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/HostDetailsPage.jsx
  assets/js/components/HostDetails/index.js
  assets/js/trento.jsx
Labels: chore, dx

#1783 Instance cleanup e2e
  .photofinish.toml
  test/e2e/cypress/e2e/databases_overview.cy.js
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
  test/fixtures/scenarios/sap-systems-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_sap_system_discovery_absent.json
  test/fixtures/scenarios/sap-systems-overview/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_sap_system_discovery_absent.json
  test/fixtures/scenarios/sap-systems-overview/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery_absent.json
Labels: chore, test

#1790 Application Instance Move only if clustered
  .photofinish.toml
  assets/js/components/DatabasesOverview/DatabaseItemOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemItemOverview.jsx
  lib/trento/application/integration/discovery/discovery.ex
  lib/trento/application/integration/discovery/policies/sap_system_policy.ex
  lib/trento/domain/sap_system/commands/register_application_instance.ex
  lib/trento/domain/sap_system/sap_system.ex
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
  test/e2e/cypress/support/commands.js
  test/fixtures/scenarios/sap-systems-overview/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_sap_system_discovery_NOT_MOVED.json
  test/fixtures/scenarios/sap-systems-overview/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_sap_system_discovery_MOVED.json
  test/trento/application/integration/discovery/policies/sap_system_policy_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: env

#1811 Improve app instance present toast
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
Labels: bug

#1810 Fix instance movement logic
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: bug, env

#1796 Saptune summary frontend
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.stories.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/HostDetailsPage.jsx
  assets/js/components/HostDetails/SaptuneSummary.jsx
  assets/js/components/HostDetails/SaptuneSummary.test.jsx
  assets/js/components/SaptuneDetails/SaptuneTuningState.jsx
  assets/js/components/SaptuneDetails/SaptuneTuningState.test.jsx
  assets/js/components/SaptuneDetails/SaptuneVersion.jsx
  assets/js/components/SaptuneDetails/SaptuneVersion.test.jsx
  assets/js/components/SaptuneDetails/index.js
  assets/js/lib/saptune/index.js
  assets/js/lib/saptune/saptune.test.js
  assets/js/lib/test-utils/factories/hosts.js
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/fixtures/host-details/selected_host.js
Labels: enhancement

#1801 Handle saptune payload
  lib/trento/application/integration/discovery/discovery.ex
  lib/trento/application/integration/discovery/payloads/saptune_discovery_payload.ex
  lib/trento/application/integration/discovery/policies/host_policy.ex
  lib/trento/domain/host/commands/update_saptune_status.ex
  lib/trento/domain/value_objects/saptune_note.ex
  lib/trento/domain/value_objects/saptune_service_status.ex
  lib/trento/domain/value_objects/saptune_solution.ex
  lib/trento/domain/value_objects/saptune_staging.ex
  lib/trento/domain/value_objects/saptune_status.ex
  test/fixtures/discovery/saptune_discovery.json
  test/fixtures/discovery/saptune_discovery_empty_result.json
  test/fixtures/discovery/saptune_discovery_empty_status.json
  test/trento/application/integration/discovery/policies/host_policy_test.exs
Labels: enhancement, elixir

#1809 Host Check result detail
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/BackToTargetExecution.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckDetailHeader.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckDetailHeader.test.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetailPage.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultInfoBox.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultInfoBox.test.jsx
  assets/js/components/ExecutionResults/CheckResultOutline.jsx
  assets/js/components/ExecutionResults/CheckResultOutline.test.jsx
  assets/js/components/ExecutionResults/ExecutionHeader.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/ExecutionResults/checksUtils.js
  assets/js/components/ExecutionResults/checksUtils.test.js
  assets/js/lib/test-utils/factories/executions.js
  assets/js/trento.jsx
Labels: enhancement, user story, ux, javascript, env

#1800 Saptune domain
  lib/trento/domain/host/commands/update_saptune_status.ex
  lib/trento/domain/host/events/saptune_status_updated.ex
  lib/trento/domain/host/host.ex
  lib/trento/infrastructure/router.ex
  test/support/factory.ex
  test/trento/domain/host/host_test.exs
Labels: enhancement

#1821 Saptune status projection
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento_web/openapi/v1/schema/host.ex
  lib/trento_web/openapi/v1/schema/saptune_status.ex
  lib/trento_web/views/v1/host_view.ex
  priv/repo/migrations/20230905141817_add_saptune_status_host_read_model.exs
  test/support/factory.ex
  test/trento/application/projectors/host_projector_test.exs
Labels: enhancement

#1802 Add tooltip above `Start Execution` button
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.test.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
Labels: enhancement, javascript

#1825 Enable navigation from host details to check results
  assets/js/components/HostDetails/HostDetails.jsx
Labels: chore

#1822 Listen to saptune update broadcast messages in frontend
  assets/js/components/HostDetails/HostDetailsPage.jsx
  assets/js/state/channels.js
  assets/js/state/hosts.js
  assets/js/state/hosts.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
Labels: enhancement

#1836 Fix typo on tuning word
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/SaptuneSummary.jsx
  assets/js/components/HostDetails/SaptuneSummary.test.jsx
Labels: bug

#1834 Align `primary` button style `disabled` state with UI proposal
  assets/js/components/Button/Button.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostDetails.jsx
Labels: ux, javascript, env

#1833 Set solutions to nil if not found
  lib/trento/application/integration/discovery/policies/host_policy.ex
  test/fixtures/discovery/saptune_discovery_not_configured.json
  test/trento/application/integration/discovery/policies/host_policy_test.exs
Labels: enhancement

#1842 Uniform Target Checks Selection
  assets/js/components/ChecksSelection/ChecksSelectionHeader.jsx
  assets/js/components/ChecksSelection/ChecksSelectionHeader.stories.jsx
  assets/js/components/ChecksSelection/ChecksSelectionHeader.test.jsx
  assets/js/components/ChecksSelection/FailAlert.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/HostDetails/HostChecksSelection.jsx
  assets/js/components/HostDetails/HostChecksSelection.stories.jsx
  assets/js/components/HostDetails/HostChecksSelection.test.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
Labels: tech debt, chore, javascript

#1843 Port check results detail page selectors to reselect
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetailPage.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
  assets/js/state/selectors/host.js
  assets/js/state/selectors/host.test.js
Labels: chore

#1848 Determine host health
  lib/trento/application/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/domain/host/commands/complete_checks_execution.ex
  lib/trento/domain/host/events/host_checks_health_changed.ex
  lib/trento/domain/host/events/host_health_changed.ex
  lib/trento/domain/host/host.ex
  lib/trento/infrastructure/router.ex
  test/support/factory.ex
  test/trento/domain/host/host_test.exs
Labels: enhancement, user story, elixir

#1866 Downgrade remark-gfm until it gets fixed upstream
  assets/package-lock.json
  assets/package.json
Labels: bug, dependencies, env

#1859 Dispatch host checks execution completion command
  lib/trento/application/integration/checks/checks.ex
  test/trento/application/integration/checks/checks_test.exs
Labels: enhancement, user story, elixir

#1858 Exclude checks result from host's health when empty selection is saved
  lib/trento/domain/host/host.ex
  test/trento/domain/host/host_test.exs
Labels: enhancement, user story, elixir

#1864 Checks results overview inside host details
  assets/js/components/CheckResultsOverview/CheckResultCount.jsx
  assets/js/components/CheckResultsOverview/CheckResultsOverview.jsx
  assets/js/components/CheckResultsOverview/CheckResultsOverview.stories.jsx
  assets/js/components/CheckResultsOverview/CheckResultsOverview.test.jsx
  assets/js/components/CheckResultsOverview/index.js
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.stories.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/HostDetailsPage.jsx
Labels: enhancement, javascript

#1871 Add health to host read model
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento/domain/host/events/host_registered.ex
  lib/trento_web/views/v1/host_view.ex
  priv/repo/migrations/20230926082236_add_host_health.exs
  test/support/factory.ex
  test/trento/application/projectors/host_projector_test.exs
  test/trento/domain/host/events/host_registered_test.exs
  test/trento_web/views/v1/host_view_test.exs
Labels: enhancement, user story, elixir

#1885 Fix cache-miss in CI pipeline
  .github/workflows/ci.yaml
Labels: ci
