Repository trento-project/web, pull requests merged in 2023-03, with the labels that each got.

#1215 Remove table filtering tests from cypress suite
  test/e2e/cypress/e2e/clusters_overview.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
Labels: removal

#1224 Vmware provider
  .photofinish.toml
  assets/js/components/ClusterDetails/ClusterInfoBox.test.jsx
  assets/js/components/HostDetails/ProviderDetails.jsx
  assets/js/components/HostDetails/ProviderDetails.test.jsx
  assets/js/components/ProviderLabel/ProviderLabel.jsx
  assets/js/components/ProviderLabel/ProviderLabel.test.jsx
  assets/static/vmware-logo.png
  lib/trento/domain/enums/provider.ex
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/fixtures/host-details/selected_host.js
  test/fixtures/discovery/cloud_discovery_vmware.json
  test/fixtures/scenarios/hana-cluster-details/b767b3e9-e802-587e-a442-541d093b86b9_ha_cluster_discovery_vmware_provider.json
  test/fixtures/scenarios/host-details/9cd46919-5f19-59aa-993e-cf3736c71053_cloud_discovery_vmware.json
  test/trento/application/integration/discovery/policies/host_policy_test.exs
Labels: javascript, elixir

#1226 Fix margin between filter elements
  assets/js/components/Table/Filter.jsx
Labels: bug, ux

#1223 Check based execution results
  assets/js/components/ExecutionResults/CheckResultOutline.jsx
  assets/js/components/ExecutionResults/ExecutionHeader.jsx
  assets/js/components/ExecutionResults/ExecutionHeader.test.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/TargetIcon.jsx
  assets/js/components/ExecutionResults/TargetResult.jsx
  assets/js/lib/model/index.js
  assets/js/lib/test-utils/factories/executions.js
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
Labels: enhancement, ux, javascript

#1228 Object tree component
  assets/.eslintrc.js
  assets/.storybook/main.js
  assets/js/components/ObjectTree/ObjectTree.jsx
  assets/js/components/ObjectTree/ObjectTree.stories.jsx
  assets/js/components/ObjectTree/ObjectTree.test.jsx
  assets/js/components/ObjectTree/ObjectTreeIcon.jsx
  assets/js/components/ObjectTree/ObjectTreeNode.jsx
  assets/js/components/ObjectTree/index.js
  assets/js/components/ObjectTree/tree.js
  assets/js/lib/test-utils/factories/index.js
  assets/package-lock.json
  assets/package.json
Labels: enhancement

#1235 Remove debug code
  assets/js/components/Table/CollapsibleTableRow.jsx
Labels: chore, removal

#1236 Fix some act wrapping warnings
  assets/js/components/ClustersList.test.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.test.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.test.jsx
  assets/js/components/Table/Table.test.jsx
Labels: bug

#1230 Filter Component UI fixes
  assets/js/components/Table/Filter.jsx
  assets/js/components/Table/Table.jsx
Labels: bug, ux

#1243 Add extra second to heartbeat interval to avoid glitches
  config/config.exs
Labels: bug

#1237 Host rollup
  lib/trento/application/event_handlers/roll_up_event_handler.ex
  lib/trento/application/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/domain/host/commands/rollup_host.ex
  lib/trento/domain/host/events/host_roll_up_requested.ex
  lib/trento/domain/host/events/host_rolled_up.ex
  lib/trento/domain/host/host.ex
  lib/trento/domain/host/lifespan.ex
  lib/trento/infrastructure/router.ex
  test/trento/application/event_handlers/stream_roll_up_event_handler_test.exs
  test/trento/domain/host/host_test.exs
Labels: elixir

#1244 Add Checks warning banner when provider is VMware
  assets/js/components/ClusterDetails/ClusterSettings.jsx
  assets/js/components/ClusterDetails/ClusterSettings.test.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/lib/test-utils/index.jsx
Labels: javascript

#1247 Fix remaining act warning
  assets/package-lock.json
  assets/package.json
Labels: bug

#1252 Deregistration side effects
  lib/trento/application/integration/discovery/protocol/enrich_register_application_instance.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/read_models/application_instance_read_model.ex
  lib/trento/application/read_models/database_instance_read_model.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento/application/usecases/hosts/hosts.ex
  priv/repo/migrations/20230309094053_add_deregistered_at_to_host_read_model.exs
  test/trento/application/integration/discovery/protocol/enrich_register_application_instance_test.exs
  test/trento/application/projectors/host_projector_test.exs
  test/trento/application/usecases/hosts_test.exs
Labels: enhancement, elixir

#1259 Agent version warning
  assets/js/components/Health/HealthIcon.jsx
  assets/js/components/Health/HealthIcon.stories.jsx
  assets/js/components/Health/HealthIcon.test.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostsList.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/components/Pill/Pill.jsx
  assets/js/components/Pill/Pill.stories.jsx
  assets/js/components/Pill/Pill.test.jsx
  assets/js/components/Tooltip/Tooltip.jsx
  assets/js/lib/agent/agent.test.js
  assets/js/lib/agent/index.js
  assets/package-lock.json
  assets/package.json
Labels: enhancement

#1271 Add dev.local.exs usage
  .gitignore
  config/dev.exs
Labels: chore

#1272 Sapsystem rollup
  config/config.exs
  lib/trento/application/event_handlers/roll_up_event_handler.ex
  lib/trento/application/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/domain/sap_system/commands/rollup_sap_system.ex
  lib/trento/domain/sap_system/events/sap_system_roll_up_requested.ex
  lib/trento/domain/sap_system/events/sap_system_rolled_up.ex
  lib/trento/domain/sap_system/lifespan.ex
  lib/trento/domain/sap_system/sap_system.ex
  lib/trento/infrastructure/router.ex
  test/trento/application/event_handlers/stream_roll_up_event_handler_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: enhancement, elixir

#1277 Handle properly the not found scenario in exporters_status
  lib/trento/application/integration/prometheus/adapter/prometheus_api.ex
  lib/trento_web/controllers/v1/prometheus_controller.ex
  test/trento/application/integration/prometheus/adapters/prometheus_api_test.exs
  test/trento_web/controllers/v1/prometheus_controller_test.exs
Labels: bug

#1279 Add empty state subcomponent for the table component
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/components/Table/EmptyState.jsx
  assets/js/components/Table/Table.jsx
  assets/js/components/Table/Table.test.jsx
Labels: enhancement, javascript
