Repository trento-project/web, pull requests merged in 2023-10, with the labels that each got.

#1887 Update storybook control type from string to text
  assets/js/components/ChecksSelection/ChecksSelectionHeader.stories.jsx
  assets/js/components/HostDetails/HostDetails.stories.jsx
Labels: tech debt, javascript

#1878 Handle fact value with null value
  assets/js/components/ExecutionResults/CheckResultDetail/FactValue.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/FactValue.test.jsx
  assets/js/components/ObjectTree/ObjectTree.stories.jsx
  assets/js/components/ObjectTree/ObjectTree.test.jsx
  assets/js/components/ObjectTree/ObjectTreeNode.jsx
  assets/js/components/ObjectTree/tree.js
  assets/js/lib/test-utils/factories/index.js
Labels: bug

#1891 Fix test after behaviour change
  assets/js/components/HostsList.test.jsx
Labels: chore

#1900 Send email notification on host health going critical
  guides/alerting/alerting.md
  lib/trento/application/event_handlers/alerts_event_handler.ex
  lib/trento/application/usecases/alerting/alerting.ex
  lib/trento/application/usecases/alerting/email/templates/critical.html.eex
  test/trento/application/usecases/alerting_test.exs
Labels: enhancement, user story, elixir, env

#1908 Notify user when cluster health changes
  assets/js/state/clusters.js
  assets/js/state/sagas/clusters.js
  assets/js/state/sagas/clusters.test.js
  assets/js/state/sagas/index.js
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento_web/views/v2/cluster_view.ex
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento_web/views/v2/cluster_view_test.exs
Labels: enhancement, javascript, elixir

#1883 Update outdated Agent message
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostsList.test.jsx
  assets/js/lib/agent/agent.test.js
  assets/js/lib/agent/index.js
Labels: enhancement, ux

#1913 Fix "no tuning" value by "not tuned"
  assets/js/components/HostDetails/HostDetails.stories.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
  assets/js/components/HostDetails/SaptuneSummary.test.jsx
  assets/js/components/SaptuneDetails/SaptuneDetails.stories.jsx
  assets/js/components/SaptuneDetails/SaptuneDetails.test.jsx
  assets/js/components/SaptuneDetails/SaptuneTuningState.jsx
  assets/js/components/SaptuneDetails/SaptuneTuningState.test.jsx
  assets/js/lib/test-utils/factories/hosts.js
  test/support/factory.ex
Labels: bug

#1906 Saptune services status icons
  assets/js/components/SaptuneDetails/SaptuneDetails.jsx
  assets/js/components/SaptuneDetails/SaptuneDetails.stories.jsx
  assets/js/components/SaptuneDetails/SaptuneDetails.test.jsx
  assets/js/components/SaptuneDetails/SaptuneServiceStatus.jsx
  assets/js/components/SaptuneDetails/SaptuneServiceStatus.test.jsx
Labels: enhancement, javascript, env

#1909 Improve renderSolution function if solution is empty
  assets/js/components/SaptuneDetails/SaptuneDetails.jsx
  assets/js/components/SaptuneDetails/SaptuneDetails.test.jsx
Labels: bug, enhancement

#1914 Update 27 nodes scenario to use 2.1.0 agent version
  test/e2e/cypress/fixtures/hana-database-details/selected_database.js
  test/e2e/cypress/fixtures/host-details/selected_host.js
  test/e2e/cypress/fixtures/hosts-overview/available_hosts.js
  test/e2e/cypress/fixtures/sap-system-details/selected_system.js
  test/fixtures/scenarios/aws-landscape/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json
  test/fixtures/scenarios/aws-landscape/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json
  test/fixtures/scenarios/aws-landscape/1b0e9297-97dd-55d6-9874-8efde4d84c90_host_discovery.json
  test/fixtures/scenarios/aws-landscape/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_host_discovery.json
  test/fixtures/scenarios/aws-landscape/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_host_discovery.json
  test/fixtures/scenarios/aws-landscape/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/1b0e9297-97dd-55d6-9874-8efde4d84c90_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/098fc159-3ed6-58e7-91be-38fda8a833ea_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/0fc07435-7ee2-54ca-b0de-fb27ffdc5deb_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/116d49bd-85e1-5e59-b820-83f66db8800c_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/21de186a-e38f-5804-b643-7f4ef22fecfd_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/25677e37-fd33-5005-896c-9275b1284534_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/3711ea88-9ccc-5b07-8f9d-042be449d72b_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/422686d6-b2d1-5092-93e8-a744854f5085_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/4b30a6af-4b52-5bda-bccb-f2248a12c992_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/69f4dcbb-efa2-5a16-8bc8-01df7dbb7384_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/81e9b629-c1e7-538f-bff1-47d3a6580522_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/927901fa-2c87-524e-b18c-3ef5187f504f_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a26b6d0-6e72-597c-9fe5-152a6875f214_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9cd46919-5f19-59aa-993e-cf3736c71053_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/a09d9cf3-46c1-505c-8fb8-4b0a71a9114e_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/a3297d85-5e8b-5ac5-b8a3-55eebc2b8d12_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/ddcb7992-2ffb-5c10-8b39-80685f6eaaba_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/e0c182db-32ff-55c6-a9eb-2b82dd21bc8b_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/f0c808b3-d869-5192-a944-20f66a6a8449_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json
Labels: chore, test, env

#1918 Added 3 categories for Storybook structure
  assets/js/components/AboutPage/AboutPage.stories.jsx
  assets/js/components/Accordion/Accordion.stories.jsx
  assets/js/components/Banners/WarningBanner.stories.jsx
  assets/js/components/Button/Button.stories.jsx
  assets/js/components/CheckResultsOverview/CheckResultsOverview.stories.jsx
  assets/js/components/ChecksCatalog/ProviderSelection.stories.jsx
  assets/js/components/ChecksSelection/ChecksSelection.stories.jsx
  assets/js/components/ChecksSelection/ChecksSelectionHeader.stories.jsx
  assets/js/components/CleanUpButton/CleanUpButton.stories.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.stories.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/components/DatabaseDetails/DatabaseDetails.stories.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.stories.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.stories.jsx
  assets/js/components/DottedPagination/DottedPagination.stories.jsx
  assets/js/components/Eula/Community.stories.jsx
  assets/js/components/Eula/Premium.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectedValues.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/GatheredFacts.stories.jsx
  assets/js/components/ExecutionResults/ExecutionResults.stories.jsx
  assets/js/components/Health/HealthIcon.stories.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.stories.jsx
  assets/js/components/HostDetails/HostDetails.stories.jsx
  assets/js/components/ListView/ListView.stories.jsx
  assets/js/components/NotFound/NotFound.stories.jsx
  assets/js/components/ObjectTree/ObjectTree.stories.jsx
  assets/js/components/Pill/Pill.stories.jsx
  assets/js/components/PremiumPill/PremiumPill.stories.jsx
  assets/js/components/ProviderLabel/ProviderLabel.stories.jsx
  assets/js/components/SapSystemDetails/SapSystemDetails.stories.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.stories.jsx
  assets/js/components/SaptuneDetails/SaptuneDetails.stories.jsx
  assets/js/components/Spinner.stories.jsx
  assets/js/components/Table/Table.stories.jsx
  assets/js/components/Tags/Tags.stories.jsx
  assets/js/components/Tooltip/Tooltip.stories.jsx
Labels: enhancement, chore, ux, proposal

#1922 Update rabbitmq image in docker-compose
  docker-compose.yaml
Labels: chore

#1905 Update host health state based on saptune data
  lib/trento/application/integration/discovery/discovery.ex
  lib/trento/application/integration/discovery/policies/host_policy.ex
  lib/trento/domain/host/commands/update_saptune_status.ex
  lib/trento/domain/host/events/host_saptune_health_changed.ex
  lib/trento/domain/host/host.ex
  test/support/factory.ex
  test/trento/application/integration/discovery/policies/host_policy_test.exs
  test/trento/domain/host/host_test.exs
Labels: enhancement, env

#1917 Add e2e tests for hosts health affected by saptune data
  .photofinish.toml
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/fixtures/scenarios/hosts-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_saptune_discovery_compliant.json
  test/fixtures/scenarios/hosts-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_saptune_discovery_not_compliant.json
  test/fixtures/scenarios/hosts-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_saptune_discovery_not_tuned.json
  test/fixtures/scenarios/hosts-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_saptune_discovery_uninstalled.json
  test/fixtures/scenarios/hosts-overview/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_saptune_discovery_unsupported.json
  test/fixtures/scenarios/hosts-overview/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_saptune_discovery_not_tuned.json
  test/fixtures/scenarios/hosts-overview/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_saptune_discovery_uninstalled.json
Labels: test

#1923 Saptune details view e2e test
  .photofinish.toml
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/e2e/cypress/e2e/saptune_details.cy.js
  test/e2e/cypress/fixtures/saptune-details/saptune_details_data.js
  test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_compliant.json
  test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_not_compliant.json
  test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_not_tuned.json
  test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_saptune_service_status_passing.json
  test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_uninstalled.json
  test/fixtures/scenarios/hosts-overview/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery_unsupported.json
Labels: javascript, test

#1935 Replace "SAP INSTANCES" title in Trento dashboard/home page
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
Labels: enhancement, chore

#1945 Add missing cluster type when loading checks in cluster checks selection
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
Labels: bug, chore

#1950 Normalize redux state content as snake_case
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.stories.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/lib/serialization/index.js
  assets/js/lib/test-utils/factories/index.js
  assets/js/state/healthSummary.js
  assets/js/state/sagas/index.js
Labels: tech debt, chore

#1954 Fix redirection when a query string is involved
  lib/trento_web/plugs/api_redirector.ex
  test/trento_web/plugs/api_redirector_test.exs
Labels: bug

#1953 Checks catalog stories
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.stories.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogPage.jsx
  assets/js/components/ChecksCatalog/index.js
  assets/js/trento.jsx
Labels: tech debt

#1944 Fix ip address ui in host details
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.stories.jsx
  assets/js/components/HostDetails/HostSummary.jsx
  assets/js/components/HostDetails/HostSummary.test.jsx
  assets/js/components/ListView/ListView.jsx
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/fixtures/host-details/selected_host.js
Labels: bug, enhancement, javascript, env

#1958 Checks catalog only first group expanded
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.test.jsx
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement

#1959 Handle when no checks available in the checks results overview
  assets/js/components/CheckResultsOverview/CheckResultsOverview.jsx
  assets/js/components/CheckResultsOverview/CheckResultsOverview.stories.jsx
  assets/js/components/CheckResultsOverview/CheckResultsOverview.test.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.stories.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.test.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetailPage.test.jsx
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.stories.jsx
  assets/js/components/HostDetails/HostDetailsPage.jsx
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/e2e/host_details.cy.js
Labels: enhancement, javascript
