Repository trento-project/web, pull requests merged in 2023-11, with the labels that each got.

#1975 Fix saptune domain clause
  lib/trento/domain/host/host.ex
  test/trento/domain/host/host_test.exs
Labels: bug

#1979 Update tooltip texts
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  assets/js/components/InstanceOverview/InstanceOverview.test.jsx
  assets/js/components/SapSystemLink.jsx
  assets/js/components/SapSystemLink.test.jsx
Labels: enhancement

#1980 Use databasesList slice properly to get db instances
  assets/js/components/ClustersList.test.jsx
  assets/js/state/selectors/sapSystem.js
  assets/js/state/selectors/sapSystem.test.js
  test/e2e/cypress/e2e/databases_overview.cy.js
Labels: bug

#1996 Release 2.2.0
  CHANGELOG.md
  mix.exs
  test/e2e/package.json
Labels: release

#1999 Re-release 2.2.0
  CHANGELOG.md
Labels: release

#1998 Iconify check's target type in catalog
  assets/js/components/ChecksCatalog/CheckItem.jsx
  assets/js/components/ChecksCatalog/CheckItem.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.stories.jsx
  assets/js/components/ExecutionResults/CheckResultOutline.jsx
  assets/js/components/ExecutionResults/TargetIcon.jsx
  assets/js/components/ExecutionResults/TargetResult.jsx
  assets/js/components/ExecutionResults/TargetResult.test.jsx
  assets/js/components/TargetIcon/TargetIcon.jsx
  assets/js/components/TargetIcon/TargetIcon.stories.jsx
  assets/js/components/TargetIcon/TargetIcon.test.jsx
  assets/js/components/TargetIcon/index.js
  assets/js/lib/test-utils/factories/index.js
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement, user story, ux, javascript, env

#2005 Improve Error notification box usage
  assets/js/components/ExecutionResults/ResultsContainer.jsx
  assets/js/components/NotificationBox.jsx
Labels: chore, ux

#2003 ASCS/ERS checks
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.jsx
Labels: enhancement

#2010 Use catalog API version 2
  assets/js/lib/api/checks.js
  assets/js/state/sagas/catalog.test.js
  test/e2e/cypress/e2e/checks_catalog.cy.js
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
Labels: enhancement, chore, javascript

#2011 Add default props for AscsErsClusterDetails
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
Labels: chore

#2006 Supersede events
  lib/trento/support/event.ex
  lib/trento/support/intermediate_event.ex
  test/support/structs/test_legacy_event_v1.ex
  test/support/structs/test_legacy_event_v2.ex
  test/trento/support/event_test.exs
  test/trento/support/intermediate_event_test.exs
Labels: enhancement

#2002 Tags context
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/application/read_models/database_read_model.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento/application/read_models/sap_system_read_model.ex
  lib/trento/tags.ex
  lib/trento/tags/tag.ex
  lib/trento_web/controllers/v1/tags_controller.ex
  test/support/factory.ex
  test/trento/tags_test.exs
  test/trento_web/controllers/v1/tags_controller_test.exs
Labels: enhancement, tech debt

#2020 Ensure event modules are loaded during deserialization
  lib/trento/support/jsonb_serializer.ex
Labels: bug

#2013 Generic selection component
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogPage.jsx
  assets/js/components/ChecksCatalog/ProviderSelection.stories.jsx
  assets/js/components/ProviderLabel/ProviderLabel.jsx
  assets/js/components/ProviderLabel/ProviderLabel.stories.jsx
  assets/js/components/ProviderLabel/ProviderLabel.test.jsx
  assets/js/components/Select/Select.jsx
  assets/js/components/Select/Select.stories.jsx
  assets/js/components/Select/Select.test.jsx
  assets/js/components/Select/index.js
  assets/js/lib/model/index.js
  assets/js/lib/model/model.test.js
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement, user story, ux, javascript

#2025 Deploy to demo env when receives `deploy-demo` action from `wanda`
  .github/workflows/ci.yaml
Labels: bug, ci

#2009 Extend Catalog filtering
  assets/js/components/ChecksCatalog/CheckItem.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/components/ChecksCatalog/ChecksCatalogPage.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterLink.jsx
  assets/js/components/ClustersList.jsx
  assets/js/components/DatabaseDetails/DatabaseDetails.jsx
  assets/js/components/DatabaseDetails/DatabaseDetails.stories.jsx
  assets/js/components/DatabasesOverview/DatabaseItemOverview.jsx
  assets/js/components/DatabasesOverview/DatabasesOverview.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.stories.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.test.jsx
  assets/js/components/ExecutionResults/TargetResult.jsx
  assets/js/components/InstanceOverview/InstanceOverview.jsx
  assets/js/components/InstanceOverview/InstanceOverview.test.jsx
  assets/js/components/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/components/SapSystemDetails/GenericSystemDetails.test.jsx
  assets/js/components/SapSystemDetails/SapSystemDetails.jsx
  assets/js/components/SapSystemDetails/SapSystemDetails.stories.jsx
  assets/js/components/SapSystemDetails/index.js
  assets/js/components/SapSystemsOverview/SapSystemItemOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.test.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverviewPage.jsx
  assets/js/components/Select/Select.jsx
  assets/js/components/TargetIcon/TargetIcon.jsx
  assets/js/components/TargetIcon/TargetIcon.stories.jsx
  assets/js/components/TargetIcon/TargetIcon.test.jsx
  assets/js/lib/model/clusters.js
  assets/js/lib/model/clusters.test.js
  assets/js/lib/model/index.js
  assets/js/lib/model/sapSystems.js
  assets/js/lib/model/sapSystems.test.js
  assets/js/state/selectors/sapSystem.js
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement, user story, ux, javascript, env

#2029 Run `run-photofinish-demo-env` job when receiving `demo-deploy` action
  .github/workflows/ci.yaml
Labels: bug, ci

#2030 Fix leftover Domain.SapSystem
  lib/trento/sap_systems/events/legacy/sap_system_roll_up_requested.ex
  lib/trento/sap_systems/events/legacy/sap_system_rolled_up.ex
  lib/trento/sap_systems/events/sap_system_roll_up_requested.ex
  lib/trento/sap_systems/events/sap_system_rolled_up.ex
  lib/trento/sap_systems/sap_system.ex
Labels: enhancement, chore

#2007 Revert "Remove Check-related action buttons from Host Details view (#…
  assets/js/components/HostDetails/HostDetails.jsx
  assets/js/components/HostDetails/HostDetails.test.jsx
Labels: chore

#2028 Interdependent catalog filters
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/Select/Select.jsx
  assets/js/components/Select/Select.stories.jsx
  assets/js/components/Select/Select.test.jsx
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement, user story, ux, javascript, env

#2024 Redux state directory restructure
  assets/js/components/ChecksCatalog/ChecksCatalogPage.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/components/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetailPage.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/HostDetails/HostDetailsPage.jsx
  assets/js/components/HostDetails/HostSettingsPage.jsx
  assets/js/components/Login.jsx
  assets/js/state/actions/auth.js
  assets/js/state/actions/catalog.js
  assets/js/state/actions/lastExecutions.js
  assets/js/state/actions/notifications.js
  assets/js/state/catalog.js
  assets/js/state/channels.js
  assets/js/state/lastExecutions.js
  assets/js/state/notifications.js
  assets/js/state/sagas/catalog.js
  assets/js/state/sagas/checksSelection.js
  assets/js/state/sagas/checksSelection.test.js
  assets/js/state/sagas/clusters.js
  assets/js/state/sagas/clusters.test.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/databases.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/lastExecutions.js
  assets/js/state/sagas/lastExecutions.test.js
  assets/js/state/sagas/notifications.jsx
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sagas/user.js
Labels: chore, javascript

#2027 Context extraction from infra
  lib/mix/tasks/dump_scenario.ex
  lib/mix/tasks/prune_events.ex
  lib/trento/discovery.ex
  lib/trento/discovery/discarded_discovery_event.ex
  lib/trento/discovery/discovery_event.ex
  lib/trento/discovery/payloads/cloud_discovery_payload.ex
  lib/trento/discovery/payloads/cluster/cib_discovery_payload.ex
  lib/trento/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/discovery/payloads/cluster/crmmon_discovery_payload.ex
  lib/trento/discovery/payloads/cluster/sbd_discovery_payload.ex
  lib/trento/discovery/payloads/host_discovery_payload.ex
  lib/trento/discovery/payloads/sap_system_discovery_payload.ex
  lib/trento/discovery/payloads/saptune_discovery_payload.ex
  lib/trento/discovery/payloads/subscription_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento/discovery/policies/host_policy.ex
  lib/trento/discovery/policies/sap_system_policy.ex
  lib/trento/infrastructure/telemetry/telemetry.ex
  lib/trento/settings.ex
  lib/trento/settings/settings.ex
  lib/trento_web/auth/api_key.ex
  lib/trento_web/controllers/v1/about_controller.ex
  lib/trento_web/controllers/v1/discovery_controller.ex
  lib/trento_web/controllers/v1/installation_controller.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  mix.exs
  test/support/factory.ex
  test/support/helpers/discovery_fixtures_helper.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento/discovery/policies/host_policy_test.exs
  test/trento/discovery/policies/sap_system_policy_test.exs
  test/trento/discovery_test.exs
  test/trento/infrastructure/telemetry/telemetry_test.exs
  test/trento/settings.exs
  test/trento_web/auth/api_key_test.exs
  test/trento_web/plugs/authenticate_apikey_plug_test.exs
Labels: enhancement, chore

#2036 Split saga functions context
  assets/js/state/clusters.js
  assets/js/state/hosts.js
  assets/js/state/sagas/catalog.js
  assets/js/state/sagas/checksSelection.js
  assets/js/state/sagas/clusters.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/eula.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/lastExecutions.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/settings.js
  assets/js/state/user.js
Labels: tech debt
