Repository trento-project/web, pull requests merged in 2023-12, with the labels that each got.

#2088 Provide ENSA version info to Wanda
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
Labels: enhancement, javascript

#2079 New empty state for catalog
  assets/js/common/NotificationBox/NotificationBox.jsx
  assets/js/common/NotificationBox/NotificationBox.test.jsx
  assets/js/pages/ChecksCatalog/CatalogContainer.jsx
  assets/js/pages/ChecksCatalog/CatalogContainer.test.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.stories.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalogPage.jsx
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/static/checks-not-found.svg
Labels: enhancement

#2091 Catalog empty state new illustration
  assets/js/pages/ChecksCatalog/CatalogContainer.jsx
  assets/js/pages/ChecksCatalog/CatalogContainer.test.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.jsx
  assets/static/checks-not-found.svg
Labels: enhancement

#2093 New catalog error state
  assets/js/pages/ChecksCatalog/CatalogContainer.jsx
  assets/js/pages/ChecksCatalog/CatalogContainer.test.jsx
  assets/static/connection-error-antenna.svg
Labels: enhancement

#2096 Fix Start Execution button size in cluster details
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
Labels: chore

#2098 Fix start execution button size for host details
  assets/js/pages/HostDetailsPage/HostDetails.jsx
Labels: chore

#2105 Fix classnames usage in HostDetails
  assets/js/pages/HostDetailsPage/HostDetails.jsx
Labels: chore

#2049 Charts Without Grafana
  README.md
  assets/js/common/TimeSeriesLineChart/TimeSeriesLineChart.jsx
  assets/js/common/TimeSeriesLineChart/TimeSeriesLineChart.stories.jsx
  assets/js/common/TimeSeriesLineChart/TimeSeriesLineChart.test.jsx
  assets/js/common/TimeSeriesLineChart/index.js
  assets/js/pages/HostDetailsPage/HostChart.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/package-lock.json
  assets/package.json
  config/config.exs
  config/runtime.exs
  container_fixtures/prometheus/prometheus_entrypoint.sh
  container_fixtures/prometheus/prometheus_snap.tar.xz
  docker-compose.yaml
  guides/development/environment_variables.md
  guides/development/hack_on_the_trento.md
  guides/monitoring/monitoring.md
  lib/mix/tasks/init_grafana_dashboards.ex
  lib/trento/charts.ex
  lib/trento/charts/chart_time_series.ex
  lib/trento/charts/chart_time_series_sample.ex
  lib/trento/charts/hosts/host_cpu_chart.ex
  lib/trento/charts/hosts/host_data_fetcher.ex
  lib/trento/charts/hosts/host_memory_chart.ex
  lib/trento/hosts.ex
  lib/trento/infrastructure/grafana/grafana.ex
  lib/trento/infrastructure/prometheus/adapter/prometheus_api.ex
  lib/trento/infrastructure/prometheus/chart_integration.ex
  lib/trento/infrastructure/prometheus/prometheus_samples.ex
  lib/trento/release.ex
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/v1/chart_controller.ex
  lib/trento_web/openapi/v1/schema/chart.ex
  lib/trento_web/router.ex
  lib/trento_web/templates/page/index.html.heex
  lib/trento_web/views/v1/chart_view.ex
  mix.exs
  priv/data/grafana/node_exporter.json
  prometheus-dev-config.yml
  test/trento/charts_test.exs
  test/trento/infrastructure/prometheus/adapters/prometheus_api_test.exs
  test/trento/infrastructure/prometheus/chart_integration_test.exs
  test/trento_web/controllers/v1/chart_controller_test.exs
Labels: enhancement, javascript, elixir
