Repository trento-project/web, pull requests merged in 2023-06, with the labels that each got.

#1479 UX improvements in ASCS/ERS and HANA cluster details view
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterDetails/SBDDetails.jsx
  assets/js/components/ClusterDetails/StoppedResources.jsx
Labels: enhancement, ux

#1487 Change redirect plug to use a list of available versions
  lib/trento_web/plugs/api_redirector.ex
  lib/trento_web/router.ex
  test/trento_web/plugs/api_redirector_test.exs
Labels: enhancement

#1480 Send cluster type to wanda
  lib/trento/application/integration/checks/checks.ex
  lib/trento/application/integration/checks/cluster_execution_env.ex
  lib/trento/application/usecases/clusters/clusters.ex
  test/trento/application/integration/checks/checks_test.exs
  test/trento/application/usecases/clusters_test.exs
Labels: enhancement

#1488 Enable openapi schema versioning
  .github/workflows/ci.yaml
  config/dev.exs
  lib/trento_web/controllers/health_controller.ex
  lib/trento_web/controllers/v1/about_controller.ex
  lib/trento_web/controllers/v1/cluster_controller.ex
  lib/trento_web/controllers/v1/discovery_controller.ex
  lib/trento_web/controllers/v1/health_overview_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/controllers/v1/prometheus_controller.ex
  lib/trento_web/controllers/v1/sap_system_controller.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/controllers/v1/tags_controller.ex
  lib/trento_web/openapi/api_spec.ex
  lib/trento_web/openapi/v1/api_spec.ex
  lib/trento_web/openapi/v1/schema/bad_request.ex
  lib/trento_web/openapi/v1/schema/checks.ex
  lib/trento_web/openapi/v1/schema/checks_catalog.ex
  lib/trento_web/openapi/v1/schema/cluster.ex
  lib/trento_web/openapi/v1/schema/database.ex
  lib/trento_web/openapi/v1/schema/discovery_event.ex
  lib/trento_web/openapi/v1/schema/health.ex
  lib/trento_web/openapi/v1/schema/host.ex
  lib/trento_web/openapi/v1/schema/http_std.ex
  lib/trento_web/openapi/v1/schema/not_found.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/openapi/v1/schema/prometheus.ex
  lib/trento_web/openapi/v1/schema/provider.ex
  lib/trento_web/openapi/v1/schema/ready.ex
  lib/trento_web/openapi/v1/schema/resource_health.ex
  lib/trento_web/openapi/v1/schema/sap_system.ex
  lib/trento_web/openapi/v1/schema/sles_subscription.ex
  lib/trento_web/openapi/v1/schema/tag.ex
  lib/trento_web/router.ex
  test/trento_web/controllers/health_controller_test.exs
  test/trento_web/controllers/session_controller_test.exs
  test/trento_web/controllers/v1/cluster_controller_test.exs
  test/trento_web/controllers/v1/health_overview_controller_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
  test/trento_web/controllers/v1/installation_controller_test.exs
  test/trento_web/controllers/v1/prometheus_controller_test.exs
  test/trento_web/controllers/v1/sap_system_controller_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
  test/trento_web/openapi/api_spec_test.exs
Labels: enhancement

#1450 Add endpoint to deregister a host
  config/config.exs
  config/test.exs
  lib/trento/application/integration/discovery/protocol/enrich_request_host_deregistration.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento/application/usecases/hosts/heartbeat.ex
  lib/trento/application/usecases/hosts/hosts.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/openapi/v1/schema/host.ex
  lib/trento_web/openapi/v1/schema/unprocessable_entity.ex
  lib/trento_web/router.ex
  lib/trento_web/templates/page/index.html.heex
  test/support/factory.ex
  test/trento/application/integration/discovery/protocol/enrich_request_host_deregistration_test.exs
  test/trento/application/usecases/hosts_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement, elixir

#1486 Handle evaluation errors
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.test.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.test.jsx
  assets/js/components/ExecutionResults/checksUtils.js
  assets/js/components/ExecutionResults/checksUtils.test.js
  assets/js/lib/test-utils/factories/executions.js
Labels: bug

#1496 Identify sap systems ensa version
  lib/trento/application/integration/discovery/policies/sap_system_policy.ex
  lib/trento/domain/enums/ensa_version.ex
  lib/trento/domain/sap_system/commands/register_application_instance.ex
  test/support/factory.ex
  test/trento/application/integration/discovery/policies/sap_system_policy_test.exs
Labels: enhancement

#1504 DatabaseDeregistered side effects
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/read_models/database_read_model.ex
  lib/trento/application/usecases/sap_systems/sap_systems.ex
  lib/trento_web/views/v1/sap_system_view.ex
  priv/repo/migrations/20230608105745_add_deregistered_at_to_database_read_model.exs
  test/trento/application/projectors/database_projector_test.exs
  test/trento/application/usecases/sap_systems_test.exs
Labels: elixir

#1505 Make `HostReadModel.last_heartbeat_timestamp` a virtual field
  lib/trento/application/integration/discovery/protocol/enrich_request_host_deregistration.ex
  lib/trento/application/read_models/host_read_model.ex
  lib/trento/application/usecases/hosts/heartbeat.ex
  lib/trento/application/usecases/hosts/hosts.ex
  lib/trento_web/openapi/v1/schema/host.ex
  test/trento/application/usecases/hosts_test.exs
Labels: enhancement, elixir

#1510 Add text to loading state cluster details
  assets/js/components/ClusterDetails/ChecksResultOverview.jsx
  assets/js/components/ClusterDetails/ChecksResultOverview.test.jsx
  assets/js/components/Spinner.jsx
  assets/js/components/Spinner.stories.jsx
  assets/js/components/Spinner.test.jsx
Labels: documentation, enhancement, javascript

#1506 Add resourceType when querying for checks in cluster checks selection
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
Labels: enhancement, javascript

#1513 Reject commands when aggregate deregistered
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/host/host.ex
  lib/trento/domain/sap_system/sap_system.ex
  test/support/factory.ex
  test/trento/domain/cluster/cluster_test.exs
  test/trento/domain/host/host_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: elixir

#1514 Rename resource_type to target_type in catalog interaction
  assets/js/components/ChecksCatalog/ChecksCatalog.jsx
  assets/js/components/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/components/ClusterDetails/ChecksSelection.jsx
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: chore

#1512 Ensa version domain
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento/application/read_models/sap_system_read_model.ex
  lib/trento/domain/sap_system/application.ex
  lib/trento/domain/sap_system/events/sap_system_registered.ex
  lib/trento/domain/sap_system/events/sap_system_updated.ex
  lib/trento/domain/sap_system/sap_system.ex
  lib/trento_web/openapi/v1/schema/sap_system.ex
  priv/repo/migrations/20230613101433_add_ensa_version_to_sap_system_read_model.exs
  priv/repo/migrations/20230613102033_set_ensa_version_initial_value_to_sap_system_read_model.exs
  test/support/factory.ex
  test/trento/application/projectors/sap_system_projector_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: enhancement

#1520 Create AscsErsClusterRole enum
  lib/trento/application/integration/discovery/policies/cluster_policy.ex
  lib/trento/domain/enums/ascs_ers_cluster_role.ex
  lib/trento/domain/value_objects/ascs_ers_cluster_node.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
Labels: chore

#1517 Host restoration
  lib/trento/application/projectors/host_projector.ex
  lib/trento/domain/host/events/host_restored.ex
  lib/trento/domain/host/host.ex
  test/trento/application/projectors/host_projector_test.exs
  test/trento/domain/host/host_test.exs
Labels: enhancement, elixir

#1516 Broadcast sap system updated
  assets/js/lib/test-utils/factories/sapSystems.js
  assets/js/state/channels.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento_web/views/v1/sap_system_view.ex
  test/trento/application/projectors/sap_system_projector_test.exs
Labels: enhancement

#1523 Cluster restoration
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/cluster/events/cluster_restored.ex
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento/domain/cluster/cluster_test.exs
Labels: enhancement, elixir

#1536 Avoid duplicated expectation names from catalog factories
  assets/js/lib/test-utils/factories/index.js
Labels: chore

#1531 Move databases/sapsystems sagas functions to separate files following adr 0009
  assets/js/state/databases.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sapSystems.js
Labels: tech debt, javascript

#1524 Add Host Check Selection Domain logic
  lib/trento/domain/host/commands/select_host_checks.ex
  lib/trento/domain/host/events/host_checks_selected.ex
  lib/trento/domain/host/host.ex
  lib/trento/infrastructure/router.ex
  test/trento/domain/host/host_test.exs
Labels: enhancement, user story, elixir

#1530 Update health summary endpoint
  lib/trento/application/usecases/sap_systems/health_summary_service.ex
  lib/trento_web/openapi/v1/schema/sap_system.ex
  lib/trento_web/views/v1/health_overview_view.ex
  test/trento/application/usecases/health_summary_service_test.exs
  test/trento_web/views/v1/health_overview_view_test.exs
Labels: enhancement

#1522 Frontend instance removal on broadcast
  assets/js/lib/test-utils/factories/databases.js
  assets/js/lib/test-utils/factories/sapSystems.js
  assets/js/state/channels.js
  assets/js/state/databases.js
  assets/js/state/databases.test.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/databases.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento_web/views/v1/sap_system_view.ex
  test/trento/application/projectors/database_projector_test.exs
  test/trento/application/projectors/sap_system_projector_test.exs
Labels: enhancement, javascript

#1543 Sap system link cluster details
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/components/SapSystemLink.jsx
Labels: enhancement

#1529 Add HomeHealthSummary storybook
  assets/js/components/HealthSummary/HomeHealthSummary.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.stories.jsx
  assets/js/components/HealthSummary/HomeHealthSummary.test.jsx
  assets/js/components/HealthSummary/HomeHealthSummaryPage.jsx
  assets/js/components/HealthSummary/index.js
  assets/js/components/Home/Home.jsx
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/lib/test-utils/factories/executions.js
  assets/js/lib/test-utils/factories/index.js
Labels: chore

#1549 Enforce expectation names uniqueness in CheckResultOutline test
  assets/js/components/ExecutionResults/CheckResultOutline.test.jsx
Labels: chore, javascript, test

#1553 Enforce fact and value name uniqueness
  assets/js/lib/test-utils/factories/executions.js
Labels: chore, javascript, test

#1550 Fix sap system domain apply ordering issues
  lib/trento/domain/sap_system/application.ex
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: bug

#1544 Add select host checks endpoint
  lib/trento/application/usecases/hosts/hosts.ex
  lib/trento_web/controllers/v1/cluster_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/router.ex
  test/trento/application/usecases/hosts_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement, user story, elixir

#1559 Add ensa version sap system details
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/DatabaseDetails/DatabaseDetails.stories.jsx
  assets/js/components/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/components/SapSystemDetails/GenericSystemDetails.test.jsx
  assets/js/components/SapSystemDetails/SapSystemDetails.stories.jsx
  assets/js/components/SapSystemDetails/index.js
  assets/js/lib/test-utils/factories/databases.js
  assets/js/lib/test-utils/factories/sapSystems.js
Labels: enhancement

#1537 Add Deregistration modal
  assets/js/components/Button/Button.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.stories.jsx
  assets/js/components/DeregistrationModal/DeregistrationModal.test.jsx
  assets/js/components/DeregistrationModal/index.js
Labels: enhancement, javascript

#1551 Allow rollup on deregistered aggregates
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/host/host.ex
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/cluster/cluster_test.exs
  test/trento/domain/host/host_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: bug, elixir

#1563 Complete tests on command acceptance/rejection
  test/trento/domain/cluster/cluster_test.exs
  test/trento/domain/host/host_test.exs
Labels: chore

#1542 Add projector for host checks selection
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/application/read_models/host_read_model.ex
  priv/repo/migrations/20230616114036_add_selected_checks_to_hosts.exs
  test/trento/application/projectors/host_projector_test.exs
Labels: enhancement, elixir

#1568 Add missing target_type query param to catalog when loading execution results page
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
Labels: bug, chore

#1561 Add ensa version to sap systems overview entries
  assets/js/components/SapSystemsOverview/SapSystemsOverview.jsx
  assets/js/components/SapSystemsOverview/SapSystemsOverview.test.jsx
Labels: enhancement

#1545 Sap system restoration
  lib/trento/application/projectors/database_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento/domain/sap_system/events/database_restored.ex
  lib/trento/domain/sap_system/events/sap_system_restored.ex
  lib/trento/domain/sap_system/sap_system.ex
  test/support/factory.ex
  test/trento/application/projectors/database_projector_test.exs
  test/trento/application/projectors/sap_system_projector_test.exs
  test/trento/domain/sap_system/sap_system_test.exs
Labels: enhancement, elixir
