Repository trento-project/web, pull requests merged in 2023-05, with the labels that each got.

#1358 Application instances registration changes
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: elixir

#1356 Add SAP System de/registration logic to Process Manager
  lib/trento/application/process_managers/deregistration_process_manager.ex
  test/support/factory.ex
  test/trento/application/process_managers/deregistration_process_manager_test.exs
Labels: enhancement, elixir

#1372 Add database instance deregistration logic
  lib/trento/domain/sap_system/sap_system.ex
  lib/trento/infrastructure/router.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: enhancement, elixir

#1387 Add SAP System deregistration side effects
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento/application/read_models/sap_system_read_model.ex
  lib/trento/application/usecases/sap_systems/health_summary_service.ex
  lib/trento/application/usecases/sap_systems/sap_systems.ex
  lib/trento_web/views/v1/sap_system_view.ex
  priv/repo/migrations/20230505124514_add_deregistered_at_to_sap_system_read_model.exs
  test/support/factory.ex
  test/trento/application/projectors/sap_system_projector_test.exs
  test/trento/application/usecases/health_summary_service_test.exs
  test/trento/application/usecases/sap_systems_test.exs
Labels: enhancement, elixir

#1375 Fix wrong filtered catalog being used in execution results page
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
Labels: bug

#1400 Discover ASCS/ERS cluster SIDs
  lib/trento/application/integration/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/application/integration/discovery/policies/cluster_policy.ex
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/read_models/cluster_read_model.ex
  lib/trento/domain/cluster/cluster.ex
  lib/trento/domain/cluster/commands/register_cluster_host.ex
  lib/trento/domain/cluster/events/cluster_details_updated.ex
  lib/trento/domain/cluster/events/cluster_registered.ex
  lib/trento_web/openapi/schema/cluster.ex
  priv/repo/migrations/20230509114833_add_additional_sids_to_cluster_read_model.exs
  test/support/factory.ex
  test/trento/application/integration/discovery/policies/cluster_policy_test.exs
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento/domain/cluster/cluster_test.exs
Labels: enhancement

#1405 Handle `:database_not_registered` errors
  lib/trento/application/integration/discovery/protocol/enrich_register_application_instance.ex
  lib/trento_web/controllers/fallback_controller.ex
  test/trento/application/integration/discovery/protocol/enrich_register_application_instance_test.exs
Labels: bug, elixir

#1410 Allow custom css in table rows
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/Table/CollapsibleTableRow.jsx
  assets/js/components/Table/Table.jsx
  assets/js/components/Table/Table.test.jsx
Labels: enhancement, chore

#1416 Improve scalar values support in FactValue
  assets/js/components/ExecutionResults/CheckResultDetail/FactValue.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/FactValue.test.jsx
Labels: bug

#1415 Do not render Values section when no values are available
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/CheckResultDetail.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectedValues.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectedValues.test.jsx
  assets/js/lib/test-utils/factories/executions.js
Labels: enhancement, chore, ux, javascript

#1403 Display ASCS/ERS clusters SID in clusters view
  assets/js/components/ClustersList.jsx
  assets/js/components/ClustersList.test.jsx
  assets/js/lib/test-utils/factories/clusters.js
  lib/trento/application/usecases/clusters/clusters.ex
  test/e2e/cypress/fixtures/clusters-overview/available_clusters.js
Labels: enhancement

#1414 Fix 404 page when wrong filtered catalog is being used in execution results page
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/components/ExecutionResults/checksUtils.js
Labels: bug, enhancement, javascript

#1423 Update copyright message in UI bottom left to include year 2023
  LICENSE
  README.md
  assets/js/components/Layout/Layout.jsx
Labels: documentation

#1426 Use absolute urls for documentation assets
  guides/authentication/spa_flow.md
  guides/monitoring/monitoring.md
Labels: documentation, chore

#1429 Revert HeartbeatSucceeded to old name
  lib/trento/application/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/application/projectors/host_projector.ex
  lib/trento/domain/host/events/heartbeat_succeded.ex
  lib/trento/domain/host/host.ex
  test/trento/application/projectors/host_projector_test.exs
  test/trento/domain/host/host_test.exs
Labels: bug

#1428 Refactor cluster details
  assets/js/components/ClusterDetails/ChecksSelection.test.jsx
  assets/js/components/ClusterDetails/ClusterDetails.jsx
  assets/js/components/ClusterDetails/ClusterDetails.stories.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/components/ClusterDetails/SBDDetails.jsx
  assets/js/components/ClusterDetails/StoppedResources.jsx
  assets/js/components/ClusterDetails/index.js
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/lib/test-utils/factories/hosts.js
  assets/js/trento.jsx
Labels: enhancement

#1424 Deregistration UI websocket events
  assets/js/state/channels.js
  assets/js/state/clusters.js
  assets/js/state/clusters.test.js
  assets/js/state/hosts.js
  assets/js/state/hosts.test.js
  assets/js/state/sagas/clusters.js
  assets/js/state/sagas/clusters.test.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
  lib/trento/application/projectors/cluster_projector.ex
  lib/trento/application/projectors/sap_system_projector.ex
  lib/trento_web/views/v1/sap_system_view.ex
  test/trento/application/projectors/cluster_projector_test.exs
  test/trento/application/projectors/sap_system_projector_test.exs
Labels: enhancement, javascript, elixir

#1443 Dotted pagination
  assets/js/components/DottedPagination/Arrow.jsx
  assets/js/components/DottedPagination/DottedPagination.jsx
  assets/js/components/DottedPagination/DottedPagination.stories.jsx
  assets/js/components/DottedPagination/DottedPagitation.test.jsx
  assets/js/components/DottedPagination/index.js
Labels: enhancement

#1457 Fix navigation to a running execution detail
  assets/js/state/selectors/lastExecutions.js
  assets/js/state/selectors/lastExecutions.test.js
Labels: bug

#1456 Display cluster details by type
  assets/js/components/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.test.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/components/ClusterLink.jsx
  assets/js/components/ClusterLink.test.jsx
  assets/js/lib/model/index.js
  assets/js/lib/test-utils/factories/clusters.js
Labels: enhancement

#1451 Display check failure message
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.test.jsx
  assets/js/lib/test-utils/factories/executions.js
Labels: enhancement, user story, ux, javascript

#1444 Rename sections in Expectations Details view
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectationsResults.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectedValues.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/ExpectedValues.stories.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/GatheredFacts.jsx
  assets/js/components/ExecutionResults/CheckResultDetail/GatheredFacts.stories.jsx
Labels: chore, javascript

#1442 Add additional ascs/ers cluster details discovery
  lib/trento/application/integration/discovery/policies/cluster_policy.ex
  lib/trento/domain/value_objects/ascs_ers_cluster_node.ex
  lib/trento/domain/value_objects/ascs_ers_cluster_sap_system.ex
  test/trento/application/integration/discovery/policies/cluster_policy_test.exs
Labels: enhancement

#1445 Persist selected filters in checks results inside Redux
  assets/js/components/ExecutionResults/ChecksResultFilters.jsx
  assets/js/components/ExecutionResults/ExecutionHeader.jsx
  assets/js/components/ExecutionResults/ExecutionResults.jsx
  assets/js/components/ExecutionResults/ExecutionResults.test.jsx
  assets/js/components/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/state/checksResultsFilters.js
  assets/js/state/checksResultsFilters.test.js
  assets/js/state/index.js
  assets/js/state/selectors/checksResultsFilters.js
  assets/js/state/selectors/checksResultsFilters.test.js
Labels: enhancement

#1467 Self host Lato font
  assets/.storybook/main.js
  assets/css/app.css
  lib/trento_web/templates/layout/root.html.heex
  priv/static/fonts/lato-400-ext.woff2
  priv/static/fonts/lato-400.woff2
  priv/static/fonts/lato-700-ext.woff2
  priv/static/fonts/lato-700.woff2
Labels: chore

#1466 ASCS/ERS cluster details component
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.stories.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/components/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/components/DottedPagination/Arrow.jsx
  assets/js/components/DottedPagination/DottedPagination.jsx
  assets/js/components/DottedPagination/DottedPagitation.test.jsx
  assets/js/lib/test-utils/factories/clusters.js
  assets/static/checks-coming-soon.svg
Labels: enhancement

#1473 Deregistration process manager retry the rollup errors from aggregates
  lib/trento/application/process_managers/deregistration_process_manager.ex
Labels: elixir

#1469 Improve tooltip styling
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/components/Tooltip/Tooltip.jsx
Labels: chore

#1461 Basic deregistration leftovers
  lib/trento/domain/sap_system/database.ex
  lib/trento/domain/sap_system/sap_system.ex
  test/trento/domain/sap_system/sap_system_test.exs
Labels: elixir

#1472 Add cluster nodes details to ASCS/ERS cluster details view
  assets/js/components/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.stories.jsx
  assets/js/components/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/components/ClusterDetails/HanaClusterDetails.jsx
  assets/js/lib/test-utils/factories/clusters.js
Labels: enhancement
