Repository trento-project/web, pull requests merged in 2024-06, with the labels that each got.

#2657 Totp enrollment frontend
  assets/js/lib/api/users.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/Profile/ProfileForm.jsx
  assets/js/pages/Profile/ProfileForm.stories.jsx
  assets/js/pages/Profile/ProfileForm.test.jsx
  assets/js/pages/Profile/ProfilePage.jsx
  assets/js/pages/Profile/ProfilePage.test.jsx
  assets/js/pages/Profile/TotpEnrollmentBox.jsx
  assets/js/pages/Profile/TotpEnrollmentBox.stories.jsx
  assets/js/pages/Profile/TotpEnrollmentBox.test.jsx
  assets/package-lock.json
  assets/package.json
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/views/v1/profile_view.ex
Labels: enhancement, javascript

#2658 Allow admin disable totp
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.jsx
  assets/js/common/Select/Select.jsx
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/ChecksCatalog/ChecksCatalog.jsx
  assets/js/pages/Users/EditUserPage.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
  lib/trento/users.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/views/v1/users_view.ex
  test/trento/users_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
Labels: enhancement, user story

#2670 Policy support functions
  lib/trento/support/policy_helper.ex
  lib/trento/users/policy.ex
  test/trento/support/policy_helper_test.exs
Labels: enhancement, elixir

#2667 TOTP authentication e2e tests
  test/e2e/cypress/e2e/users.cy.js
  test/e2e/package-lock.json
  test/e2e/package.json
Labels: enhancement, test

#2668 Upgradable packages view
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.jsx
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.test.jsx
  assets/js/common/UpgradablePackagesList/index.js
  assets/js/lib/api/softwareUpdates.js
  assets/js/lib/test-utils/factories/relevantPatches.js
  assets/js/lib/test-utils/factories/upgradablePackage.js
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.test.jsx
  assets/js/pages/UpgradablePackagesPage/index.js
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/selectors/softwareUpdates.test.js
  assets/js/state/softwareUpdates.js
  assets/js/state/softwareUpdates.test.js
  assets/js/trento.jsx
Labels: enhancement

#2669 Add sorting to `Table` component
  assets/js/common/Table/SortingIcon.jsx
  assets/js/common/Table/Table.jsx
  assets/js/common/Table/Table.stories.jsx
  assets/js/common/Table/Table.test.jsx
  assets/js/common/Table/sorting.js
Labels: enhancement, javascript

#2677 Fix SAP systems policy receiving an empty list of instances
  lib/trento/discovery/payloads/sap_system_discovery_payload.ex
  test/fixtures/discovery/sap_system_discovery_empty_application_instances.json
  test/trento/discovery/policies/sap_system_policy_test.exs
Labels: env

#2675 Fix SMTP usage in runtime configuration
  config/runtime.exs
  lib/trento/infrastructure/alerting/alerting.ex
Labels: bug, elixir, env

#2632 Add HTTPS using cert-manager for demo env
  .github/workflows/ci.yaml
Labels: ci

#2681 Default empty string for smtp server
  config/runtime.exs
Labels: bug

#2679 Add sorting in `Upgradable Packages` & `Available Patches` lists
  assets/js/common/PatchList/PatchList.jsx
  assets/js/common/Table/index.js
  assets/js/common/Table/sorting.js
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.stories.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.test.jsx
  assets/js/trento.jsx
Labels: enhancement, javascript

#2682 Rename `TRENTO_DOMAIN` to `TRENTO_WEB_ORIGIN`
  .github/workflows/ci.yaml
  config/runtime.exs
  guides/development/environment_variables.md
Labels: chore

#2672 Disabled guard
  assets/js/common/DisabledGuard/DisabledGuard.jsx
  assets/js/common/DisabledGuard/DisabledGuard.stories.jsx
  assets/js/common/DisabledGuard/DisabledGuard.test.jsx
  assets/js/common/DisabledGuard/index.js
  assets/js/common/ForbiddenGuard/ForbiddeGuard.test.jsx
  assets/js/common/ForbiddenGuard/ForbiddenGuard.jsx
  assets/js/common/ForbiddenGuard/index.js
  assets/js/pages/Layout/Layout.jsx
  assets/js/trento.jsx
Labels: enhancement

#2638 Make discovery payload nullable in schema
  lib/trento_web/openapi/v1/schema/discovery_event.ex
  test/trento_web/controllers/v1/discovery_controller_test.exs
Labels: bug, env

#2685 Add header to upgradable packages view
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.jsx
Labels: chore

#2684 Add search to table component
  assets/js/common/Table/Table.stories.jsx
  assets/js/lib/filter/index.js
  assets/js/lib/filter/index.test.js
  assets/js/lib/test-utils/index.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.test.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.stories.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.test.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.test.jsx
Labels: enhancement, javascript

#2688 Add ability to download CSV file when `Download CSV` button is clicked
  .github/workflows/ci.yaml
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.test.jsx
  assets/package-lock.json
  assets/package.json
Labels: enhancement, javascript

#2637 Add SUMA credentials e2e
  assets/js/common/SuseManagerClearSettingsDialog/SuseManagerClearSettingsModal.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.test.jsx
  assets/js/common/SuseManagerSettingsDialog/SuseManagerSettingsModal.jsx
  test/e2e/cypress/e2e/settings.cy.js
  test/e2e/cypress/fixtures/suma_credentials/certificates.js
  test/e2e/cypress/support/commands.js
  test/e2e/package-lock.json
Labels: tech debt, test

#2704 Refactor settings page section
  assets/js/common/SettingsLoader/SettingsLoader.jsx
  assets/js/common/SettingsLoader/SettingsLoader.stories.jsx
  assets/js/common/SettingsLoader/SettingsLoader.test.jsx
  assets/js/common/SettingsLoader/index.js
  assets/js/common/SuseManagerConfig/SuseManagerSettingsContainer.jsx
  assets/js/common/SuseManagerConfig/index.js
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/pages/SettingsPage/SettingsPage.test.jsx
Labels: chore

#2708 Improve tag validation msg show up
  assets/js/common/Tags/Tags.jsx
  assets/js/common/Tags/Tags.test.jsx
Labels: chore

#2663 Add a docs section to pr template
  .github/pull_request_template.md
Labels: documentation, enhancement

#2690 Activity log retention time
  lib/trento/activity_log.ex
  lib/trento/activity_logging/retention_period_unit.ex
  lib/trento/activity_logging/retention_time.ex
  lib/trento/activity_logging/settings.ex
  lib/trento/release.ex
  priv/repo/migrations/20240612081138_add_activity_log_settings.exs
  priv/repo/seeds.exs
  test/support/factory.ex
  test/trento/activity_log_test.exs
  test/trento/release_test.exs
Labels: enhancement

#2712 Use proper command to login
  test/e2e/cypress/e2e/settings.cy.js
  test/e2e/cypress/support/commands.js
Labels: test

#2713 Set python3 as ansible interpreter
  .github/workflows/pr_env.yaml
Labels: bug, env

#2714 Apply fix in the PR cleanup as well
  .github/workflows/pr_env_close.yaml
Labels: chore

#2692 Watch channel events
  assets/jest.config.js
  assets/js/state/channels.js
  assets/js/state/clusters.js
  assets/js/state/databases.js
  assets/js/state/hosts.js
  assets/js/state/sagas/channels.js
  assets/js/state/sagas/channels.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sapSystems.js
  assets/js/state/user.js
  assets/mocks/phoenix.js
Labels: tech debt

#2702 Activity log retention time endpoint
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/settings_view.ex
  test/trento_web/controllers/v1/settings_controller_test.exs
Labels: enhancement, elixir

#2709 Singularize Activity Log retention period unit
  lib/trento/activity_logging/retention_period_unit.ex
  lib/trento/activity_logging/retention_time.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  test/trento/activity_log_test.exs
  test/trento/release_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
Labels: chore

#2717 Add migration and schema for ActivityLog
  lib/trento/activity_logging/activity_log.ex
  priv/repo/migrations/20240626103903_create_activity_logs.exs
Labels: enhancement, user story, elixir

#2719 Add migration to restart the abilities sequence from 3
  priv/repo/migrations/20240626134815_restart_abilities_sequence.exs
Labels: enhancement, elixir

#2718 Add missing resource type assigns for tagging/untagging
  lib/trento_web/router.ex
Labels: chore

#2721 Check selection abilities
  assets/js/common/DisabledGuard/DisabledGuard.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionHeader.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionHeader.stories.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionHeader.test.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.test.jsx
  lib/trento/clusters/policy.ex
  lib/trento/hosts/policy.ex
  lib/trento_web/controllers/v1/cluster_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  priv/repo/migrations/20240626142750_add_check_selection_abilities.exs
  test/support/helpers/abilities_test_helper.ex
  test/trento/clusters/policy_test.exs
  test/trento/hosts/policy_test.exs
  test/trento_web/controllers/v1/cluster_controller_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
Labels: enhancement, env
