Repository trento-project/web, pull requests merged in 2024-03, with the labels that each got.

#2378 Add the ability to get relevant patches given a SUMA system ID
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/discovery/gen.ex
  test/trento/infrastructure/software_updates/suma_test.exs
Labels: enhancement, elixir

#2371 JWT Api Key
  config/config.exs
  lib/trento/release.ex
  lib/trento/settings.ex
  lib/trento/settings/api_key_settings.ex
  lib/trento/settings/installation_settings.ex
  lib/trento/settings/settings.ex
  lib/trento/support/ecto/sti.ex
  lib/trento_web/auth/access_token.ex
  lib/trento_web/auth/api_key.ex
  lib/trento_web/auth/refresh_token.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/session_controller.ex
  lib/trento_web/controllers/v1/installation_controller.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/plugs/app_jwt_auth_plug.ex
  lib/trento_web/plugs/authenticate_apikey_plug.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/settings_view.ex
  priv/repo/migrations/20240227102315_add_api_key_settings_to_settings_schema.exs
  priv/repo/seeds.exs
  test/support/factory.ex
  test/trento/settings.exs
  test/trento/settings_test.exs
  test/trento_web/auth/access_token_test.exs
  test/trento_web/auth/api_key_test.exs
  test/trento_web/auth/refresh_token_test.exs
  test/trento_web/controllers/session_controller_test.exs
  test/trento_web/controllers/v1/installation_controller_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
  test/trento_web/plugs/app_jwt_auth_plug_test.exs
  test/trento_web/plugs/authenticate_apikey_plug_test.exs
Labels: enhancement, elixir

#2366 Add `managed` field in Cluster resources
  assets/js/lib/test-utils/data/clusters.js
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/AttributesDetails.jsx
  assets/js/pages/ClusterDetails/AttributesDetails.test.jsx
  assets/js/pages/ClusterDetails/ClusterNodeName.jsx
  assets/js/pages/ClusterDetails/ClusterNodeName.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.jsx
  lib/trento/clusters/value_objects/cluster_resource.ex
  lib/trento/discovery/payloads/cluster/crmmon_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  lib/trento_web/views/v1/cluster_view.ex
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/views/v1/cluster_view_test.exs
Labels: enhancement, javascript, elixir

#2384 Add Api key expiration checking routine
  config/config.exs
  lib/trento/infrastructure/alerting/alerting.ex
  lib/trento/infrastructure/alerting/emails/email_alert.ex
  lib/trento/infrastructure/alerting/emails/templates/api_key_expiration.html.eex
  test/trento/infrastructure/alerting/alerting_test.exs
Labels: enhancement, elixir

#2382 Handle failing authentication
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  test/trento/infrastructure/software_updates/suma_test.exs
Labels: enhancement, elixir

#2386 Add a clear operation to suma service
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento/infrastructure/software_updates/suma.ex
  test/trento/infrastructure/software_updates/suma_test.exs
Labels: enhancement, user story, elixir

#2389 Add wrap prop to tooltip
  assets/js/common/Tooltip/Tooltip.jsx
  assets/js/common/Tooltip/Tooltip.stories.jsx
  assets/js/common/Tooltip/Tooltip.test.jsx
Labels: enhancement

#2391 Add ability to provide a CA cert when making requests to SUMA
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  test/trento/infrastructure/software_updates/suma_test.exs
Labels: enhancement, elixir

#2395 Don't return error when deleting non-existent CA cert file
  lib/trento/infrastructure/software_updates/suma.ex
Labels: bug, elixir

#2388 Api key expiration frontend notifications
  assets/js/common/DismissableToast/DismissableToast.jsx
  assets/js/common/DismissableToast/DismissableToast.test.jsx
  assets/js/common/DismissableToast/index.js
  assets/js/lib/test-utils/factories/settings.js
  assets/js/state/notifications.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/notifications.jsx
  assets/js/state/sagas/settings.jsx
  assets/js/state/sagas/settings.test.jsx
  test/e2e/cypress/e2e/settings.cy.js
  test/e2e/cypress/support/commands.js
  test/e2e/package-lock.json
  test/e2e/package.json
Labels: enhancement, javascript

#2387 Add empty state to sbd details
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/SBDDetails.jsx
  assets/js/pages/ClusterDetails/SBDDetails.test.jsx
Labels: enhancement, javascript

#2396 Use derived state `use_ca_cert` in SUMA GenServer
  lib/trento/infrastructure/software_updates/state.ex
  lib/trento/infrastructure/software_updates/suma.ex
  test/trento/infrastructure/software_updates/suma_test.exs
Labels: elixir

#2397 Remove duplicated redux state `database_instances` field from the SAP system reducer
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/databases.test.js
  assets/js/state/sagas/sapSystems.js
  assets/js/state/sagas/sapSystems.test.js
  assets/js/state/sapSystems.js
  assets/js/state/sapSystems.test.js
  assets/js/state/selectors/sapSystem.js
Labels: removal

#2408 Remove warning banner for HANA Scale Up performance optimized clusters on VMware
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/pages/ExecutionResults/ExecutionHeader.jsx
  assets/js/pages/ExecutionResults/ExecutionResults.test.jsx
Labels: chore, removal

#2394 Clear suma discoveries
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/software_updates.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/discovery/gen.ex
  test/support/commanded/commanded_case.ex
  test/support/software_updates/discovery_case.ex
  test/trento/software_updates/discovery_test.exs
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
Labels: enhancement, user story, elixir

#2409 Refactor Banner component
  assets/js/common/Banners/Banner.jsx
  assets/js/common/Banners/Banner.stories.jsx
  assets/js/common/Banners/Banner.test.jsx
  assets/js/common/Banners/WarningBanner.jsx
  assets/js/common/Banners/WarningBanner.stories.jsx
  assets/js/common/Banners/WarningBanner.test.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ExecutionResults/CheckResultDetail/CheckDetailHeader.jsx
  assets/js/pages/ExecutionResults/ExecutionHeader.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
Labels: enhancement, tech debt, ux, javascript

#2420 Add notifications playground
  assets/js/common/DismissableToast/DismissableToast.jsx
  assets/js/common/DismissableToast/NotificationsPlayground.stories.jsx
Labels: javascript

#2429 Set docker as install method in `env` CI job
  .github/workflows/pr_env.yaml
  .github/workflows/pr_env_close.yaml
Labels: chore, ci, env

#2428 Update photofinish version to 1.3.0 in CI
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .photofinish.toml
  test/fixtures/scenarios/sap-systems-overview/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_sap_system_discovery_GRAY.json
Labels: chore, ci, env

#2415 Endpoint available software updates
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  lib/trento/software_updates.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/discovery/gen.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/suse_manager_controller.ex
  lib/trento_web/openapi/v1/schema/available_software_updates.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/suse_manager_view.ex
  test/support/factory.ex
  test/trento/infrastructure/software_updates/suma_test.exs
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
  test/trento_web/views/v1/suse_manager_view_test.exs
Labels: enhancement

#2416 Add Redux Sagas for getting SUSE Manager software updates
  assets/js/lib/api/softwareUpdates.js
  assets/js/state/index.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/selectors/softwareUpdates.test.js
  assets/js/state/softwareUpdates.js
  assets/js/state/softwareUpdates.test.js
Labels: enhancement, javascript

#2430 Display SUMA updates in Host Details page
  assets/js/lib/api/softwareUpdates.js
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdates.test.js
  assets/js/state/softwareUpdates.js
  assets/js/state/softwareUpdates.test.js
Labels: enhancement, javascript, env

#2435 Fix start execution button height
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
Labels: bug

#2443 Fix Start Execution button margin in checks execution
  assets/js/pages/ChecksSelection/ChecksSelectionHeader.jsx
Labels: bug

#2437 Turn on SUMA integration flag
  config/config.exs
  config/prod.exs
Labels: chore, env

#2458 Remove `cursor: pointer` style on Available Software Updates component
  assets/js/common/AvailableSoftwareUpdates/Indicator.jsx
Labels: javascript

#2453 Test suma connection UI
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.jsx
  assets/js/common/Button/Button.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.stories.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.test.jsx
  assets/js/lib/api/softwareUpdatesSettings.js
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/sagas/softwareUpdatesSettings.test.js
  assets/js/state/selectors/softwareUpdatesSettings.js
  assets/js/state/selectors/softwareUpdatesSettings.test.js
  assets/js/state/softwareUpdatesSettings.js
  assets/js/state/softwareUpdatesSettings.test.js
  test/e2e/cypress/e2e/settings.cy.js
Labels: enhancement, user story, ux, javascript, env

#2457 Make `Software Updates` service handle no SUMA settings saved
  lib/trento/software_updates.ex
  lib/trento_web/controllers/fallback_controller.ex
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
Labels: enhancement, elixir

#2464 Fix typespec for `get software updates` service
  lib/trento/software_updates.ex
Labels: bug, elixir

#2456 Sap system deregistration/restore based on the database
  lib/trento/event_handlers_supervisor.ex
  lib/trento/infrastructure/commanded/event_handlers/database_deregistration_event_handler.ex
  lib/trento/infrastructure/commanded/event_handlers/database_restore_event_handler.ex
  lib/trento/infrastructure/commanded/middleware/enrich_register_application_instance.ex
  lib/trento/router.ex
  lib/trento/sap_systems/commands/deregister_sap_system.ex
  lib/trento/sap_systems/commands/register_application_instance.ex
  lib/trento/sap_systems/commands/restore_sap_system.ex
  lib/trento/sap_systems/events/sap_system_registered.ex
  lib/trento/sap_systems/projections/database_read_model.ex
  lib/trento/sap_systems/projections/sap_system_projector.ex
  lib/trento/sap_systems/projections/sap_system_read_model.ex
  lib/trento/sap_systems/sap_system.ex
  lib/trento_web/views/v1/sap_system_view.ex
  priv/repo/migrations/20240321095516_add_database_sap_system_relationship.exs
  test/support/factory.ex
  test/trento/infrastructure/commanded/event_handlers/database_deregistration_event_handler_test.exs
  test/trento/infrastructure/commanded/event_handlers/database_restore_event_handler_test.exs
  test/trento/infrastructure/commanded/middleware/enrich_register_application_instance_test.exs
  test/trento/sap_systems/projections/sap_system_projector_test.exs
  test/trento/sap_systems/sap_system_test.exs
  test/trento/sap_systems/services/health_summary_service_test.exs
  test/trento/sap_systems_test.exs
  test/trento_web/controllers/v1/health_overview_controller_test.exs
Labels: enhancement, elixir

#2471 Update Redux Toolkit to version 2.0
  assets/js/state/index.js
  assets/package-lock.json
  assets/package.json
Labels: enhancement, javascript

#2469 Database rollup
  lib/trento/databases/commands/rollup_database.ex
  lib/trento/databases/database.ex
  lib/trento/databases/events/database_roll_up_requested.ex
  lib/trento/databases/events/database_rolled_up.ex
  lib/trento/databases/events/database_tombstoned.ex
  lib/trento/databases/lifespan.ex
  lib/trento/infrastructure/commanded/event_handlers/roll_up_event_handler.ex
  lib/trento/infrastructure/commanded/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/infrastructure/commanded/process_managers/deregistration_process_manager.ex
  lib/trento/router.ex
  test/support/factory.ex
  test/trento/databases/database_test.exs
  test/trento/infrastructure/commanded/event_handlers/stream_roll_up_event_handler_test.exs
  test/trento/infrastructure/commanded/process_managers/deregistration_process_manager_test.exs
Labels: enhancement

#2436 Clear software updates discovered health on host deregistration
  lib/trento/hosts/host.ex
  test/trento/hosts/host_test.exs
Labels: enhancement, elixir

#2477 Read `SUSE Manager Enabled` flag from config in `HostDetailsPage`
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
Labels: javascript

#2473 Adapt frontend to use the new database_id field
  assets/js/lib/test-utils/data/databases.js
  assets/js/lib/test-utils/factories/databases.js
  assets/js/lib/test-utils/factories/sapSystems.js
  assets/js/pages/ClusterDetails/ClustersList.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/tableConfigs.jsx
  assets/js/pages/HostsList/HostsList.jsx
  assets/js/pages/HostsList/HostsList.test.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.jsx
  assets/js/state/databases.js
  assets/js/state/databases.test.js
  assets/js/state/instances.js
  assets/js/state/sagas/databases.js
  assets/js/state/sagas/databases.test.js
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
  assets/js/state/selectors/sapSystem.js
Labels: enhancement, chore

#2478 Fix incorrect alias in database value object
  lib/trento/sap_systems/database.ex
Labels: bug
