Repository trento-project/web, pull requests merged in 2024-05, with the labels that each got.

#2552 Policy enforcing on users
  config/config.exs
  lib/trento/abilities/ability.ex
  lib/trento/abilities/users_abilities.ex
  lib/trento/release.ex
  lib/trento/users.ex
  lib/trento/users/policy.ex
  lib/trento/users/user.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/plugs/load_user_plug.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/users_view.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20240423104437_create_abilities.exs
  priv/repo/migrations/20240423110214_attach_abilities_to_users.exs
  priv/repo/migrations/20240425131500_add_basic_permissions.exs
  priv/repo/seeds.exs
  test/support/factory.ex
  test/trento/abilities_test.exs
  test/trento/users/policy_test.exs
  test/trento/users_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
  test/trento_web/plugs/load_user_plug_test.exs
Labels: enhancement, elixir

#2566 Edit user form
  assets/js/lib/api/users.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/Users/CreateUserPage.test.jsx
  assets/js/pages/Users/EditUserPage.jsx
  assets/js/pages/Users/EditUserPage.test.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
  assets/js/pages/Users/index.js
  assets/js/trento.jsx
Labels: enhancement, env

#2561 Read tracked software updates discoveries
  lib/trento/software_updates.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/discovery/discovery_result.ex
  lib/trento_web/controllers/fallback_controller.ex
  test/support/factory.ex
  test/trento/software_updates/discovery_test.exs
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
Labels: enhancement, elixir, env

#2582 Manage npm dependencies
  assets/package-lock.json
  assets/package.json
Labels: chore, dependencies

#2583 User profile routes
  lib/trento/users.ex
  lib/trento/users/user.ex
  lib/trento_web/controllers/v1/profile_controller.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/profile_view.ex
  test/trento/users_test.exs
  test/trento_web/controllers/v1/profile_controller_test.exs
Labels: enhancement, elixir

#2584 Add soft delete for email and update test
  lib/trento/users/user.ex
  test/trento/users_test.exs
Labels: bug, elixir

#2591 Enable user status update
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
  lib/trento/users.ex
  lib/trento/users/user.ex
  test/trento/users_test.exs
Labels: enhancement

#2581 Validation of CA certificate inside SUSE Manager settings
  lib/trento/software_updates.ex
  lib/trento/software_updates/settings.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20240502105156_migrate_suma_settings_sti.exs
  test/support/factory.ex
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
Labels: enhancement, chore

#2592 Disable admin edit in frontend
  assets/js/lib/model/users.js
  assets/js/lib/model/users.test.js
  assets/js/pages/Users/EditUserPage.jsx
  assets/js/pages/Users/EditUserPage.test.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/Users.jsx
Labels: enhancement

#2596 Use plain string certificates
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  lib/trento/infrastructure/software_updates/auth/state.ex
  lib/trento/infrastructure/software_updates/auth/suma_auth.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  test/trento/infrastructure/software_updates/auth/suma_auth_test.exs
  test/trento/infrastructure/software_updates/suma_test.exs
Labels: enhancement, elixir

#2595 Optimistic lock for users
  assets/js/lib/api/users.js
  assets/js/pages/Users/EditUserPage.jsx
  lib/trento/users.ex
  lib/trento/users/user.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/openapi/v1/schema/precondition_failed.ex
  lib/trento_web/openapi/v1/schema/precondition_required.ex
  lib/trento_web/views/error_view.ex
  priv/repo/migrations/20240506100222_add_lock_version_to_users.exs
  test/trento/users_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
Labels: enhancement, elixir, env

#2593 Make SUSE Manager section in Host Details page reactive
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/channels.js
  assets/js/state/hosts.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/selectors/softwareUpdates.test.js
  assets/js/state/softwareUpdates.js
  assets/js/state/softwareUpdates.test.js
  lib/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler.ex
  test/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler_test.exs
Labels: enhancement, javascript, elixir

#2602 Ensure SUMA related controllers return 403 when credentials were not set
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/views/error_view.ex
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
  test/trento_web/views/error_view_test.exs
Labels: chore

#2590 Add top-right corner profile button & menu
  assets/js/common/ProfileMenu/ProfileMenu.jsx
  assets/js/common/ProfileMenu/ProfileMenu.stories.jsx
  assets/js/common/ProfileMenu/ProfileMenu.test.jsx
  assets/js/common/ProfileMenu/index.js
  assets/js/lib/auth/index.js
  assets/js/pages/Layout/Layout.jsx
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  assets/js/state/selectors/user.js
  assets/js/state/user.js
  assets/js/state/user.test.js
  assets/js/trento.jsx
Labels: enhancement, ux

#2607 Fix users/profile controller tests
  test/trento_web/controllers/v1/profile_controller_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
Labels: chore

#2594 Update installation instructions
  guides/development/hack_on_the_trento.md
  mix.exs
Labels: documentation

#2576 Add a generate password button for the UserForm
  assets/js/common/Input/Password.jsx
  assets/js/common/Input/Password.stories.jsx
  assets/js/pages/Users/EditUserPage.test.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
  assets/js/pages/Users/generatePassword.js
  assets/js/pages/Users/generatePassword.test.js
Labels: enhancement, javascript, env

#2610 Fix SUMA settings error handling
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/sagas/softwareUpdatesSettings.test.js
Labels: bug, env

#2611 Users abilities frontend
  assets/js/lib/api/abilities.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/Users/CreateUserPage.jsx
  assets/js/pages/Users/CreateUserPage.test.jsx
  assets/js/pages/Users/EditUserPage.jsx
  assets/js/pages/Users/EditUserPage.test.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
Labels: enhancement

#2612 Forbidden guard for user entries
  assets/js/pages/ForbiddenGuard/ForbiddeGuard.test.jsx
  assets/js/pages/ForbiddenGuard/ForbiddenGuard.jsx
  assets/js/pages/ForbiddenGuard/index.js
  assets/js/pages/Layout/Layout.jsx
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  assets/js/state/user.js
  assets/js/state/user.test.js
  assets/js/trento.jsx
Labels: enhancement

#2616 Interpolate validation errors in error view
  lib/trento_web/views/error_view.ex
  test/support/structs/test_data_with_validation.ex
  test/trento_web/views/error_view_test.exs
Labels: enhancement

#2615 User Profile page
  assets/js/lib/api/users.js
  assets/js/lib/forms/index.jsx
  assets/js/pages/Profile/ProfileForm.jsx
  assets/js/pages/Profile/ProfileForm.stories.jsx
  assets/js/pages/Profile/ProfileForm.test.jsx
  assets/js/pages/Profile/ProfilePage.jsx
  assets/js/pages/Profile/ProfilePage.test.jsx
  assets/js/pages/Profile/ProfilePasswordChangeForm.jsx
  assets/js/pages/Profile/ProfilePasswordChangeForm.stories.jsx
  assets/js/pages/Profile/ProfilePasswordChangeForm.test.jsx
  assets/js/pages/Profile/index.js
  assets/js/pages/Users/UserForm.jsx
  assets/js/trento.jsx
  assets/package-lock.json
Labels: enhancement, javascript, env

#2613 User edit create toast
  assets/js/pages/Users/CreateUserPage.jsx
  assets/js/pages/Users/CreateUserPage.test.jsx
  assets/js/pages/Users/EditUserPage.jsx
  assets/js/pages/Users/EditUserPage.test.jsx
Labels: enhancement, javascript, env

#2622 Rescue StaleError in user update function when abilities are present
  lib/trento/users.ex
Labels: bug, elixir

#2624 Password change request
  lib/trento/users.ex
  lib/trento/users/user.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/views/v1/profile_view.ex
  lib/trento_web/views/v1/users_view.ex
  priv/repo/migrations/20240508125711_add_password_change_requested_at_to_users.exs
  test/support/factory.ex
  test/trento/users_test.exs
Labels: enhancement

#2626 Change placeholders
  assets/js/pages/Users/EditUserPage.jsx
  assets/js/pages/Users/EditUserPage.test.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
Labels: enhancement, javascript

#2625 Password change request frontend
  assets/js/common/ProfileMenu/ProfileMenu.jsx
  assets/js/common/ToastNotifications/ToastNotifications.jsx
  assets/js/common/ToastNotifications/ToastNotifications.test.jsx
  assets/js/common/ToastNotifications/index.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/Profile/ProfilePage.jsx
  assets/js/pages/Profile/ProfilePage.test.jsx
  assets/js/state/notifications.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/notifications.jsx
  assets/js/state/sagas/notifications.test.jsx
  assets/js/state/sagas/settings.js
  assets/js/state/sagas/settings.test.jsx
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  assets/js/state/user.js
  assets/js/state/user.test.js
  assets/js/trento.jsx
Labels: enhancement

#2629 Update alerting.md
  guides/alerting/alerting.md
Labels: documentation

#2630 Clean and improve e2e performance
  test/e2e/cypress/e2e/about.cy.js
  test/e2e/cypress/e2e/clusters_overview.cy.js
  test/e2e/cypress/e2e/databases_overview.cy.js
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/e2e/hana_database_details.cy.js
  test/e2e/cypress/e2e/home.cy.js
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/e2e/cypress/e2e/sap_system_details.cy.js
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
  test/e2e/cypress/e2e/saptune_details.cy.js
  test/e2e/cypress/support/commands.js
  test/e2e/cypress/support/e2e.js
Labels: removal

#2639 Specify elixir version >= 1.15 in rpm spec
  packaging/suse/rpm/trento-web.spec
Labels: enhancement

#2631 e2e user management
  assets/js/lib/test-utils/factories/users.js
  test/e2e/cypress/e2e/users.cy.js
  test/e2e/cypress/support/commands.js
  test/e2e/cypress/support/e2e.js
Labels: enhancement, chore, test

#2641 Pin erlang version to 26.2.1
  .github/workflows/ci.yaml
  .tool-versions
Labels: enhancement

#2623 Add PatchList component
  assets/js/common/PatchList/PatchList.jsx
  assets/js/common/PatchList/PatchList.stories.jsx
  assets/js/common/PatchList/PatchList.test.jsx
  assets/js/common/PatchList/index.js
  assets/js/lib/test-utils/factories/relevantPatches.js
Labels: enhancement, javascript

#2645 Release 2.3.0
  CHANGELOG.md
Labels: release

#2640 Add validation when a password is generated
  assets/js/lib/forms/index.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/generatePassword.js
  assets/js/pages/Users/generatePassword.test.js
  lib/trento/users/user.ex
Labels: enhancement, javascript

#2646 User totp fields
  lib/trento/users/user.ex
  priv/repo/migrations/20240522122122_add_totp_fields_to_users.exs
  test/trento/users/user_test.exs
Labels: enhancement, chore

#2636 Add upgradable packages list component
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.jsx
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.stories.jsx
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.test.jsx
  assets/js/lib/test-utils/factories/upgradablePackage.js
Labels: enhancement, javascript

#2649 Add host patches page
  assets/js/lib/test-utils/factories/index.js
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.stories.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.test.jsx
  assets/js/pages/HostRelevantPatches/Page.jsx
  assets/js/pages/HostRelevantPatches/index.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/selectors/softwareUpdates.test.js
  assets/js/trento.jsx
Labels: enhancement, javascript

#2651 Topt enrollment backend procedure
  lib/trento/users.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/profile_controller.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/profile_view.ex
  mix.exs
  mix.lock
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento/users_test.exs
  test/trento_web/controllers/v1/profile_controller_test.exs
Labels: enhancement, elixir

#2647 Login with totp
  assets/js/pages/Login/Login.jsx
  assets/js/pages/Login/Login.test.jsx
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  assets/js/state/user.js
  config/config.exs
  lib/trento/users.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/session_controller.ex
  lib/trento_web/openapi/v1/schema/unauthorized.ex
  test/trento/users_test.exs
  test/trento_web/controllers/session_controller_test.exs
Labels: enhancement
