Repository trento-project/web, pull requests merged in 2024-04, with the labels that each got.

#2476 Add CopyButton component
  assets/css/tooltip.scss
  assets/js/common/ApiKeyBox/ApiKeyBox.jsx
  assets/js/common/ApiKeyBox/index.js
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.jsx
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.test.jsx
  assets/js/common/CopyButton/CopyButton.jsx
  assets/js/common/CopyButton/CopyButton.stories.jsx
  assets/js/common/CopyButton/index.js
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/pages/SettingsPage/SettingsPage.test.jsx
  assets/package-lock.json
  assets/package.json
  package-lock.json
  test/e2e/cypress/e2e/settings.cy.js
Labels: enhancement, javascript

#2481 Add extra events triggering host rollup
  lib/trento/infrastructure/commanded/event_handlers/stream_roll_up_event_handler.ex
Labels: chore

#2479 Add fqdns to photofinish fixtures
  test/fixtures/discovery/host_discovery.json
  test/fixtures/discovery/host_discovery_with_installation_source.json
  test/fixtures/scenarios/aws-landscape/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json
  test/fixtures/scenarios/aws-landscape/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json
  test/fixtures/scenarios/aws-landscape/1b0e9297-97dd-55d6-9874-8efde4d84c90_host_discovery.json
  test/fixtures/scenarios/aws-landscape/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_host_discovery.json
  test/fixtures/scenarios/aws-landscape/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_host_discovery.json
  test/fixtures/scenarios/aws-landscape/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/1b0e9297-97dd-55d6-9874-8efde4d84c90_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_host_discovery.json
  test/fixtures/scenarios/gcp-landscape/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/0f6e6491-21f2-495e-9f2d-bc50b872efaf_host_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/43dcb497-2652-4254-b53a-3ff1d3b2a0ff_host_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/5f2632a9-7b18-4c37-955a-fe16cadaaef4_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/1109be4b-54fb-4796-b073-f4cc04d2ca55_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/12ab9a68-c047-4eda-81c8-1e24578d9973_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/16bd3ed1-923d-46ff-b6d0-9bfed42e387b_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/28edd956-2155-487e-a4eb-f3d4cf7c9543_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/33ec3a15-103b-453b-b6b2-f3f971582dc_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/f3463fd1-004a-4214-afd4-b15160b0d521_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/098fc159-3ed6-58e7-91be-38fda8a833ea_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/0fc07435-7ee2-54ca-b0de-fb27ffdc5deb_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/116d49bd-85e1-5e59-b820-83f66db8800c_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/25677e37-fd33-5005-896c-9275b1284534_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/3711ea88-9ccc-5b07-8f9d-042be449d72b_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/422686d6-b2d1-5092-93e8-a744854f5085_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/4b30a6af-4b52-5bda-bccb-f2248a12c992_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/69f4dcbb-efa2-5a16-8bc8-01df7dbb7384_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/81e9b629-c1e7-538f-bff1-47d3a6580522_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/927901fa-2c87-524e-b18c-3ef5187f504f_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a26b6d0-6e72-597c-9fe5-152a6875f214_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9cd46919-5f19-59aa-993e-cf3736c71053_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/a09d9cf3-46c1-505c-8fb8-4b0a71a9114e_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/a3297d85-5e8b-5ac5-b8a3-55eebc2b8d12_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/ddcb7992-2ffb-5c10-8b39-80685f6eaaba_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/e0c182db-32ff-55c6-a9eb-2b82dd21bc8b_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/f0c808b3-d869-5192-a944-20f66a6a8449_host_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_host_discovery.json
  test/fixtures/scenarios/single-hana-single-app/c4914bd4-efa3-553a-9a52-e9b562e210e5_host_discovery.json
  test/fixtures/scenarios/single-hana-single-app/e77ab524-c4e4-5381-bb59-5af8639d52a4_host_discovery.json
Labels: chore

#2487 Fix suma ca cert options
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
Labels: bug, env

#2475 Dynamic catalog filters
  assets/js/pages/ChecksCatalog/ChecksCatalog.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.stories.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalogPage.jsx
  assets/js/state/catalog.js
  assets/js/state/catalog.test.js
  assets/js/state/sagas/catalog.js
  assets/js/state/sagas/catalog.test.js
  assets/js/state/selectors/catalog.js
  assets/js/state/selectors/catalog.test.js
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement, javascript, env

#2493 Hide misleading navigation icon from software updates indicator
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.test.jsx
  assets/js/common/AvailableSoftwareUpdates/Indicator.jsx
Labels: chore

#2494 Fix checking existence of certain checks in the catalog
  assets/js/lib/model/checks.js
  assets/js/lib/model/checks.test.js
  assets/js/pages/ChecksCatalog/ChecksCatalog.jsx
Labels: bug, env

#2495 Api key Expiration Label fix
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/state/sagas/settings.jsx
  assets/js/state/sagas/settings.test.jsx
Labels: bug, env

#2485 Handle old database events
  lib/trento/databases/database.ex
  lib/trento/databases/events/database_deregistered.ex
  lib/trento/databases/events/database_health_changed.ex
  lib/trento/databases/events/database_instance_deregistered.ex
  lib/trento/databases/events/database_instance_health_changed.ex
  lib/trento/databases/events/database_instance_marked_absent.ex
  lib/trento/databases/events/database_instance_marked_present.ex
  lib/trento/databases/events/database_instance_registered.ex
  lib/trento/databases/events/database_instance_system_replication_changed.ex
  lib/trento/databases/events/database_registered.ex
  lib/trento/databases/events/database_restored.ex
  lib/trento/databases/events/database_rolled_up.ex
  lib/trento/databases/events/upcaster/upcast_database_id.ex
  lib/trento/infrastructure/commanded/middleware/enrich_deregister_application_instance.ex
  lib/trento/infrastructure/commanded/process_managers/deregistration_process_manager.ex
  lib/trento/sap_systems/events/sap_system_rolled_up.ex
  lib/trento/support/event.ex
  lib/trento/support/intermediate_event.ex
  priv/repo/migrations/20240327074541_delete_sap_system_entries.exs
  test/support/structs/test_custom_supersede_event.ex
  test/trento/databases/database_test.exs
  test/trento/databases/events/database_rolled_up_test.exs
  test/trento/databases/events/upcaster/upcast_database_id_test.exs
  test/trento/infrastructure/commanded/middleware/enrich_deregister_application_instance_test.exs
  test/trento/sap_systems/events/sap_system_rolled_up_test.exs
  test/trento/support/event_test.exs
  test/trento/support/intermediate_event_test.exs
Labels: enhancement

#2503 Pin docker-compose postgres to 15
  docker-compose.yaml
Labels: chore

#2500 Multi tenant discovery
  assets/js/pages/HealthSummary/HomeHealthSummary.jsx
  assets/js/pages/HealthSummary/HomeHealthSummary.test.jsx
  lib/trento/databases/commands/register_database_instance.ex
  lib/trento/databases/database.ex
  lib/trento/databases/events/database_instance_registered.ex
  lib/trento/databases/events/database_tenants_updated.ex
  lib/trento/databases/projections/database_instance_read_model.ex
  lib/trento/databases/projections/database_projector.ex
  lib/trento/databases/projections/database_read_model.ex
  lib/trento/databases/value_objects/tenant.ex
  lib/trento/discovery/policies/sap_system_policy.ex
  lib/trento/infrastructure/commanded/middleware/enrich_register_application_instance.ex
  lib/trento/sap_systems/services/health_summary_service.ex
  lib/trento_web/openapi/v1/schema/sap_system.ex
  lib/trento_web/views/v1/database_view.ex
  lib/trento_web/views/v1/health_overview_view.ex
  priv/repo/migrations/20240408112012_add_multiple_tenants_to_databases.exs
  priv/repo/migrations/20240408124205_add_tenants_database_index.exs
  test/fixtures/discovery/sap_system_discovery_database_multi_tenant.json
  test/support/factory.ex
  test/trento/databases/database_test.exs
  test/trento/databases/projections/database_projector_test.exs
  test/trento/discovery/policies/sap_system_policy_test.exs
  test/trento/infrastructure/commanded/middleware/enrich_register_application_instance_test.exs
  test/trento/sap_systems/services/health_summary_service_test.exs
  test/trento_web/views/v1/health_overview_view_test.exs
  test/trento_web/views/v1/sap_system_view_test.exs
Labels: enhancement, elixir, env

#2504 Add upcasting regression e2e test to the CI
  .github/workflows/ci.yaml
  test/fixtures/regression/sap_system_split/trento_dev.sql
  test/fixtures/regression/sap_system_split/trento_eventstore_dev.sql
Labels: github_actions, test, regression

#2507 Handle requests for software updates discoveries from Host aggregate
  lib/trento/hosts/host.ex
  test/support/factory.ex
  test/trento/hosts/host_test.exs
Labels: enhancement

#2514 Add intermediate confirmation step in ApiKeySettingsModal
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.jsx
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.test.jsx
  test/e2e/cypress/e2e/settings.cy.js
Labels: enhancement, javascript, env

#2515 Software updates event handler
  config/config.exs
  config/demo.exs
  config/test.exs
  lib/trento/event_handlers_supervisor.ex
  lib/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler.ex
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento/software_updates/discovery.ex
  test/support/factory.ex
  test/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler_test.exs
  test/trento/software_updates/discovery_test.exs
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
Labels: enhancement, env

#2520 Fix empty relevant patches visualization
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.stories.jsx
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.test.jsx
  assets/js/common/AvailableSoftwareUpdates/Indicator.jsx
Labels: bug, env

#2519 Issue software updates discoveries on save/change settings
  lib/trento/hosts/host.ex
  lib/trento/software_updates.ex
  test/trento/hosts/host_test.exs
  test/trento/software_updates_test.exs
Labels: enhancement, elixir, env

#2527 Add missed permission check
  .github/workflows/ci.yaml
Labels: regression

#2530 Properly clear suma genserver state when clearing software updates settings
  lib/trento/software_updates/discovery.ex
  test/trento/software_updates/discovery_test.exs
Labels: bug, elixir, env

#2528 Change `software_updates_discovery_health` default value
  lib/trento/hosts/commands/complete_software_updates_discovery.ex
  lib/trento/hosts/events/software_updates_discovery_completed.ex
  lib/trento/hosts/events/software_updates_health_changed.ex
  lib/trento/hosts/host.ex
  lib/trento/hosts/value_objects/relevant_patches.ex
  lib/trento/infrastructure/commanded/event_handlers/stream_roll_up_event_handler.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/enums/software_updates_health.ex
  test/support/factory.ex
  test/trento/hosts/host_test.exs
  test/trento/software_updates/discovery_test.exs
Labels: enhancement, elixir, env

#2526 Add a generate sid function and fix bug
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/lib/test-utils/factories/databases.js
  assets/js/lib/test-utils/factories/index.js
  assets/js/lib/test-utils/factories/sapSystems.js
  assets/js/pages/DeregistrationModal/DeregistrationModal.test.jsx
  assets/js/pages/HostsList/HostsList.test.jsx
Labels: bug, tech debt, javascript

#2532 Handle software updates discovery errors
  lib/trento/software_updates/discovery.ex
  test/trento/hosts/host_test.exs
  test/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler_test.exs
  test/trento/software_updates/discovery_test.exs
Labels: enhancement, elixir

#2535 Adjust suma timeouts
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  lib/trento/infrastructure/software_updates/suma.ex
Labels: enhancement

#2533 Asynchronously run software updates discovery when applying settings
  lib/trento/application.ex
  lib/trento/software_updates.ex
  test/support/task_case.ex
  test/trento/software_updates_test.exs
Labels: enhancement, elixir

#2537 Raise when waiting for tasks completion times out
  test/support/task_case.ex
Labels: chore

#2534 Deregister sap system on tenant removal
  lib/trento/databases/database.ex
  lib/trento/databases/events/database_tenants_updated.ex
  lib/trento/databases/projections/database_read_model.ex
  lib/trento/infrastructure/commanded/event_handlers/database_deregistration_event_handler.ex
  test/trento/databases/database_test.exs
  test/trento/infrastructure/commanded/event_handlers/database_deregistration_event_handler_test.exs
Labels: enhancement, env, regression

#2531 Improve suma authentication concurrency
  config/config.exs
  lib/trento/application.ex
  lib/trento/infrastructure/software_updates/auth/gen.ex
  lib/trento/infrastructure/software_updates/auth/state.ex
  lib/trento/infrastructure/software_updates/auth/suma_auth.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/software_updates/discovery.ex
  test/test_helper.exs
  test/trento/infrastructure/software_updates/auth/suma_auth_test.exs
  test/trento/infrastructure/software_updates/suma_test.exs
  test/trento/software_updates/discovery_test.exs
Labels: enhancement

#2547 Avoid SUMA health complete on settings not configured error
  lib/trento/software_updates/discovery.ex
  test/trento/software_updates/discovery_test.exs
Labels: bug, enhancement, env

#2541 Fix hana scale out no hooks
  lib/trento/discovery/policies/cluster_policy.ex
  test/fixtures/discovery/hana_cluster_discovery_hana_scale_out_no_srhooks.json
  test/trento/discovery/policies/cluster_policy_test.exs
Labels: bug, enhancement, env

#2512 Removed eula popup notification
  assets/js/pages/Eula/Community.jsx
  assets/js/pages/Eula/Community.stories.jsx
  assets/js/pages/Eula/Eula.jsx
  assets/js/pages/Eula/Eula.test.jsx
  assets/js/pages/Eula/Premium.jsx
  assets/js/pages/Eula/Premium.stories.jsx
  assets/js/pages/Eula/index.js
  assets/js/state/sagas/eula.js
  assets/js/state/sagas/index.js
  assets/js/state/settings.js
  assets/js/trento.jsx
  lib/trento/settings.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  priv/repo/migrations/20240404165703_drop_column_eula_accepted.exs
  test/trento/settings_test.exs
Labels: removal

#2551 Add factories to eslint dev list
  assets/.eslintrc.js
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/lib/test-utils/factories/databases.js
  assets/js/lib/test-utils/factories/executions.js
  assets/js/lib/test-utils/factories/hosts.js
  assets/js/lib/test-utils/factories/index.js
  assets/js/lib/test-utils/factories/sapSystems.js
  assets/js/lib/test-utils/factories/settings.js
  assets/js/lib/test-utils/factories/softwareUpdatesSettings.js
Labels: chore, javascript

#2538 Extend error handling of `AvailableSoftwareUpdates` component
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.jsx
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.stories.jsx
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.test.jsx
  assets/js/common/AvailableSoftwareUpdates/Indicator.jsx
  assets/js/common/AvailableSoftwareUpdates/Loading.jsx
  assets/js/common/AvailableSoftwareUpdates/SumaNotConfigured.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/selectors/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdatesSettings.js
  assets/js/state/selectors/softwareUpdatesSettings.test.js
  assets/js/state/softwareUpdates.js
  assets/js/state/softwareUpdates.test.js
Labels: enhancement, javascript

#2555 Change the tooltip message for SUMA's fallback scenario
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
Labels: chore

#2560 Remove `DiscoverSoftwareUpdates` command
  lib/trento/hosts/commands/discover_software_updates.ex
  lib/trento/hosts/host.ex
  lib/trento/router.ex
  test/trento/hosts/host_test.exs
Labels: removal

#2540 Track software update discoveries
  lib/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/discovery/discovery_result.ex
  priv/repo/migrations/20240422105737_create_software_updates_discovery_result.exs
  test/support/factory.ex
  test/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler_test.exs
  test/trento/software_updates/discovery_test.exs
Labels: enhancement, elixir, env

#2553 Install make and gcc in container and rpm
  Dockerfile
  packaging/suse/container/Dockerfile
  packaging/suse/rpm/trento-web.spec
Labels: chore, env

#2544 Add New User Management View
  assets/js/lib/api/users.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/Layout/Layout.jsx
  assets/js/pages/Users/Users.jsx
  assets/js/pages/Users/Users.stories.jsx
  assets/js/pages/Users/Users.test.jsx
  assets/js/pages/Users/UsersPage.jsx
  assets/js/pages/Users/UsersPage.test.jsx
  assets/js/pages/Users/index.js
  assets/js/trento.jsx
Labels: enhancement, javascript, env

#2548 Create user form
  assets/js/common/Input/Password.jsx
  assets/js/common/SuseManagerSettingsDialog/SuseManagerSettingsModal.jsx
  assets/js/lib/api/users.js
  assets/js/lib/api/validationErrors.js
  assets/js/lib/api/validationErrors.test.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/Users/CreateUserPage.jsx
  assets/js/pages/Users/CreateUserPage.test.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
  assets/js/pages/Users/UsersPage.test.jsx
  assets/js/pages/Users/index.js
  assets/js/trento.jsx
Labels: enhancement, env

#2567 Remove "SUSE Manager connection failed" error message
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.jsx
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.stories.jsx
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.test.jsx
  assets/js/common/AvailableSoftwareUpdates/Indicator.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/selectors/softwareUpdates.test.js
  assets/js/state/softwareUpdates.js
  assets/js/state/softwareUpdates.test.js
Labels: javascript, env
