Repository trento-project/web, pull requests merged in 2024-02, with the labels that each got.

#2234 Add software updates settings schema
  lib/trento/software_updates/settings.ex
  lib/trento/support/ecto/encrypted_binary.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20240130130617_create_software_update_settings.exs
Labels: enhancement, user story, elixir

#2249 Upgrade to Storybook 7.6.12
  assets/package-lock.json
  assets/package.json
Labels: chore

#2251 Fix typo in software updates settings schema
  lib/trento/software_updates/settings.ex
  priv/repo/migrations/20240130130617_create_software_update_settings.exs
Labels: chore

#2246 Fix charts tests increasing prometheus retention time in dev docker compose
  docker-compose.yaml
Labels: bug

#2248 Add ability to read software update settings
  lib/trento/software_updates.ex
  test/support/factory.ex
  test/trento/software_updates_test.exs
Labels: enhancement, user story, elixir

#2250 Add endpoint to retrieve software update settings
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/software_updates_controller.ex
  lib/trento_web/openapi/v1/schema/software_updates.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/software_updates_view.ex
  test/trento_web/controllers/v1/software_updates_controller_test.exs
  test/trento_web/views/v1/software_updates_view_test.exs
Labels: enhancement, elixir

#2264 Rename route: `/software_updates/settings` -> `/settings/suma_credentials`
  lib/trento_web/controllers/v1/suma_credentials_controller.ex
  lib/trento_web/openapi/v1/schema/suma_credentials.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/suma_credentials_view.ex
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
  test/trento_web/views/v1/suma_credentials_view_test.exs
Labels: elixir

#2220 Hana scale out discovery
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  lib/trento/discovery/policies/cluster_policy.ex
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_out.json
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_out_multitarget.json
  test/trento/discovery/policies/cluster_policy_test.exs
Labels: enhancement

#2247 Add SUSE Manager config component
  assets/js/common/SuseManagerConfig/CertificateUploadDate.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.stories.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.test.jsx
  assets/js/common/SuseManagerConfig/index.js
Labels: enhancement

#2259 Apply software updates settings
  lib/trento/software_updates.ex
  lib/trento/software_updates/settings.ex
  priv/repo/migrations/20240130130617_create_software_update_settings.exs
  test/trento/software_updates_test.exs
Labels: enhancement, user story, elixir

#2263 Add clear settings feature to software updates
  lib/trento/software_updates.ex
  test/trento/software_updates_test.exs
Labels: enhancement, user story, elixir

#2272 Add endpoint to clear SUMA credentials
  lib/trento_web/controllers/v1/suma_credentials_controller.ex
  lib/trento_web/router.ex
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
Labels: enhancement, elixir

#2273 Add change settings feature to software updates
  lib/trento/software_updates.ex
  lib/trento/software_updates/settings.ex
  test/trento/software_updates_test.exs
Labels: enhancement, user story, elixir

#2271 Add endpoint to save SUMA credentials
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/suma_credentials_controller.ex
  lib/trento_web/openapi/v1/schema/suma_credentials.ex
  lib/trento_web/router.ex
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
Labels: enhancement, elixir

#2265 Add saptune discovery payloads to the healthy clusters scenario
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/098fc159-3ed6-58e7-91be-38fda8a833ea_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/0a055c90-4cb6-54ce-ac9c-ae3fedaf40d4_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/0fc07435-7ee2-54ca-b0de-fb27ffdc5deb_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/116d49bd-85e1-5e59-b820-83f66db8800c_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/13e8c25c-3180-5a9a-95c8-51ec38e50cfc_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/1b0e9297-97dd-55d6-9874-8efde4d84c90_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/21de186a-e38f-5804-b643-7f4ef22fecfd_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/240f96b1-8d26-53b7-9e99-ffb0f2e735bf_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/25677e37-fd33-5005-896c-9275b1284534_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/3711ea88-9ccc-5b07-8f9d-042be449d72b_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/422686d6-b2d1-5092-93e8-a744854f5085_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/4b30a6af-4b52-5bda-bccb-f2248a12c992_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/69f4dcbb-efa2-5a16-8bc8-01df7dbb7384_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/7269ee51-5007-5849-aaa7-7c4a98b0c9ce_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/81e9b629-c1e7-538f-bff1-47d3a6580522_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/927901fa-2c87-524e-b18c-3ef5187f504f_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/99cf8a3a-48d6-57a4-b302-6e4482227ab6_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a26b6d0-6e72-597c-9fe5-152a6875f214_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9a3ec76a-dd4f-5013-9cf0-5eb4cf89898f_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/9cd46919-5f19-59aa-993e-cf3736c71053_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/a09d9cf3-46c1-505c-8fb8-4b0a71a9114e_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/a3297d85-5e8b-5ac5-b8a3-55eebc2b8d12_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/b767b3e9-e802-587e-a442-541d093b86b9_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/ddcb7992-2ffb-5c10-8b39-80685f6eaaba_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/e0c182db-32ff-55c6-a9eb-2b82dd21bc8b_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/f0c808b3-d869-5192-a944-20f66a6a8449_saptune_discovery.json
  test/fixtures/scenarios/healthy-27-node-SAP-cluster/fb2c6b8a-9915-5969-a6b7-8b5a42de1971_saptune_discovery.json
Labels: chore, env

#2277 Hana cluster find sites
  lib/trento/clusters/value_objects/hana_cluster_details.ex
  lib/trento/clusters/value_objects/hana_cluster_node.ex
  lib/trento/clusters/value_objects/hana_cluster_site.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  lib/trento_web/views/v1/cluster_view.ex
  test/fixtures/discovery/ha_cluster_discovery_gcp.json
  test/support/factory.ex
  test/trento/clusters/cluster_test.exs
  test/trento/clusters/projections/cluster_projector_test.exs
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/views/v1/cluster_view_test.exs
Labels: enhancement

#2290 Validate ca_cert when it was provided different than null
  lib/trento/software_updates/settings.ex
  test/trento/software_updates_test.exs
Labels: enhancement, elixir

#2291 Hana scale out scenario for photofinish
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .photofinish.toml
  test/fixtures/scenarios/hana-scale-out/1109be4b-54fb-4796-b073-f4cc04d2ca55_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-out/1109be4b-54fb-4796-b073-f4cc04d2ca55_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/1109be4b-54fb-4796-b073-f4cc04d2ca55_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-out/1109be4b-54fb-4796-b073-f4cc04d2ca55_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-out/1109be4b-54fb-4796-b073-f4cc04d2ca55_subscription_discovery.json
  test/fixtures/scenarios/hana-scale-out/12ab9a68-c047-4eda-81c8-1e24578d9973_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-out/12ab9a68-c047-4eda-81c8-1e24578d9973_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-out/12ab9a68-c047-4eda-81c8-1e24578d9973_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/12ab9a68-c047-4eda-81c8-1e24578d9973_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-out/12ab9a68-c047-4eda-81c8-1e24578d9973_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-out/12ab9a68-c047-4eda-81c8-1e24578d9973_subscription_discovery.json
  test/fixtures/scenarios/hana-scale-out/16bd3ed1-923d-46ff-b6d0-9bfed42e387b_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-out/16bd3ed1-923d-46ff-b6d0-9bfed42e387b_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-out/16bd3ed1-923d-46ff-b6d0-9bfed42e387b_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/16bd3ed1-923d-46ff-b6d0-9bfed42e387b_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-out/16bd3ed1-923d-46ff-b6d0-9bfed42e387b_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-out/16bd3ed1-923d-46ff-b6d0-9bfed42e387b_subscription_discovery.json
  test/fixtures/scenarios/hana-scale-out/28edd956-2155-487e-a4eb-f3d4cf7c9543_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-out/28edd956-2155-487e-a4eb-f3d4cf7c9543_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-out/28edd956-2155-487e-a4eb-f3d4cf7c9543_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/28edd956-2155-487e-a4eb-f3d4cf7c9543_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-out/28edd956-2155-487e-a4eb-f3d4cf7c9543_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-out/28edd956-2155-487e-a4eb-f3d4cf7c9543_subscription_discovery.json
  test/fixtures/scenarios/hana-scale-out/33ec3a15-103b-453b-b6b2-f3f971582dc_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-out/33ec3a15-103b-453b-b6b2-f3f971582dc_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-out/33ec3a15-103b-453b-b6b2-f3f971582dc_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/33ec3a15-103b-453b-b6b2-f3f971582dc_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-out/33ec3a15-103b-453b-b6b2-f3f971582dc_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-out/33ec3a15-103b-453b-b6b2-f3f971582dc_subscription_discovery.json
  test/fixtures/scenarios/hana-scale-out/f3463fd1-004a-4214-afd4-b15160b0d521_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-out/f3463fd1-004a-4214-afd4-b15160b0d521_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-out/f3463fd1-004a-4214-afd4-b15160b0d521_host_discovery.json
  test/fixtures/scenarios/hana-scale-out/f3463fd1-004a-4214-afd4-b15160b0d521_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-out/f3463fd1-004a-4214-afd4-b15160b0d521_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-out/f3463fd1-004a-4214-afd4-b15160b0d521_subscription_discovery.json
Labels: enhancement, env

#2292 Cleanup .tgz(s) from previous runs
  .github/workflows/ci.yaml
Labels: ci, rpm

#2299 Pass className through to Textarea component
  assets/js/common/Input/Textarea.jsx
Labels: chore

#2298 Add Label component
  assets/js/common/Label/Label.jsx
  assets/js/common/Label/Label.stories.jsx
  assets/js/common/Label/Label.test.jsx
  assets/js/common/Label/index.js
Labels: enhancement

#2297 Cluster maintenance mode
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  lib/trento/clusters/value_objects/ascs_ers_cluster_details.ex
  lib/trento/clusters/value_objects/hana_cluster_details.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  lib/trento_web/views/v1/cluster_view.ex
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
  test/fixtures/discovery/ha_cluster_discovery_ascs_ers_maintenance.json
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_out.json
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_out_maintenance.json
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_up.json
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_up_maintenance.json
  test/support/factory.ex
  test/trento/clusters/projections/cluster_projector_test.exs
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/controllers/v2/cluster_controller_test.exs
  test/trento_web/views/v1/cluster_view_test.exs
  test/trento_web/views/v2/cluster_view_test.exs
Labels: enhancement, javascript, elixir, env

#2296 Hana details other site nodes
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  lib/trento/discovery/policies/cluster_policy.ex
  test/trento/discovery/policies/cluster_policy_test.exs
Labels: enhancement, env

#2307 Add an error property to inputs for user feedback
  assets/js/common/Input/Input.jsx
  assets/js/common/Input/Input.stories.jsx
  assets/js/common/Input/Password.jsx
  assets/js/common/Input/Password.stories.jsx
  assets/js/common/Input/Textarea.jsx
  assets/js/common/Input/Textarea.stories.jsx
Labels: enhancement

#2306 Add endpoint to update SUSE Manager credentials
  lib/trento_web/controllers/v1/suma_credentials_controller.ex
  lib/trento_web/openapi/v1/schema/suma_credentials.ex
  lib/trento_web/router.ex
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
Labels: enhancement, elixir

#2310 Add support to PATCH requests in network client
  assets/js/lib/network/index.js
Labels: enhancement, user story, javascript

#2312 Add network operations for SUMA credentials
  assets/js/lib/api/softwareUpdatesSettings.js
Labels: enhancement, javascript

#2309 Add hana diskless sbd scenario
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .photofinish.toml
  test/fixtures/scenarios/hana-diskless-sbd/0f6e6491-21f2-495e-9f2d-bc50b872efaf_cloud_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/0f6e6491-21f2-495e-9f2d-bc50b872efaf_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/0f6e6491-21f2-495e-9f2d-bc50b872efaf_host_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/0f6e6491-21f2-495e-9f2d-bc50b872efaf_sap_system_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/0f6e6491-21f2-495e-9f2d-bc50b872efaf_saptune_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/0f6e6491-21f2-495e-9f2d-bc50b872efaf_subscription_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/43dcb497-2652-4254-b53a-3ff1d3b2a0ff_cloud_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/43dcb497-2652-4254-b53a-3ff1d3b2a0ff_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/43dcb497-2652-4254-b53a-3ff1d3b2a0ff_host_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/43dcb497-2652-4254-b53a-3ff1d3b2a0ff_sap_system_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/43dcb497-2652-4254-b53a-3ff1d3b2a0ff_saptune_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/43dcb497-2652-4254-b53a-3ff1d3b2a0ff_subscription_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/5f2632a9-7b18-4c37-955a-fe16cadaaef4_cloud_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/5f2632a9-7b18-4c37-955a-fe16cadaaef4_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/5f2632a9-7b18-4c37-955a-fe16cadaaef4_host_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/5f2632a9-7b18-4c37-955a-fe16cadaaef4_sap_system_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/5f2632a9-7b18-4c37-955a-fe16cadaaef4_saptune_discovery.json
  test/fixtures/scenarios/hana-diskless-sbd/5f2632a9-7b18-4c37-955a-fe16cadaaef4_subscription_discovery.json
Labels: enhancement

#2308 Discover diskless SBD clusters
  lib/trento/discovery/policies/cluster_policy.ex
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_up_diskless_sbd.json
  test/trento/discovery/policies/cluster_policy_test.exs
Labels: enhancement, env

#2311 Indexserver & nameserver roles in cluster sites
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.test.jsx
  lib/trento/clusters/value_objects/hana_cluster_node.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  lib/trento_web/views/v1/cluster_view.ex
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/controllers/v2/cluster_controller_test.exs
  test/trento_web/views/v1/cluster_view_test.exs
Labels: enhancement, javascript, elixir, env

#2320 Fix HostDetails story
  assets/js/common/ChartsFeatureWrapper/ChartsFeatureWrapper.jsx
  assets/js/common/ChartsFeatureWrapper/ChartsFeatureWrapper.test.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
Labels: bug

#2318 Initial software updates settings state and saga
  assets/js/lib/test-utils/factories/softwareUpdatesSettings.js
  assets/js/state/index.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/sagas/softwareUpdatesSettings.test.js
  assets/js/state/selectors/softwareUpdatesSettings.js
  assets/js/state/selectors/softwareUpdatesSettings.test.js
  assets/js/state/softwareUpdatesSettings.js
  assets/js/state/softwareUpdatesSettings.test.js
Labels: enhancement, user story, javascript

#2317 Handle concurrent settings saving operations
  lib/trento/software_updates.ex
  lib/trento/software_updates/settings.ex
  priv/repo/migrations/20240214153742_add_uniqueness_to_software_updates_settings.exs
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
Labels: bug, enhancement, elixir

#2329 Fix tiny typo in errors logic for input field
  assets/js/common/Input/Input.jsx
  assets/js/common/Input/Textarea.jsx
Labels: chore

#2326 Fetch credentials and feed SUMA Config
  assets/js/pages/Settings/index.js
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/pages/SettingsPage/SettingsPage.test.jsx
  assets/js/pages/SettingsPage/index.js
  assets/js/state/softwareUpdatesSettings.js
  assets/js/state/softwareUpdatesSettings.test.js
  assets/js/trento.jsx
Labels: enhancement, user story, javascript

#2337 Add header prop to table
  assets/js/common/Table/Pagination.jsx
  assets/js/common/Table/Table.jsx
  assets/js/common/Table/Table.stories.jsx
  assets/js/common/Table/Table.test.jsx
Labels: enhancement, javascript

#2300 Add SUSE Manager settings dialog component
  assets/js/common/SuseManagerSettingsDialog/SuseManagerSettingsModal.jsx
  assets/js/common/SuseManagerSettingsDialog/SuseManagerSettingsModal.stories.jsx
  assets/js/common/SuseManagerSettingsDialog/SuseManagerSettingsModal.test.jsx
  assets/js/common/SuseManagerSettingsDialog/errors.js
  assets/js/common/SuseManagerSettingsDialog/errors.test.js
  assets/js/common/SuseManagerSettingsDialog/index.js
Labels: enhancement

#2342 Bump httpoison version
  mix.exs
  mix.lock
Labels: chore, dependencies, env

#2338 Implement sagas for save and upsate of SUMA settings
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/sagas/softwareUpdatesSettings.test.js
  assets/js/state/softwareUpdatesSettings.js
  assets/js/state/softwareUpdatesSettings.test.js
Labels: enhancement

#2328 Cluster details updates
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/AttributesDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.jsx
  assets/js/pages/ClusterDetails/StoppedResources.jsx
  assets/js/pages/ClusterDetails/StoppedResources.test.jsx
Labels: enhancement, ux, javascript, env

#2344 Update license year to 2024
  README.md
  assets/js/pages/Layout/Layout.jsx
Labels: documentation, chore

#2346 Add `Clear Software Updates settings` Saga
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/sagas/softwareUpdatesSettings.test.js
  assets/js/state/softwareUpdatesSettings.js
Labels: enhancement, javascript

#2354 Fix software updates patching idempotency
  lib/trento/software_updates/settings.ex
  test/trento/software_updates_test.exs
Labels: bug

#2358 Change KVM provider label to "on-premise / KVM"
  assets/js/common/ClusterInfoBox/ClusterInfoBox.test.jsx
  assets/js/common/HostInfoBox/HostInfoBox.test.jsx
  assets/js/common/ProviderLabel/ProviderLabel.jsx
  assets/js/pages/HostDetailsPage/ProviderDetails.test.jsx
Labels: enhancement, javascript

#2355 Openapi schemas no additional properties
  lib/trento_web/openapi/v1/schema/bad_request.ex
  lib/trento_web/openapi/v1/schema/chart.ex
  lib/trento_web/openapi/v1/schema/checks.ex
  lib/trento_web/openapi/v1/schema/checks_catalog.ex
  lib/trento_web/openapi/v1/schema/cluster.ex
  lib/trento_web/openapi/v1/schema/database.ex
  lib/trento_web/openapi/v1/schema/discovery_event.ex
  lib/trento_web/openapi/v1/schema/health.ex
  lib/trento_web/openapi/v1/schema/host.ex
  lib/trento_web/openapi/v1/schema/http_std.ex
  lib/trento_web/openapi/v1/schema/not_found.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/openapi/v1/schema/provider.ex
  lib/trento_web/openapi/v1/schema/ready.ex
  lib/trento_web/openapi/v1/schema/sap_system.ex
  lib/trento_web/openapi/v1/schema/saptune_status.ex
  lib/trento_web/openapi/v1/schema/sles_subscription.ex
  lib/trento_web/openapi/v1/schema/suma_credentials.ex
  lib/trento_web/openapi/v1/schema/tag.ex
  lib/trento_web/openapi/v1/schema/unprocessable_entity.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  lib/trento_web/views/v1/cluster_view.ex
  lib/trento_web/views/v1/host_view.ex
  lib/trento_web/views/v1/sap_system_view.ex
  lib/trento_web/views/v2/cluster_view.ex
  test/trento_web/views/v1/host_view_test.exs
Labels: enhancement, tech debt, elixir

#2341 Cluster node status
  lib/trento/clusters/value_objects/ascs_ers_cluster_node.ex
  lib/trento/clusters/value_objects/hana_cluster_node.ex
  lib/trento/discovery/payloads/cluster/crmmon_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  lib/trento_web/views/v1/cluster_view.ex
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_up_node_status.json
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/views/v1/cluster_view_test.exs
Labels: enhancement

#2359 Change KVM label to "On-premises / KVM"
  assets/js/common/ClusterInfoBox/ClusterInfoBox.test.jsx
  assets/js/common/HostInfoBox/HostInfoBox.test.jsx
  assets/js/common/ProviderLabel/ProviderLabel.jsx
  assets/js/pages/HostDetailsPage/ProviderDetails.test.jsx
Labels: javascript

#2362 Add flag for "SUSE Manager config enabled"
  assets/jest.config.js
  assets/js/lib/config/config.js
  assets/js/lib/config/config.test.js
  assets/js/lib/config/index.js
  assets/js/pages/SettingsPage/SettingsPage.jsx
  config/demo.exs
  config/dev.exs
  config/prod.exs
  config/test.exs
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/router.ex
  lib/trento_web/templates/page/index.html.heex
Labels: enhancement, javascript, elixir

#2365 Add missing timestamps to ecto schemas
  lib/trento/clusters/cluster_enrichment_data.ex
  lib/trento/clusters/projections/cluster_read_model.ex
  lib/trento/heartbeats/heartbeat.ex
  lib/trento/hosts/projections/host_read_model.ex
  lib/trento/hosts/projections/host_telemetry_read_model.ex
  lib/trento/hosts/projections/sles_subscription_read_model.ex
  lib/trento/sap_systems/projections/application_instance_read_model.ex
  lib/trento/sap_systems/projections/database_instance_read_model.ex
  lib/trento/sap_systems/projections/database_read_model.ex
  lib/trento/sap_systems/projections/sap_system_read_model.ex
  lib/trento/settings/settings.ex
  lib/trento/tags/tag.ex
  lib/trento/users/user.ex
  lib/trento_web/openapi/v1/schema/cluster.ex
  lib/trento_web/openapi/v1/schema/database.ex
  lib/trento_web/openapi/v1/schema/host.ex
  lib/trento_web/openapi/v1/schema/sap_system.ex
  lib/trento_web/openapi/v1/schema/tag.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  priv/repo/migrations/20240221134250_add_missing_timestamps.exs
Labels: enhancement, tech debt, elixir

#2367 Fix host view to include timestamps
  lib/trento_web/views/v1/host_view.ex
Labels: tech debt, elixir

#2345 Cluster node status frontend
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/ClusterNodeName.jsx
  assets/js/pages/ClusterDetails/ClusterNodeName.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.jsx
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
Labels: enhancement, env

#2363 Integrate suma get system id
  config/config.exs
  config/prod.exs
  lib/trento/application.ex
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  lib/trento/infrastructure/software_updates/state.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/discovery/gen.ex
  test/test_helper.exs
  test/trento/infrastructure/software_updates/suma_test.exs
Labels: enhancement, user story, elixir

#2368 Change host's health based on software updates discovery result
  lib/trento/hosts/commands/complete_software_updates_discovery.ex
  lib/trento/hosts/events/software_updates_discovery_completed.ex
  lib/trento/hosts/host.ex
  lib/trento/hosts/value_objects/relevant_patches.ex
  lib/trento/router.ex
  test/trento/hosts/host_test.exs
Labels: enhancement, user story, elixir
