Repository trento-project/web, pull requests merged in 2024-10, with the labels that each got.

#3039 Adjust mantainers in ci files
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .github/workflows/pr_env_close.yaml
Labels: chore

#3038 Do not expose level info for activity log entries
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.stories.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.test.jsx
Labels: chore, env

#3030 Clean up unused PageNumberPagination
  assets/js/common/Pagination/PageNumberPagination.stories.jsx
  assets/js/common/Pagination/Pagination.jsx
  assets/js/common/Pagination/Pagination.test.jsx
  assets/js/common/Pagination/index.js
  assets/package-lock.json
  assets/package.json
Labels: removal

#3021 Raise an error during SAML init if decryption fails
  lib/trento/release.ex
Labels: enhancement

#3053 SUSE Manager - Navigate from patch detail to previews pages
  assets/js/common/BackButton/BackButton.jsx
  assets/js/lib/history/index.js
  assets/js/lib/history/index.test.js
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.jsx
  assets/js/pages/AdvisoryDetails/AdvisoryDetailsPage.jsx
Labels: bug

#3052 Improve usability of select search on large options content
  assets/js/common/Filter/Filter.jsx
  assets/js/common/Filter/Filter.stories.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: enhancement, ux, javascript, env

#3066 Adjust filters section in activity log
  assets/js/common/ComposedFilter/ComposedFilter.jsx
  assets/js/common/DateFilter/DateFilter.jsx
  assets/js/common/Filter/Filter.jsx
  assets/js/common/Table/Table.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
Labels: chore, ux, javascript, env

#3061 Fix navigation still possible from host details to SUSE Manager pages in case of error
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.test.jsx
  assets/js/common/AvailableSoftwareUpdates/Indicator.jsx
Labels: bug

#3090 Update README.md
  README.md
Labels: documentation, enhancement

#3084 Display active users only in Activity Log filter
  lib/trento/users.ex
  lib/trento_web/channels/activity_log_channel.ex
  test/trento/users_test.exs
Labels: enhancement, elixir, env

#3102 Change SAML_SP_DIR default location
  config/runtime.exs
  lib/trento/release.ex
Labels: chore
