Repository trento-project/web, pull requests merged in 2024-11, with the labels that each got.

#3098 Add a button to download upgradable packages as CSV
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.jsx
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.stories.jsx
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.test.jsx
  assets/js/lib/test-utils/factories/relevantPatches.js
  assets/js/lib/test-utils/factories/upgradablePackage.js
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.stories.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.test.jsx
Labels: bug, javascript, env

#3134 Add support for chained certificates
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  test/fixtures/cert/one_entry_chain.pem
  test/fixtures/cert/three_entries_chain.pem
  test/fixtures/cert/two_entries_chain.pem
  test/trento/infrastructure/software_updates/adapter/suma_http_executor_test.exs
Labels: bug

#3135 Sort csv content by alphabet
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.jsx
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.stories.jsx
  assets/js/lib/test-utils/factories/relevantPatches.js
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackages.test.jsx
Labels: javascript, env

#3139 Bump `photofinish` to v1.4.1
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
Labels: env

#3144 Replaces Empty Favicon with Trento Logo
  priv/static/favicon.ico
  priv/static/images/trento.svg
Labels: enhancement, chore

#3056 Activity Log search by metadata
  assets/js/common/ComposedFilter/ComposedFilter.jsx
  assets/js/common/ComposedFilter/ComposedFilter.stories.jsx
  assets/js/common/ComposedFilter/ComposedFilter.test.jsx
  assets/js/common/Input/Input.jsx
  assets/js/lib/test-utils/factories/activityLog.js
  assets/js/lib/test-utils/factories/advisoryErrata.js
  assets/js/lib/test-utils/factories/softwareUpdatesSettings.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
  assets/js/pages/ActivityLogPage/searchParams.js
  assets/js/pages/ActivityLogPage/searchParams.test.js
  assets/js/pages/SettingsPage/hooks.test.jsx
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: enhancement, user story, env

#3156 Allow the scheduled execution to check also ascs/ers clusters
  lib/trento/clusters.ex
  test/trento/clusters_test.exs
Labels: bug

#3159 Omit an unnecessary query when requesting cluster checks execution
  lib/trento/clusters.ex
Labels: chore

#3125 Handle ApplicationInstanceMoved event in deregistration
  lib/trento/infrastructure/commanded/process_managers/deregistration_process_manager.ex
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/trento/infrastructure/commanded/process_managers/deregistration_process_manager_test.exs
Labels: bug, env

#3140 Upgrade to Headless UI 2
  assets/js/common/Accordion/Accordion.jsx
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.test.jsx
  assets/js/common/Modal/Modal.jsx
  assets/js/pages/ChecksCatalog/CheckItem.test.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/pages/Users/UserForm.test.jsx
  assets/js/pages/Users/Users.test.jsx
  assets/package-lock.json
  assets/package.json
  test/e2e/cypress/e2e/activity_log.cy.js
  test/e2e/cypress/e2e/users.cy.js
Labels: tech debt, chore

#3164 Fix Activity Log type filter width
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
Labels: chore, ux, env

#3152 Add sap hana scale up cost optimized and performance optimized discovery
  .gitignore
  assets/js/common/ClusterTypeLabel/ClusterTypeLabel.jsx
  assets/js/common/SapSystemLink/SapSystemLink.jsx
  assets/js/lib/model/clusters.js
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterDetails/ClusterDetailsPage.test.jsx
  assets/js/pages/ClusterDetails/ClustersList.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/pages/HostsList/HostsList.jsx
  lib/trento/clusters/enums/hana_scenario.ex
  lib/trento/clusters/value_objects/hana_cluster_details.ex
  lib/trento/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento_web/controllers/v1/cluster_json.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  test/fixtures/discovery/ha_cluster_discovery_hana_scale_up_cost_opt.json
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/views/v1/cluster_view_json_test.exs
Labels: javascript, elixir, test, env

#3165 Use prometheus targets
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  docker-compose.yaml
  lib/trento/discovery/payloads/host_discovery_payload.ex
  lib/trento/discovery/policies/host_policy.ex
  lib/trento/hosts/commands/register_host.ex
  lib/trento/hosts/events/host_details_updated.ex
  lib/trento/hosts/events/host_registered.ex
  lib/trento/hosts/host.ex
  lib/trento/hosts/projections/host_projector.ex
  lib/trento/hosts/projections/host_read_model.ex
  lib/trento_web/controllers/v1/host_json.ex
  lib/trento_web/controllers/v1/prometheus_json.ex
  priv/repo/migrations/20241127140203_add_prometheus_targets_to_host_read_model.exs
  prometheus-dev-config.yml
  test/fixtures/discovery/host_discovery_with_prometheus_targets.json
  test/support/factory.ex
  test/trento/discovery/policies/host_policy_test.exs
  test/trento/hosts/events/host_details_updated_test.exs
  test/trento/hosts/events/host_registered_test.exs
  test/trento/hosts/host_test.exs
  test/trento/hosts/projections/host_projector_test.exs
  test/trento_web/controllers/v1/prometheus_controller_test.exs
  test/trento_web/views/v1/host_view_json_test.exs
  test/trento_web/views/v1/prometheus_json_test.exs
Labels: enhancement
