Repository trento-project/web, pull requests merged in 2024-01, with the labels that each got.

#2143 Fix SLES subscription identifier in host tests
  test/support/factory.ex
Labels: chore

#2145 Rename node exporter service in compose file for cross docker version compatibility
  docker-compose.yaml
  prometheus-dev-config.yml
Labels: bug

#2147 Enable/disable charts feature
  assets/js/common/ChartsDisabledBox/ChartsDisabledBox.jsx
  assets/js/common/ChartsDisabledBox/ChartsDisabledBox.stories.jsx
  assets/js/common/ChartsDisabledBox/index.js
  assets/js/common/ChartsFeatureWrapper/ChartsFeatureWrapper.jsx
  assets/js/common/ChartsFeatureWrapper/ChartsFeatureWrapper.test.jsx
  assets/js/common/ChartsFeatureWrapper/index.js
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  config/config.exs
  config/runtime.exs
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/plugs/charts_disabled_plug.ex
  lib/trento_web/plugs/unplug/predicates/charts_disabled.ex
  lib/trento_web/router.ex
  lib/trento_web/templates/page/index.html.heex
  lib/trento_web/views/error_view.ex
  test/trento_web/plugs/unplug/predicates/charts_disabled.exs
Labels: enhancement, javascript, elixir

#2155 Random chart data in demo environment
  config/demo.exs
  lib/trento/infrastructure/prometheus/adapter/mock_prometheus_api.ex
Labels: chore, elixir

#2154 Remove Reset Filters button in Checks selection
  assets/js/pages/ChecksCatalog/CatalogContainer.jsx
  assets/js/pages/ChecksCatalog/CatalogContainer.test.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.jsx
  assets/js/pages/ChecksSelection/ChecksSelection.stories.jsx
Labels: enhancement, chore, ux, javascript, env

#2144 Fix ascs ers detection in checks selection
  assets/js/common/ClusterInfoBox/ClusterInfoBox.jsx
  assets/js/common/ClusterInfoBox/ClusterInfoBox.test.jsx
  assets/js/pages/ClusterDetails/ClusterDetailsPage.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/pages/ExecutionResults/ExecutionHeader.jsx
  assets/js/pages/ExecutionResults/ExecutionHeader.test.jsx
  assets/js/pages/ExecutionResults/ExecutionResults.test.jsx
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
Labels: bug, chore, env

#2126 Send filesystem type to Wanda
  assets/js/lib/model/clusters.js
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/state/selectors/cluster.js
  assets/js/state/selectors/cluster.test.js
  lib/trento/clusters.ex
  lib/trento/clusters/enums/filesystem_type.ex
  lib/trento/infrastructure/checks/checks.ex
  lib/trento/infrastructure/checks/cluster_execution_env.ex
  test/trento/clusters_test.exs
Labels: enhancement

#2162 Include new cert variables required by the ansible playbook
  .github/workflows/pr_env.yaml
Labels: ci, env

#2178 Remove grafana last references
  .github/workflows/e2e.yaml
  .github/workflows/pr_env.yaml
Labels: removal

#2176 Differentiate env build between HANA and ASCS/ERS cluster details
  assets/js/lib/checks/env.js
  assets/js/lib/checks/env.test.js
  assets/js/lib/checks/index.js
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
Labels: enhancement

#2184 Docker compose utility adapt
  prometheus-dev-config.yml
Labels: chore

#2177 Add ENSA version info to Checks execution
  lib/trento/clusters.ex
  lib/trento/clusters/enums/ensa_version.ex
  lib/trento/infrastructure/checks/checks.ex
  lib/trento/infrastructure/checks/cluster_execution_env.ex
  test/trento/clusters_test.exs
Labels: enhancement, elixir

#2186 Upgrade elixir 1.15.7 otp 26
  .github/workflows/ci.yaml
  .tool-versions
  config/test.exs
  lib/trento/discovery/payloads/sap_system_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento/discovery/policies/host_policy.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20220320190026_create_settings.exs
  test/trento/support/event_handler_failure_context_test.exs
  test/trento_web/auth/api_key_test.exs
  test/trento_web/views/error_view_test.exs
Labels: enhancement

#2194 Restore github actions removed during elixir upgrade
  .github/workflows/ci.yaml
Labels: chore

#2196 Elixir upgrade dockerfiles
  Dockerfile
  packaging/suse/Dockerfile
Labels: enhancement

#2198 Add exporter_name to prometheus dev config file
  prometheus-dev-config.yml
Labels: chore

#2204 Project host FQDN
  lib/trento/discovery/payloads/host_discovery_payload.ex
  lib/trento/discovery/policies/host_policy.ex
  lib/trento/hosts/commands/register_host.ex
  lib/trento/hosts/events/host_details_updated.ex
  lib/trento/hosts/events/host_registered.ex
  lib/trento/hosts/host.ex
  lib/trento/hosts/projections/host_projector.ex
  lib/trento/hosts/projections/host_read_model.ex
  priv/repo/migrations/20240118164648_add_hosts_fqdn.exs
  test/support/factory.ex
  test/trento/hosts/events/host_details_updated_test.exs
  test/trento/hosts/events/host_registered_test.exs
  test/trento/hosts/host_test.exs
  test/trento/hosts/projections/host_projector_test.exs
Labels: enhancement

#2214 Fix required fields usage
  lib/trento/discovery/payloads/cluster/cib_discovery_payload.ex
  lib/trento/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/discovery/payloads/cluster/crmmon_discovery_payload.ex
  lib/trento/discovery/payloads/cluster/sbd_discovery_payload.ex
  lib/trento/discovery/payloads/sap_system_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
Labels: bug

#2187 Saptune summary warning icon
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/SaptuneSummary.jsx
  assets/js/pages/SaptuneDetails/SaptuneVersion.jsx
  assets/js/pages/SaptuneDetails/SaptuneVersion.test.jsx
Labels: javascript

#2209 Update README, by adding more references to installation options
  README.md
Labels: documentation

#2195 Fix playbook usage in pr_env
  .github/workflows/pr_env.yaml
Labels: bug, env

#2221 Fix TargetIcon test containing a typo
  assets/js/common/TargetIcon/TargetIcon.test.jsx
Labels: chore

#2213 Input fields
  assets/.eslintrc.js
  assets/css/app.css
  assets/css/input.scss
  assets/js/common/Input/Input.jsx
  assets/js/common/Input/Input.stories.jsx
  assets/js/common/Input/Input.test.jsx
  assets/js/common/Input/Password.jsx
  assets/js/common/Input/Password.stories.jsx
  assets/js/common/Input/Password.test.jsx
  assets/js/common/Input/Textarea.jsx
  assets/js/common/Input/Textarea.stories.jsx
  assets/js/common/Input/Textarea.test.jsx
  assets/js/common/Input/index.js
  assets/package-lock.json
  assets/package.json
Labels: enhancement, ux, javascript

#2232 Button type danger
  assets/js/common/Button/Button.jsx
  assets/js/common/Button/Button.stories.jsx
Labels: enhancement

#2229 Updated logo assets
  assets/js/pages/Login/Login.jsx
  assets/static/trento-dark.svg
  assets/static/trento-icon.png
  assets/static/trento-logo-stacked.svg
  assets/static/trento.svg
Labels: enhancement, env

#2222 Fix ENSA version calculation
  lib/trento/clusters.ex
  lib/trento/clusters/enums/cluster_ensa_version.ex
  lib/trento/infrastructure/checks/cluster_execution_env.ex
  test/trento/clusters_test.exs
Labels: bug, elixir

#2212 Add ability to encrypt and decrypt plain content
  config/config.exs
  config/runtime.exs
  lib/trento/application.ex
  lib/trento/vault.ex
  mix.exs
  mix.lock
  test/trento/vault_test.exs
Labels: enhancement, elixir
