Repository trento-project/web, pull requests merged in 2024-08, with the labels that each got.

#2798 E2E SUSE Manager integration
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.jsx
  assets/js/state/softwareUpdates.js
  config/config.exs
  config/dev.exs
  test/e2e/cypress/e2e/suse_manager_overviews.cy.js
Labels: tech debt

#2817 Log domain events
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/activity_logger.ex
  lib/trento/activity_logging/parser/activity_parser.ex
  lib/trento/activity_logging/parser/event_parser.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/event_handlers_supervisor.ex
  lib/trento/infrastructure/commanded/event_handlers/activity_log_event_handler.ex
  lib/trento/support/event.ex
  test/support/event_store_case.ex
  test/support/factory.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/event_parser_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/infrastructure/commanded/event_handlers/activity_log_event_handler_test.exs
Labels: enhancement, user story, elixir, env

#2852 Fix items-per-page table footer's CSS
  assets/js/common/Table/Pagination.jsx
Labels: chore

#2853 Adjust filtering
  assets/js/common/ComposedFilter/ComposedFilter.jsx
  assets/js/common/Table/Table.jsx
Labels: chore, ux, javascript, env

#2855 Change format of ABAP JAVA system type in SapSystemOverview
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.test.jsx
Labels: javascript

#2858 Log retention time changes
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
Labels: enhancement, user story

#2841 Domain events activity frontend
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.jsx
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.test.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.test.jsx
  assets/js/lib/model/activityLog.js
Labels: enhancement, javascript, env

#2862 Map changes to activity log settings entries in the UI
  assets/js/lib/model/activityLog.js
Labels: enhancement, user story, javascript, env

#2859 Disable and update user forms if OIDC is enabled
  assets/jest.config.js
  assets/js/lib/auth/config.js
  assets/js/lib/auth/config.test.js
  assets/js/lib/model/users.test.js
  assets/js/pages/Profile/ProfileForm.jsx
  assets/js/pages/Profile/ProfileForm.stories.jsx
  assets/js/pages/Profile/ProfileForm.test.jsx
  assets/js/pages/Profile/ProfilePage.jsx
  assets/js/pages/Users/CreateUserPage.jsx
  assets/js/pages/Users/CreateUserPage.test.jsx
  assets/js/pages/Users/EditUserPage.jsx
  assets/js/pages/Users/UserForm.jsx
  assets/js/pages/Users/UserForm.stories.jsx
  assets/js/pages/Users/UserForm.test.jsx
  assets/js/pages/Users/Users.jsx
  assets/js/pages/Users/Users.stories.jsx
  assets/js/pages/Users/Users.test.jsx
  assets/js/pages/Users/UsersPage.jsx
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  config/dev.exs
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/templates/page/index.html.heex
  mix.exs
Labels: enhancement

#2863 Disable actions when external idp is enabled
  lib/trento/user_identities/user_identity.ex
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/session_controller.ex
  lib/trento_web/controllers/v1/profile_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/plugs/external_idp_guard_plug.ex
  test/trento_web/controllers/session_controller_test.exs
  test/trento_web/controllers/v1/profile_controller_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
  test/trento_web/plugs/external_idp_guard_plug_test.exs
Labels: enhancement, elixir

#2865 View field for idp users
  lib/trento/users.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/views/v1/profile_view.ex
  lib/trento_web/views/v1/users_view.ex
  test/trento/users_test.exs
  test/trento_web/views/v1/users_view_test.exs
Labels: enhancement, elixir

#2857 Update Storybook Stories for `AvailableSoftwareUpdates`
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
Labels: chore, javascript

#2864 Fix cluster type tooltip message formatting
  assets/js/common/ClusterTypeLabel/ClusterTypeLabel.jsx
Labels: bug

#2868 User identities context assigns global abilities to a oidc user
  lib/trento/user_identities.ex
  test/trento/user_identities_test.exs
  test/trento_web/controllers/session_controller_test.exs
Labels: enhancement, elixir

#2866 Single sign on login view
  assets/jest.config.js
  assets/js/lib/auth/config.js
  assets/js/lib/auth/config.test.js
  assets/js/pages/Login/Login.jsx
  assets/js/pages/Login/Login.test.jsx
  assets/js/pages/Login/LoginForm.jsx
  assets/js/pages/Login/LoginSSO.jsx
Labels: enhancement

#2872 Release/2.3.2
  .github/workflows/ci.yaml
  CHANGELOG.md
  lib/trento/infrastructure/commanded/process_managers/legacy/deregistration_process_manager.ex
  lib/trento/support/jsonb_serializer.ex
  mix.exs
  test/e2e/package.json
  test/fixtures/regression/process_manager_rename/trento_dev.sql
  test/fixtures/regression/process_manager_rename/trento_eventstore_dev.sql
Labels: enhancement, regression

#2871 Improve frontend OIDC callback
  assets/jest.config.js
  assets/js/lib/auth/config.js
  assets/js/lib/auth/config.test.js
  assets/js/lib/auth/index.js
  assets/js/pages/Login/LoginSSO.jsx
  assets/js/pages/OidcCallback/OidcCallback.jsx
  assets/js/pages/OidcCallback/OidcCallback.test.jsx
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  assets/js/trento.jsx
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/templates/page/index.html.heex
Labels: enhancement

#2879 Allow only abilities update with OIDC
  lib/trento/users/user.ex
  lib/trento_web/controllers/v1/users_controller.ex
  test/trento/users_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
Labels: enhancement, elixir

#2874 Add option to load oidc variables in runtime
  config/runtime.exs
Labels: enhancement

#2873 Advisory details fixes
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.jsx
  assets/js/pages/AdvisoryDetails/AdvisoryDetailsPage.jsx
  assets/js/pages/AdvisoryDetails/AdvisoryDetailsPage.test.jsx
Labels: chore

#2882 Expose info about existence of prev/next page
  lib/trento_web/openapi/v1/schema/activity_log.ex
  lib/trento_web/views/v1/activity_log_view.ex
  test/trento/activity_log_test.exs
Labels: enhancement, user story, elixir

#2880 Existing user is recovered when login with oidc
  lib/trento/user_identities.ex
  lib/trento_web/controllers/session_controller.ex
  test/trento_web/controllers/session_controller_test.exs
Labels: enhancement, elixir

#2883 Fix fullname entry in trento console for a new created user by idp provider
  lib/trento/users/user.ex
Labels: bug

#2899 Update maintainer list in the PR env workflow
  .github/workflows/pr_env.yaml
  .github/workflows/pr_env_close.yaml
Labels: chore, env

#2898 Add filters to Activity log page
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/ComposedFilter/ComposedFilter.jsx
  assets/js/common/DateFilter/DateFilter.jsx
  assets/js/common/Filter/Filter.test.jsx
  assets/js/lib/api/activityLogs.js
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
  assets/js/pages/ActivityLogPage/searchParams.js
  assets/js/pages/ActivityLogPage/searchParams.test.js
  assets/package-lock.json
  assets/package.json
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: enhancement, env

#2906 Fix OIDC Runtime config
  config/runtime.exs
Labels: enhancement, elixir

#2901 Review CI job dependencies for faster execution.
  .github/workflows/ci.yaml
Labels: chore

#2903 User management logs segregation
  lib/trento/activity_log.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  test/trento_web/controllers/v1/activity_log_controller_test.exs
Labels: enhancement, elixir

#2910 Renaming PolicyHelper to AbilitiesHelper
  lib/trento/clusters/policy.ex
  lib/trento/databases/policy.ex
  lib/trento/hosts/policy.ex
  lib/trento/sap_systems/policy.ex
  lib/trento/settings/policy.ex
  lib/trento/support/abilities_helper.ex
  lib/trento/tags/policy.ex
  lib/trento/users/policy.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  test/trento/support/abilities_helper_test.exs
Labels: chore, elixir

#2908 OIDC integration E2E tests
  .github/workflows/ci.yaml
  container_fixtures/keycloak/realm.json
  test/e2e/cypress.config.js
  test/e2e/cypress/e2e/oidc_integration.cy.js
  test/e2e/cypress/fixtures/oidc-integration/users.js
  test/e2e/cypress/support/e2e.js
Labels: test, integration

#2893 Fetch patches for packages only if list is populated
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.jsx
Labels: chore

#2913 Add oidc strategy in runtime
  config/runtime.exs
Labels: enhancement, chore

#2914 Fix flacky UserPage test
  assets/js/pages/Users/UsersPage.test.jsx
Labels: bug

#2907 Add developer guide for oidc
  guides/assets/keycloack_login.png
  guides/assets/trento_single_sign_on_login.png
  guides/integration/oidc.md
Labels: documentation

#2915 Move `<Pagination>` component to dedicated folder
  assets/js/common/Pagination/Pagination.jsx
  assets/js/common/Pagination/Pagination.stories.jsx
  assets/js/common/Pagination/Pagination.test.jsx
  assets/js/common/Pagination/index.js
  assets/js/common/Table/Table.jsx
Labels: chore

#2923 Refactor pagination tests
  assets/js/common/Pagination/Pagination.jsx
  assets/js/common/Table/Table.test.jsx
  test/e2e/cypress/e2e/clusters_overview.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
Labels: chore
