Repository trento-project/web, pull requests merged in 2024-09, with the labels that each got.

#2952 Fix SUSE Manager settings CTA not showing up
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  lib/trento_web/views/error_view.ex
  test/trento_web/controllers/v1/settings_controller_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
Labels: bug

#2946 Filter out unnecessary options
  assets/js/common/DisabledGuard/DisabledGuard.jsx
  assets/js/lib/model/activityLog.js
  assets/js/lib/model/activityLog.test.js
  assets/js/lib/model/users.js
  assets/js/lib/model/users.test.js
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
Labels: enhancement, env

#2953 Oauth2 integration
  assets/jest.config.js
  assets/js/lib/auth/config.js
  assets/js/lib/auth/config.test.js
  assets/js/lib/auth/index.js
  assets/js/pages/OidcCallback/index.js
  assets/js/pages/OidcOauthCallback/OidcOauthCallback.jsx
  assets/js/pages/OidcOauthCallback/OidcOauthCallback.test.jsx
  assets/js/pages/OidcOauthCallback/index.js
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  assets/js/state/user.js
  assets/js/trento.jsx
  config/config.exs
  config/dev.exs
  config/runtime.exs
  container_fixtures/keycloak/realm.json
  lib/trento/user_identities.ex
  lib/trento/users/user.ex
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/session_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/plugs/external_idp_guard_plug.ex
  lib/trento_web/templates/page/index.html.heex
  test/trento/user_identities_test.exs
  test/trento_web/controllers/session_controller_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
  test/trento_web/plugs/external_idp_guard_plug_test.exs
Labels: enhancement, elixir

#2956 Fix scopes usage in runtime for oauth2
  config/runtime.exs
Labels: chore

#2958 E2E oauth2 integration
  .github/workflows/ci.yaml
  test/e2e/cypress.config.js
  test/e2e/cypress/e2e/sso_integration.cy.js
  test/e2e/cypress/support/e2e.js
Labels: enhancement, test, integration

#2959 General Form Label Alignment Fixes
  assets/js/pages/Profile/ProfileForm.jsx
  assets/js/pages/Users/UserForm.jsx
Labels: chore, ux

#2949 Table Header Alignment
  assets/js/common/Table/Table.jsx
  assets/js/common/Table/Table.test.jsx
Labels: chore, ux

#2924 Activity log filter by user
  assets/js/lib/test-utils/index.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
  assets/js/state/activityLog.js
  assets/js/state/activityLog.test.js
  assets/js/state/index.js
  assets/js/state/sagas/activityLog.js
  assets/js/state/sagas/activityLog.test.js
  assets/js/state/sagas/channels.js
  assets/js/state/sagas/channels.test.js
  assets/js/state/sagas/index.js
  assets/js/state/selectors/activityLog.js
  assets/js/state/selectors/activityLog.test.js
  config/config.exs
  config/test.exs
  lib/trento/users.ex
  lib/trento_web/channels/activity_log_channel.ex
  lib/trento_web/channels/user_socket.ex
  test/trento/users_test.exs
  test/trento_web/channels/activity_log_channel_test.exs
Labels: enhancement, javascript, elixir, env

#2978 Filter out non-registered hosts from affected systems in SUMA patch
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento_web/controllers/v1/suse_manager_controller.ex
  test/e2e/cypress/e2e/suse_manager_overviews.cy.js
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
Labels: enhancement

#2982 Fix typo
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: chore

#2986 Adjust activity log columns width
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
Labels: chore, env

#2957 Log host checks execution request
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/clusters.ex
  test/support/messaging_case.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/clusters_test.exs
  test/trento_web/controllers/v1/cluster_controller_test.exs
Labels: enhancement, elixir

#2994 Do not show page stats when data set is empty
  assets/js/common/Pagination/PageStats.jsx
  assets/js/common/Pagination/PageStats.test.jsx
  assets/js/common/Pagination/Pagination.stories.jsx
Labels: bug, javascript

#2985 SAML integration
  .github/workflows/ci.yaml
  assets/js/lib/auth/index.js
  assets/js/pages/OidcOauthCallback/index.js
  assets/js/pages/SSOCallback/SSOCallback.jsx
  assets/js/pages/SSOCallback/SSOCallback.test.jsx
  assets/js/pages/SSOCallback/index.js
  assets/js/state/sagas/user.js
  assets/js/state/sagas/user.test.js
  assets/js/state/user.js
  assets/js/trento.jsx
  config/config.exs
  config/dev.exs
  container_fixtures/keycloak/realm.json
  lib/trento/application.ex
  lib/trento_web/auth/assent_saml_strategy.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/session_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/plugs/external_idp_guard_plug.ex
  lib/trento_web/router.ex
  mix.exs
  mix.lock
  test/e2e/cypress/e2e/sso_integration.cy.js
  test/e2e/cypress/fixtures/sso-integration/users.js
  test/trento_web/auth/assent_saml_strategy_test.exs
  test/trento_web/controllers/session_controller_test.exs
  test/trento_web/controllers/v1/users_controller_test.exs
  test/trento_web/plugs/external_idp_guard_plug_test.exs
Labels: enhancement, integration

#2992 Expose components retrieval by id
  lib/trento/clusters.ex
  lib/trento/databases.ex
  lib/trento/hosts.ex
  lib/trento/sap_systems.ex
  test/trento/clusters_test.exs
  test/trento/databases_test.exs
  test/trento/hosts_test.exs
  test/trento/sap_systems_test.exs
Labels: enhancement, user story, elixir

#2998 Improve domain event activity detection
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/support/event.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/support/event_test.exs
Labels: enhancement, elixir

#2996 Activity log metadata enrichment
  lib/trento/activity_logging/parser/metadata_enricher.ex
  test/support/factory.ex
  test/trento/activity_logging/metadata_enricher_test.exs
Labels: enhancement, user story, elixir

#2997 Wire up MetadataEnricher
  lib/trento/activity_logging/parser/activity_parser.ex
  lib/trento/activity_logging/parser/event_parser.ex
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/event_parser_test.exs
Labels: enhancement, user story

#2999 SAML runtime operations
  config/runtime.exs
  lib/trento/release.ex
  lib/trento/settings.ex
  lib/trento/settings/sso_certificates_settings.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/settings_view.ex
  priv/repo/migrations/20240918151940_add_sso_certificates_settings_sti.exs
  test/support/factory.ex
  test/trento/release_test.exs
  test/trento/settings_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
Labels: enhancement, env, integration

#3019 Enhance messages for tagging/untagging activities
  assets/js/common/ActivityLogOverview/ActivityLogOverview.test.jsx
  assets/js/lib/model/activityLog.js
  assets/js/lib/model/activityLog.test.js
  assets/js/lib/test-utils/factories/activityLog.js
Labels: enhancement, javascript

#2995 Enable SAML messages signing
  .github/workflows/ci.yaml
  config/dev.exs
  container_fixtures/keycloak/realm.json
  container_fixtures/keycloak/saml/cert/saml_sp.pem
  container_fixtures/keycloak/saml/cert/saml_sp_key.pem
  container_fixtures/keycloak/saml/metadata.xml
Labels: chore, env, integration

#3020 Add a refresh button to the Activity Log page
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: enhancement, user story, javascript, env

#3010 Table Component Rounded Corners Fix
  assets/js/common/Table/Table.jsx
  assets/js/common/Table/Table.test.jsx
Labels: bug, chore, ux

#3025 Add back scenario loading for Activity Log e2e
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: chore

#3026 Streamline Pagination
  assets/js/common/Pagination/PageNumberPagination.stories.jsx
  assets/js/common/Pagination/PageStats.test.jsx
  assets/js/common/Pagination/Pagination.jsx
  assets/js/common/Pagination/Pagination.stories.jsx
  assets/js/common/Pagination/Pagination.test.jsx
  assets/js/common/Pagination/index.js
  assets/js/common/Table/Table.jsx
  assets/js/common/Table/Table.test.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  test/e2e/cypress/e2e/activity_log.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
Labels: enhancement, env
