Repository trento-project/web, pull requests merged in 2024-07, with the labels that each got.

#2726 Activity logger plug
  config/config.exs
  lib/trento/activity_logging/activity_logger.ex
  lib/trento/infrastructure/activity_log/logger/adapter/noop_logger.ex
  lib/trento_web/endpoint.ex
  lib/trento_web/plugs/activity_logging_plug.ex
  lib/trento_web/plugs/load_user_plug.ex
  test/support/conn_case.ex
  test/test_helper.exs
  test/trento_web/plugs/activity_logging_plug_test.exs
  test/trento_web/plugs/load_user_plug_test.exs
Labels: enhancement, user story, elixir, env

#2660 Upgrade Node.js to version 20.14.0 LTS
  .github/workflows/ci.yaml
  .github/workflows/e2e.yaml
  .tool-versions
  Dockerfile
  guides/development/hack_on_the_trento.md
  packaging/suse/container/Dockerfile
  packaging/suse/rpm/trento-web.spec
Labels: documentation, tech debt, chore, dependencies

#2720 Remove navigate usage in redux action dispatching
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ExecutionResults/CheckResultDetail/CheckResultDetailPage.jsx
  assets/js/pages/ExecutionResults/ExecutionResultsPage.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.jsx
  assets/js/pages/HostsList/HostsList.jsx
  assets/js/pages/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.jsx
  assets/js/pages/TriggerChecksExecutionRequest/TriggerChecksExecutionRequest.test.jsx
  assets/js/state/lastExecutions.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/lastExecutions.js
  assets/js/state/sagas/lastExecutions.test.js
  assets/js/trento.jsx
Labels: tech debt

#2723 E2e check selection abilities
  .photofinish.toml
  assets/js/lib/test-utils/factories/index.js
  assets/js/lib/test-utils/factories/users.js
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/e2e/users.cy.js
  test/e2e/cypress/support/commands.js
Labels: test

#2724 Checks execution abilities
  assets/js/pages/ChecksSelection/ChecksSelectionHeader.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionHeader.stories.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionHeader.test.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.test.jsx
  lib/trento/clusters/policy.ex
  lib/trento/clusters/projections/cluster_read_model.ex
  lib/trento/hosts/policy.ex
  lib/trento/hosts/projections/host_read_model.ex
  priv/repo/migrations/20240626142058_add_check_execution_permissions.exs
  test/trento/clusters/policy_test.exs
  test/trento/hosts/policy_test.exs
  test/trento_web/controllers/v1/cluster_controller_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement, javascript, elixir, env

#2732 Fix non existent path
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: chore

#2734 Cleanup abilities/permissions
  assets/js/common/CleanUpButton/CleanUpButton.jsx
  assets/js/common/CleanUpButton/CleanUpButton.stories.jsx
  assets/js/common/CleanUpButton/CleanUpButton.test.jsx
  assets/js/lib/test-utils/index.jsx
  assets/js/pages/DatabaseDetails/DatabaseDetails.jsx
  assets/js/pages/DatabaseDetails/DatabaseDetails.stories.jsx
  assets/js/pages/DatabasesOverview/DatabaseItemOverview.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.stories.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.test.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverviewPage.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/pages/HostsList/HostsList.jsx
  assets/js/pages/HostsList/HostsList.test.jsx
  assets/js/pages/InstanceOverview/InstanceOverview.jsx
  assets/js/pages/InstanceOverview/InstanceOverview.test.jsx
  assets/js/pages/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/pages/SapSystemDetails/GenericSystemDetails.test.jsx
  assets/js/pages/SapSystemDetails/SapSystemDetails.jsx
  assets/js/pages/SapSystemDetails/SapSystemDetails.stories.jsx
  assets/js/pages/SapSystemDetails/tableConfigs.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemItemOverview.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.stories.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.test.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverviewPage.jsx
  lib/trento/databases/policy.ex
  lib/trento/databases/projections/database_read_model.ex
  lib/trento/hosts/policy.ex
  lib/trento/sap_systems/policy.ex
  lib/trento/sap_systems/projections/sap_system_read_model.ex
  lib/trento_web/controllers/v1/database_controller.ex
  lib/trento_web/controllers/v1/sap_system_controller.ex
  priv/repo/migrations/20240702075045_add_clenaup_abilities.exs
  test/trento/databases/policy_test.exs
  test/trento/hosts/policy_test.exs
  test/trento/sap_systems/policy_test.exs
  test/trento_web/controllers/v1/database_controller_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
  test/trento_web/controllers/v1/sap_system_controller_test.exs
Labels: enhancement, env

#2727 Activity log settings UI state
  assets/js/common/ActivityLogsSettingsModal/ActivityLogsSettingsModal.jsx
  assets/js/common/ActivityLogsSettingsModal/ActivityLogsSettingsModal.stories.jsx
  assets/js/common/ActivityLogsSettingsModal/ActivityLogsSettingsModal.test.jsx
  assets/js/lib/api/activityLogsSettings.js
  assets/js/lib/api/validationErrors.test.js
  assets/js/lib/test-utils/factories/activityLogsSettings.js
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/pages/SettingsPage/SettingsPage.test.jsx
  assets/js/state/activityLogsSettings.js
  assets/js/state/activityLogsSettings.test.js
  assets/js/state/index.js
  assets/js/state/sagas/activityLogsSettings.js
  assets/js/state/sagas/activityLogsSettings.test.js
  assets/js/state/sagas/index.js
  assets/js/state/selectors/activityLogsSettings.js
  assets/js/state/selectors/activityLogsSettings.test.js
Labels: env

#2738 Tags policy permissions
  assets/js/common/DisabledGuard/DisabledGuard.jsx
  assets/js/common/Pill/Pill.jsx
  assets/js/common/Pill/Pill.stories.jsx
  assets/js/common/Pill/Pill.test.jsx
  assets/js/common/Tags/Tags.jsx
  assets/js/common/Tags/Tags.stories.jsx
  assets/js/common/Tags/Tags.test.jsx
  assets/js/lib/test-utils/index.jsx
  assets/js/pages/ClusterDetails/ClustersList.jsx
  assets/js/pages/ClusterDetails/ClustersList.test.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.stories.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverview.test.jsx
  assets/js/pages/DatabasesOverview/DatabasesOverviewPage.jsx
  assets/js/pages/HostsList/HostsList.jsx
  assets/js/pages/HostsList/HostsList.test.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.stories.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.test.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverviewPage.jsx
  lib/trento/tags/policy.ex
  lib/trento/tags/tag.ex
  lib/trento_web/controllers/v1/tags_controller.ex
  priv/repo/migrations/20240701074943_add_tags_abilities.exs
  test/trento/tags/policy_test.exs
  test/trento_web/controllers/v1/tags_controller_test.exs
Labels: enhancement, elixir

#2733 Return CVEs from `Errata Details` endpoint
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/suse_manager_controller.ex
  lib/trento_web/openapi/v1/schema/available_software_updates.ex
  lib/trento_web/views/v1/suse_manager_view.ex
  test/support/factory.ex
  test/trento/infrastructure/software_updates/suma_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
  test/trento_web/views/v1/suse_manager_view_test.exs
Labels: enhancement, elixir

#2739 Activity log endpoint
  lib/trento/activity_log.ex
  lib/trento/activity_logging/activity_log.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  lib/trento_web/openapi/v1/schema/activity_log.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/activity_log_view.ex
  test/support/factory.ex
  test/trento_web/controllers/v1/activity_log_controller_test.exs
Labels: enhancement, elixir

#2744 Checks execution policy addendum
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterDetails/ClusterDetailsPage.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
Labels: enhancement, javascript

#2740 Add cleanup abilities e2e tests
  test/e2e/cypress/e2e/databases_overview.cy.js
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/e2e/cypress/e2e/sap_system_details.cy.js
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
Labels: test

#2735 Display CVEs and fixes in the advisory details page
  assets/js/lib/test-utils/factories/advisoryErrata.js
  assets/js/lib/test-utils/factories/upgradablePackage.js
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.jsx
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.stories.jsx
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.test.jsx
Labels: javascript

#2742 Check execution policy e2e tests
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/package-lock.json
Labels: enhancement, test

#2747 Tags abilities e2e tests
  assets/js/common/Tags/Tags.jsx
  test/e2e/cypress/e2e/clusters_overview.cy.js
  test/e2e/cypress/e2e/databases_overview.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
Labels: javascript, test

#2754 ExistingTag component renamed to DeleteTagButton
  assets/js/common/Tags/Tags.jsx
Labels: enhancement

#2752 Minor css fixes for activity log settings
  assets/js/common/ActivityLogsConfig/ActivityLogsConfig.jsx
  assets/js/common/ActivityLogsSettingsModal/ActivityLogsSettingsModal.jsx
Labels: chore, ux, env

#2757 Provide explicit ordering for CSV file columns
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.test.jsx
Labels: enhancement, javascript

#2761 Discover angi architecture
  lib/trento/clusters/enums/hana_architecture_type.ex
  lib/trento/clusters/value_objects/hana_cluster_details.ex
  lib/trento/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento/support/struct_helper.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  lib/trento_web/views/v1/cluster_view.ex
  test/fixtures/discovery/ha_cluster_discovery_angi_hana_scale_up.json
  test/fixtures/discovery/ha_cluster_discovery_angi_hana_scale_up_failover.json
  test/support/factory.ex
  test/trento/clusters/projections/cluster_projector_test.exs
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/views/v1/cluster_view_test.exs
Labels: enhancement, env, regression

#2730 Add Persistent Activity Logger
  config/config.exs
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/activity_logger.ex
  lib/trento/activity_logging/parser/activity_parser.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/infrastructure/activity_log/logger/adapter/noop_logger.ex
  test/support/conn_case.ex
  test/test_helper.exs
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento_web/plugs/activity_logging_plug_test.exs
Labels: enhancement, user story, elixir, env

#2760 Add permissions to the Settings View
  assets/js/common/ActivityLogsConfig/ActivityLogsConfig.jsx
  assets/js/common/ActivityLogsConfig/ActivityLogsConfig.stories.jsx
  assets/js/common/ActivityLogsConfig/ActivityLogsConfig.test.jsx
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.stories.jsx
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.test.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.stories.jsx
  assets/js/common/SuseManagerConfig/SuseManagerConfig.test.jsx
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/pages/SettingsPage/SettingsPage.test.jsx
  lib/trento/activity_logging/settings.ex
  lib/trento/settings/api_key_settings.ex
  lib/trento/settings/policy.ex
  lib/trento/software_updates/policy.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/controllers/v1/suma_credentials_controller.ex
  priv/repo/migrations/20240702125459_add_settings_permissions.exs
  test/trento/settings/policy_test.exs
  test/trento/software_updates/policy_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
Labels: enhancement, javascript, elixir, test, env

#2745 Group abilities frontend
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.jsx
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.test.jsx
  assets/js/common/AbilitiesMultiSelect/index.js
  assets/js/lib/forms/index.jsx
  assets/js/pages/Profile/ProfileForm.jsx
  assets/js/pages/Users/UserForm.jsx
Labels: enhancement, env

#2766 Angi architecture frontend
  assets/js/common/ClusterInfoBox/ClusterInfoBox.jsx
  assets/js/common/ClusterInfoBox/ClusterInfoBox.test.jsx
  assets/js/common/ClusterTypeLabel/ClusterTypeLabel.jsx
  assets/js/common/ClusterTypeLabel/ClusterTypeLabel.test.jsx
  assets/js/common/ClusterTypeLabel/index.js
  assets/js/lib/checks/env.js
  assets/js/lib/checks/env.test.js
  assets/js/lib/model/clusters.js
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ExecutionResults/TargetInfoBox.jsx
Labels: enhancement, env

#2763 Affected packages
  assets/js/lib/test-utils/factories/advisoryErrata.js
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.jsx
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.stories.jsx
  assets/js/pages/AdvisoryDetails/AdvisoryDetails.test.jsx
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/suse_manager_controller.ex
  lib/trento_web/openapi/v1/schema/available_software_updates.ex
  lib/trento_web/views/v1/suse_manager_view.ex
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
  test/trento_web/views/v1/suse_manager_view_test.exs
Labels: wip, javascript, elixir

#2768 Send HANA architecture to wanda
  lib/trento/clusters.ex
  lib/trento/infrastructure/checks/checks.ex
  lib/trento/infrastructure/checks/cluster_execution_env.ex
  test/trento/clusters_test.exs
  test/trento/infrastructure/checks/checks_test.exs
Labels: enhancement

#2772 Add e2e test for settings view to test abilities/permissions
  test/e2e/cypress/e2e/settings.cy.js
Labels: enhancement, javascript, test

#2770 Angi architecture e2e tests and demo update
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .photofinish.toml
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
  test/fixtures/scenarios/hana-cluster-details/4b67842f-ccf7-46a4-a344-9e918648b117_ha_cluster_discovery_angi_failover.json
  test/fixtures/scenarios/hana-scale-up-angi/4b67842f-ccf7-46a4-a344-9e918648b117_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/4b67842f-ccf7-46a4-a344-9e918648b117_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/4b67842f-ccf7-46a4-a344-9e918648b117_host_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/4b67842f-ccf7-46a4-a344-9e918648b117_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/4b67842f-ccf7-46a4-a344-9e918648b117_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/4b67842f-ccf7-46a4-a344-9e918648b117_subscription_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/851a4dd3-9693-44c3-a40b-b32d22872e74_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/851a4dd3-9693-44c3-a40b-b32d22872e74_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/851a4dd3-9693-44c3-a40b-b32d22872e74_host_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/851a4dd3-9693-44c3-a40b-b32d22872e74_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/851a4dd3-9693-44c3-a40b-b32d22872e74_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-up-angi/851a4dd3-9693-44c3-a40b-b32d22872e74_subscription_discovery.json
Labels: test, env

#2780 Open api spex object refactor
  lib/trento/activity_log.ex
  lib/trento_web/controllers/v1/cluster_controller.ex
  lib/trento_web/controllers/v1/discovery_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/controllers/v1/profile_controller.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/controllers/v1/suma_credentials_controller.ex
  lib/trento_web/controllers/v1/tags_controller.ex
  lib/trento_web/openapi/v1/schema/ability.ex
  lib/trento_web/openapi/v1/schema/activity_log.ex
  lib/trento_web/openapi/v1/schema/available_software_updates.ex
  lib/trento_web/openapi/v1/schema/bad_request.ex
  lib/trento_web/openapi/v1/schema/chart.ex
  lib/trento_web/openapi/v1/schema/checks.ex
  lib/trento_web/openapi/v1/schema/checks_catalog.ex
  lib/trento_web/openapi/v1/schema/cluster.ex
  lib/trento_web/openapi/v1/schema/database.ex
  lib/trento_web/openapi/v1/schema/discovery_event.ex
  lib/trento_web/openapi/v1/schema/forbidden.ex
  lib/trento_web/openapi/v1/schema/health.ex
  lib/trento_web/openapi/v1/schema/host.ex
  lib/trento_web/openapi/v1/schema/http_std.ex
  lib/trento_web/openapi/v1/schema/not_found.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/openapi/v1/schema/precondition_failed.ex
  lib/trento_web/openapi/v1/schema/precondition_required.ex
  lib/trento_web/openapi/v1/schema/prometheus.ex
  lib/trento_web/openapi/v1/schema/provider.ex
  lib/trento_web/openapi/v1/schema/ready.ex
  lib/trento_web/openapi/v1/schema/resource_health.ex
  lib/trento_web/openapi/v1/schema/sap_system.ex
  lib/trento_web/openapi/v1/schema/saptune_status.ex
  lib/trento_web/openapi/v1/schema/sles_subscription.ex
  lib/trento_web/openapi/v1/schema/suma_credentials.ex
  lib/trento_web/openapi/v1/schema/tag.ex
  lib/trento_web/openapi/v1/schema/unauthorized.ex
  lib/trento_web/openapi/v1/schema/unprocessable_entity.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  mix.exs
  mix.lock
  test/e2e/cypress/e2e/users.cy.js
  test/trento/activity_log_test.exs
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
Labels: tech debt, elixir

#2788 Suse manager settings refactor
  assets/js/lib/api/softwareUpdatesSettings.js
  assets/js/lib/api/suseManagerSettings.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/sagas/softwareUpdatesSettings.test.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/infrastructure/software_updates/auth/suma_auth.ex
  lib/trento/settings.ex
  lib/trento/settings/policy.ex
  lib/trento/settings/suse_manager_settings.ex
  lib/trento/software_updates.ex
  lib/trento/software_updates/policy.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/controllers/v1/suma_credentials_controller.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/openapi/v1/schema/suma_credentials.ex
  lib/trento_web/router.ex
  lib/trento_web/views/v1/settings_view.ex
  lib/trento_web/views/v1/suma_credentials_view.ex
  test/e2e/cypress/e2e/settings.cy.js
  test/e2e/cypress/support/commands.js
  test/support/factory.ex
  test/trento/infrastructure/software_updates/auth/suma_auth_test.exs
  test/trento/settings/policy_test.exs
  test/trento/settings_test.exs
  test/trento/software_updates/policy_test.exs
  test/trento/software_updates_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
  test/trento_web/controllers/v1/suma_credentials_controller_test.exs
  test/trento_web/views/v1/settings_view_test.exs
Labels: tech debt, elixir

#2789 Fix flickering in `Available Software Updates` panel
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.jsx
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.test.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/softwareUpdates.js
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  lib/trento_web/controllers/fallback_controller.ex
  test/trento_web/controllers/v1/suse_manager_controller_test.exs
Labels: bug, ux, javascript, elixir

#2769 Activity log overview
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.jsx
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.stories.jsx
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.test.jsx
  assets/js/common/ActivityLogDetailsModal/index.js
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.stories.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.test.jsx
  assets/js/common/ActivityLogOverview/index.js
  assets/js/lib/model/activityLog.js
  assets/js/lib/test-utils/factories/activityLog.js
Labels: enhancement, user story, javascript

#2814 Fix process manager rename
  .github/workflows/ci.yaml
  lib/trento/infrastructure/commanded/process_managers/legacy/deregistration_process_manager.ex
  lib/trento/support/jsonb_serializer.ex
  test/fixtures/regression/process_manager_rename/trento_dev.sql
  test/fixtures/regression/process_manager_rename/trento_eventstore_dev.sql
Labels: bug, regression

#2774 Activity log page
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.stories.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.test.jsx
  assets/js/lib/api/activityLogs.js
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
  assets/js/pages/ActivityLogPage/index.js
  assets/js/pages/Layout/Layout.jsx
  assets/js/trento.jsx
Labels: enhancement, user story, javascript, env

#2786 Activity log pagination and filtering
  config/config.exs
  lib/trento/activity_log.ex
  lib/trento/activity_logging/activity_log.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  lib/trento_web/openapi/v1/schema/activity_log.ex
  lib/trento_web/views/v1/activity_log_view.ex
  mix.exs
  mix.lock
  test/trento/activity_log_test.exs
  test/trento_web/controllers/v1/activity_log_controller_test.exs
  test/trento_web/views/v1/activity_log_view_test.exs
Labels: enhancement, elixir

#2827 Handle unexpected successful api response
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
Labels: enhancement, javascript, env

#2821 Extend `AvailableSoftwareUpdates` to display arbitrary errors
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.jsx
  assets/js/common/AvailableSoftwareUpdates/AvailableSoftwareUpdates.test.jsx
  assets/js/common/AvailableSoftwareUpdates/Indicator.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.test.jsx
  assets/js/state/sagas/softwareUpdates.js
  assets/js/state/sagas/softwareUpdates.test.js
  assets/js/state/selectors/softwareUpdates.js
  assets/js/state/selectors/softwareUpdates.test.js
Labels: enhancement, javascript

#2831 Upgrade to Phoenix 1.7
  .formatter.exs
  .github/workflows/ci.yaml
  lib/trento/users/user.ex
  lib/trento_web.ex
  lib/trento_web/endpoint.ex
  lib/trento_web/router.ex
  lib/trento_web/templates/layout/live.html.heex
  lib/trento_web/templates/layout/root.html.heex
  lib/trento_web/templates/page/index.html.heex
  lib/trento_web/views/error_helpers.ex
  mix.exs
  mix.lock
  test/support/conn_case.ex
  test/trento_web/plugs/api_redirector_test.exs
Labels: tech debt, elixir, env

#2828 Default to activity type as a message for unrecognized activities
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.test.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.test.jsx
Labels: enhancement, user story, javascript

#2819 Suse Manager Settings - Frontend refactoring
  assets/js/lib/test-utils/index.jsx
  assets/js/pages/HostRelevantPatches/Page.jsx
  assets/js/pages/SettingsPage/SettingsPage.jsx
  assets/js/pages/SettingsPage/SettingsPage.test.jsx
  assets/js/pages/SettingsPage/hooks.js
  assets/js/pages/SettingsPage/hooks.test.jsx
  assets/js/pages/UpgradablePackagesPage/UpgradablePackagesPage.jsx
  assets/js/state/index.js
  assets/js/state/sagas/hosts.js
  assets/js/state/sagas/hosts.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/softwareUpdatesSettings.js
  assets/js/state/sagas/softwareUpdatesSettings.test.js
  assets/js/state/selectors/softwareUpdatesSettings.js
  assets/js/state/selectors/softwareUpdatesSettings.test.js
  assets/js/state/softwareUpdatesSettings.js
  assets/js/state/softwareUpdatesSettings.test.js
Labels: tech debt, javascript, env

#2839 E2E tests for java system discovery
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .photofinish.toml
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
  test/e2e/cypress/fixtures/sap-systems-overview/available_sap_systems.js
  test/fixtures/scenarios/multi-tenant/544cbc99-c856-4b0a-88cf-e6b8db4606f6_sap_system_discovery.json
  test/fixtures/scenarios/multi-tenant/e0564d66-be9e-4763-9917-655af1bb4b58_sap_system_discovery.json
  test/fixtures/scenarios/multi-tenant/f7a8969b-db9e-4162-b82a-d5cfafe1c4e9_sap_system_discovery.json
  test/fixtures/scenarios/sap-system-java/a18a203d-4f2f-4d21-b9a5-e300a9c5eeee_cloud_discovery.json
  test/fixtures/scenarios/sap-system-java/a18a203d-4f2f-4d21-b9a5-e300a9c5eeee_host_discovery.json
  test/fixtures/scenarios/sap-system-java/a18a203d-4f2f-4d21-b9a5-e300a9c5eeee_sap_system_discovery.json
  test/fixtures/scenarios/sap-system-java/a18a203d-4f2f-4d21-b9a5-e300a9c5eeee_saptune_discovery.json
  test/fixtures/scenarios/sap-system-java/a18a203d-4f2f-4d21-b9a5-e300a9c5eeee_subscription_discovery.json
Labels: enhancement, javascript, test, env

#2826 Cluster Details Action Buttons Fixes
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
Labels: bug, enhancement
