Repository trento-project/web, pull requests merged in 2024-12, with the labels that each got.

#3161 Activity log autorefresh
  assets/js/common/ActivityLogsSettingsModal/ActivityLogsSettingsModal.jsx
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.jsx
  assets/js/common/ComposedFilter/ComposedFilter.jsx
  assets/js/common/ComposedFilter/ComposedFilter.test.jsx
  assets/js/common/Select/Select.jsx
  assets/js/common/Select/Select.stories.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
  assets/js/pages/ActivityLogPage/autorefresh.js
  assets/js/pages/ActivityLogPage/autorefresh.test.js
  assets/js/pages/ActivityLogPage/searchParams.js
  assets/js/pages/ActivityLogPage/searchParams.test.js
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: enhancement, user story, env

#3169 Activity log autorefresh e2e
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: test

#3185 Pin k3s version in CI workflow
  .github/workflows/ci.yaml
Labels: ci

#3186 Add info tooltip for metadata search
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
Labels: env

#3190 Use different clear icon
  assets/js/common/Input/Input.jsx
Labels: chore

#3179 Fix activity log e2e test
  test/e2e/cypress/e2e/activity_log.cy.js
Labels: test

#3183 Limit user access in activity log filters
  lib/trento/support/abilities_helper.ex
  lib/trento_web/channels/activity_log_channel.ex
  test/support/helpers/abilities_test_helper.ex
  test/trento/support/abilities_helper_test.exs
  test/trento_web/channels/activity_log_channel_test.exs
Labels: enhancement, env

#3195 Redact users in activity log
  lib/trento/activity_logging/policy.ex
  lib/trento_web/channels/activity_log_channel.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  lib/trento_web/controllers/v1/activity_log_json.ex
  test/support/factory.ex
  test/support/helpers/abilities_test_helper.ex
  test/trento/activity_logging/policy_test.exs
  test/trento_web/controllers/v1/activity_log_controller_test.exs
  test/trento_web/views/v1/activity_log_view_json_test.exs
Labels: enhancement, env

#3191 Show password toggle on login
  assets/js/pages/Login/Login.test.jsx
  assets/js/pages/Login/LoginForm.jsx
Labels: env

#3196 Order users query
  lib/trento/users.ex
  test/trento_web/controllers/v1/users_controller_test.exs
Labels: chore, test

#3198 Add a PR comment when a preview environment is created
  .github/scripts/pr_env.js
  .github/workflows/pr_env.yaml
  .github/workflows/pr_env_close.yaml
Labels: env

#3206 Hana Scale up cost opt checks in the trento console
  assets/js/common/ClusterInfoBox/ClusterInfoBox.jsx
  assets/js/common/ClusterInfoBox/ClusterInfoBox.test.jsx
  assets/js/lib/checks/env.js
  assets/js/lib/checks/env.test.js
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/ExecutionResults/ExecutionHeader.test.jsx
  assets/js/pages/ExecutionResults/ExecutionResults.stories.jsx
  assets/js/pages/ExecutionResults/TargetInfoBox.jsx
  lib/trento/clusters.ex
  lib/trento/infrastructure/checks/checks.ex
  lib/trento/infrastructure/checks/cluster_execution_env.ex
  test/trento/clusters_test.exs
Labels: enhancement, javascript, elixir

#3212 Cost opt e2e
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .photofinish.toml
  assets/js/pages/HostsList/HostsList.jsx
  assets/js/pages/HostsList/HostsList.test.jsx
  docker-compose.yaml
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
  test/fixtures/scenarios/hana-scale-up-cost-opt/2372b24f-3d7a-5d01-9b1a-a2c4c95c53d4_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/2372b24f-3d7a-5d01-9b1a-a2c4c95c53d4_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/2372b24f-3d7a-5d01-9b1a-a2c4c95c53d4_host_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/2372b24f-3d7a-5d01-9b1a-a2c4c95c53d4_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/2372b24f-3d7a-5d01-9b1a-a2c4c95c53d4_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/2372b24f-3d7a-5d01-9b1a-a2c4c95c53d4_subscription_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/fa7a5602-232b-5389-96a6-f5f5de6ff9a2_cloud_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/fa7a5602-232b-5389-96a6-f5f5de6ff9a2_ha_cluster_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/fa7a5602-232b-5389-96a6-f5f5de6ff9a2_host_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/fa7a5602-232b-5389-96a6-f5f5de6ff9a2_sap_system_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/fa7a5602-232b-5389-96a6-f5f5de6ff9a2_saptune_discovery.json
  test/fixtures/scenarios/hana-scale-up-cost-opt/fa7a5602-232b-5389-96a6-f5f5de6ff9a2_subscription_discovery.json
Labels: chore, test

#3208 Cypress E2E Tests parallelization
  .github/workflows/ci.yaml
  test/e2e/cypress/e2e/about.cy.js
  test/e2e/cypress/e2e/activity_log.cy.js
  test/e2e/cypress/e2e/clusters_overview.cy.js
  test/e2e/cypress/e2e/databases_overview.cy.js
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/e2e/hana_database_details.cy.js
  test/e2e/cypress/e2e/home.cy.js
  test/e2e/cypress/e2e/host_details.cy.js
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/e2e/cypress/e2e/sap_system_details.cy.js
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
  test/e2e/cypress/e2e/saptune_details.cy.js
  test/e2e/cypress/e2e/suse_manager_overviews.cy.js
  test/e2e/cypress/plugins/index.js
  test/e2e/cypress/support/commands.js
  test/e2e/package-lock.json
  test/e2e/package.json
Labels: enhancement, test

#3216 Upgrade tzdata to 1.1.2 to avoid error log
  mix.exs
  mix.lock
Labels: bug
