Repository trento-project/web, pull requests merged in 2025-03, with the labels that each got.

#3345 Add operations button host view
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/selectors/runningOperations.js
  assets/js/state/selectors/runningOperations.test.js
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/page_html/index.html.heex
Labels: enhancement, env

#3353 Rabbitmq explicit ssl support
  config/dev.exs
  config/test.exs
  config/wanda.exs
  container_fixtures/rabbitmq/certs/ca_certificate.pem
  container_fixtures/rabbitmq/certs/ca_key.pem
  container_fixtures/rabbitmq/certs/client_web.trento.local_certificate.pem
  container_fixtures/rabbitmq/certs/client_web.trento.local_key.pem
  container_fixtures/rabbitmq/certs/server_rabbit.trento.local_certificate.pem
  container_fixtures/rabbitmq/certs/server_rabbit.trento.local_key.pem
  container_fixtures/rabbitmq/rabbitmq.conf
  docker-compose.yaml
Labels: enhancement

#3344 Apply po pattern home tests
  test/e2e/cypress/e2e/home.cy.js
  test/e2e/cypress/pageObject/home-po.js
Labels: test

#3354 Log operation requested in activity log
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/activity_logging/severity_level.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
Labels: enhancement

#3358 Add modified check pill in checks execution results an detail
  assets/js/common/ModifiedCheckPill/ModifiedCheckPill.jsx
  assets/js/common/ModifiedCheckPill/ModifiedCheckPill.test.jsx
  assets/js/common/ModifiedCheckPill/index.js
  assets/js/lib/test-utils/factories/executions.js
  assets/js/pages/ChecksSelection/ChecksSelectionItem.jsx
  assets/js/pages/ExecutionResults/CheckResultDetail/ExpectedValues.jsx
  assets/js/pages/ExecutionResults/CheckResultDetail/ExpectedValues.stories.jsx
  assets/js/pages/ExecutionResults/ExecutionResults.jsx
  assets/js/pages/ExecutionResults/ExecutionResults.stories.jsx
Labels: enhancement

#3360 Operation completed activity log
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/activity_parser.ex
  lib/trento/activity_logging/parser/queue_event_parser.ex
  lib/trento/activity_logging/severity_level.ex
  lib/trento/infrastructure/operations/amqp/processor.ex
  lib/trento/infrastructure/operations/operations.ex
  test/support/factory.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/queue_event_parser_test.exs
  test/trento/infrastructure/operations/operations_test.exs
  test/trento/infrastructure/operations/processor_test.exs
Labels: enhancement, env

#3306 Activity log severity levels UI
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.jsx
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/ActivityLogOverview/index.js
  assets/js/common/ComposedFilter/ComposedFilter.jsx
  assets/js/common/ComposedFilter/ComposedFilter.test.jsx
  assets/js/common/Filter/Filter.jsx
  assets/js/lib/model/activityLog.js
  assets/js/pages/ActivityLogPage/ActivityLogPage.jsx
  assets/js/pages/ActivityLogPage/ActivityLogPage.test.jsx
  assets/js/pages/ActivityLogPage/searchParams.js
  assets/js/pages/Layout/Layout.jsx
  lib/trento/activity_log.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  test/e2e/cypress/e2e/activity_log.cy.js
  test/e2e/cypress/pageObject/activity-log-po.js
  test/trento/activity_log_test.exs
  test/trento_web/controllers/v1/activity_log_controller_test.exs
Labels: enhancement, javascript, env

#3363 Center severity icon in table cell
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
Labels: chore, env

#3361 Upgrade github actions runner ubuntu version
  .github/workflows/ci.yaml
  .github/workflows/e2e-flaky-tests-detection.yaml
  .github/workflows/pr_env.yaml
  .github/workflows/pr_env_close.yaml
Labels: chore, ci, env

#3371 Fix operation_completed activity log severity level
  lib/trento/activity_logging/severity_level.ex
Labels: chore

#3355 Fetch running operation on page load
  assets/js/lib/api/operations.js
  assets/js/lib/operations/index.js
  assets/js/lib/operations/operations.test.js
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/runningOperations.js
  assets/js/state/sagas/operations.js
  assets/js/state/sagas/operations.test.js
Labels: enhancement

#3352 Checks customization modal save
  assets/js/common/CheckCustomizationModal/CheckCustomizationInput.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.stories.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.test.jsx
  assets/js/lib/api/checks.js
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/js/pages/ChecksSelection/ChecksSelection.stories.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.test.jsx
  assets/js/pages/ChecksSelection/hooks.js
  assets/js/pages/ChecksSelection/hooks.test.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.jsx
Labels: enhancement, javascript

#3377 Add hostname field to activity log metadata for operation entries
  lib/trento/activity_logging/parser/metadata_enricher.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  test/trento/activity_logging/metadata_enricher_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
Labels: enhancement

#3368 Operation user authorization
  lib/trento/hosts/policy.ex
  lib/trento_web/controllers/v1/host_controller.ex
  priv/repo/migrations/20250306083321_add_saptune_solution_apply_abilities.exs
  test/trento/hosts/policy_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement

#3331 Add OperationForbiddenModal
  assets/js/common/OperationModals/OperationForbiddenModal.jsx
  assets/js/common/OperationModals/OperationForbiddenModal.stories.jsx
  assets/js/common/OperationModals/OperationForbiddenModal.test.jsx
  assets/js/common/OperationModals/SaptuneSolutionApplyModal.stories.jsx
  assets/js/common/OperationModals/index.js
Labels: enhancement

#3378 Review & fix users e2e tests flakiness
  .github/workflows/e2e-flaky-tests-detection.yaml
  test/e2e/cypress/e2e/users.cy.js
  test/e2e/cypress/pageObject/base_po.js
  test/e2e/cypress/pageObject/login_po.js
  test/e2e/cypress/pageObject/users_po.js
Labels: test

#3381 Use operation forbidden modal in host details
  assets/js/lib/operations/ForbiddenMessages.jsx
  assets/js/lib/operations/index.js
  assets/js/lib/operations/operations.test.js
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/state/runningOperations.js
  assets/js/state/runningOperations.test.js
  assets/js/state/sagas/operations.js
  assets/js/state/sagas/operations.test.js
Labels: enhancement

#3389 Apply page object pattern to hosts overview tests
  test/e2e/cypress/e2e/hosts_overview.cy.js
  test/e2e/cypress/e2e/users.cy.js
  test/e2e/cypress/pageObject/base_po.js
  test/e2e/cypress/pageObject/clusters_overview_po.js
  test/e2e/cypress/pageObject/host_details_po.js
  test/e2e/cypress/pageObject/hosts_overview_po.js
  test/e2e/cypress/pageObject/users_po.js
Labels: test

#3392 Apply page object pattern Sap System Details tests.
  test/e2e/cypress/e2e/sap_system_details.cy.js
  test/e2e/cypress/pageObject/sap_system_details_po.js
Labels: test

#3398 Fix database profile payload validation
  lib/trento/discovery/payloads/sap_system_discovery_payload.ex
  test/trento/discovery/policies/sap_system_policy_test.exs
Labels: bug

#3405 Use custom function to check if data is loaded
  test/e2e/cypress/pageObject/base_po.js
  test/e2e/cypress/pageObject/databases_overview_po.js
Labels: test, regression

#3397 Identify clustered sap instances
  lib/trento/clusters.ex
  lib/trento/clusters/cluster.ex
  lib/trento/clusters/commands/register_cluster_host.ex
  lib/trento/clusters/enums/sap_instance_resource_type.ex
  lib/trento/clusters/events/cluster_details_updated.ex
  lib/trento/clusters/events/cluster_registered.ex
  lib/trento/clusters/projections/cluster_projector.ex
  lib/trento/clusters/projections/cluster_read_model.ex
  lib/trento/clusters/value_objects/sap_instance.ex
  lib/trento/discovery.ex
  lib/trento/discovery/payloads/cluster/cluster_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento/discovery/policies/sap_system_policy.ex
  lib/trento/infrastructure/commanded/middleware/enrich_register_cluster_host.ex
  lib/trento/sap_systems/commands/register_application_instance.ex
  lib/trento/sap_systems/sap_system.ex
  lib/trento_web/controllers/v1/cluster_json.ex
  lib/trento_web/controllers/v2/cluster_json.ex
  priv/repo/migrations/20250318140549_add_sap_instances_cluster_read_model.exs
  test/support/factory.ex
  test/trento/clusters/cluster_test.exs
  test/trento/clusters/projections/cluster_projector_test.exs
  test/trento/clusters/value_objects/sap_instance_test.exs
  test/trento/clusters_test.exs
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento/discovery/policies/sap_system_policy_test.exs
  test/trento/infrastructure/commanded/middleware/enrich_register_cluster_host_test.exs
  test/trento/sap_systems/sap_system_test.exs
  test/trento_web/controllers/v2/cluster_controller_test.exs
Labels: env, regression

#3410 Expose cluster sap instances frontend
  assets/js/lib/model/clusters.js
  assets/js/lib/model/clusters.test.js
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/ClusterDetails/ClustersList.jsx
  assets/js/pages/ClusterDetails/ClustersList.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/pages/InstanceOverview/InstanceOverview.jsx
  assets/js/pages/InstanceOverview/InstanceOverview.test.jsx
  assets/js/pages/SapSystemsOverviewPage/SapSystemsOverview.test.jsx
  lib/trento_web/controllers/v1/cluster_json.ex
  lib/trento_web/controllers/v2/cluster_json.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  test/trento_web/views/v1/cluster_view_json_test.exs
  test/trento_web/views/v2/cluster_view_json_test.exs
Labels: enhancement, env

#3417 Fix Save button after saving a check in the checks customization modal
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
Labels: bug

#3408 Apply PageObject pattern sap systems overview e2e tests
  test/e2e/cypress/e2e/sap_systems_overview.cy.js
  test/e2e/cypress/fixtures/sap-systems-overview/available_sap_systems.js
  test/e2e/cypress/pageObject/sap_systems_overview_po.js
  test/e2e/cypress/support/commands.js
Labels: test
