Repository trento-project/web, pull requests merged in 2025-08, with the labels that each got.

#3696 Fix version usage in page_controller
  lib/trento_web/controllers/page_controller.ex
Labels: env

#3640 SMLM settings save/change correlation
  config/config.exs
  lib/trento/activity_log.ex
  lib/trento/activity_logging/correlations.ex
  lib/trento/activity_logging/correlations/unscoped_correlations.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/software_updates/discovery.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  mix.exs
  mix.lock
  test/support/test_correlations.ex
  test/test_helper.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/heartbeats_test.exs
  test/trento/infrastructure/commanded/event_handlers/software_updates_discovery_event_handler_test.exs
  test/trento/settings_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
Labels: enhancement, elixir

#3683 Database start/stop operations user policies
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.jsx
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.test.jsx
  lib/trento/databases/policy.ex
  lib/trento_web/controllers/v1/database_controller.ex
  priv/repo/migrations/20250729131054_add_database_start_stop_abilities.exs
  test/trento/databases/policy_test.exs
  test/trento_web/controllers/v1/database_controller_test.exs
Labels: enhancement

#3697 Database start/stop activity logging
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/activity_logging/severity_level.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
Labels: enhancement

#3709 Handle null node attributes nodes list
  lib/trento/discovery/payloads/cluster/crmmon_discovery_payload.ex
  test/trento/discovery/policies/cluster_policy_test.exs
Labels: bug, env

#3713 Fix flaky test - Link to known clusters in SAP Systems Overview
  test/e2e/cypress/pageObject/base_po.js
  test/e2e/cypress/pageObject/sap_systems_overview_po.js
Labels: test

#3715 Refactors dispatch functions and their usage
  lib/trento/databases.ex
  lib/trento/heartbeats.ex
  lib/trento/hosts.ex
  lib/trento/sap_systems.ex
  lib/trento/software_updates/discovery.ex
  lib/trento/support/commanded_utils.ex
  test/trento/support/commanded_utils_test.exs
Labels: tech debt, elixir

#3719 Database start/stop policy
  lib/trento/operations/database_instance_policy.ex
  lib/trento/operations/database_policy.ex
  lib/trento_web/controllers/v1/database_controller.ex
  test/trento/operations/database_policy_test.exs
  test/trento_web/controllers/v1/database_controller_test.exs
Labels: enhancement, env

#3750 Fix flaky test activity log start refresh ticker
  test/e2e/cypress/e2e/activity_log.cy.js
  test/e2e/cypress/pageObject/activity_log_po.js
Labels: test
