Repository trento-project/web, pull requests merged in 2025-01, with the labels that each got.

#3215 Add job for flaky e2e tests detection
  .github/workflows/e2e-flaky-tests-detection.yaml
Labels: enhancement, github_actions, test

#3210 Add hana scale up scenario as selection in checks catalog
  assets/js/common/Select/Select.jsx
  assets/js/lib/model/checks.js
  assets/js/lib/model/clusters.js
  assets/js/pages/ChecksCatalog/ChecksCatalog.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalog.test.jsx
  assets/js/pages/ChecksCatalog/ChecksCatalogPage.jsx
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement, javascript, env

#3217 Update community container image to use fixed versions from leap15.6
  Dockerfile
  packaging/suse/container/Dockerfile
Labels: bug, env

#3223 Refactor activity log settings
  lib/trento/activity_log.ex
  lib/trento/release.ex
  lib/trento/settings.ex
  lib/trento/settings/activity_log_settings.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  priv/repo/seeds.exs
  test/support/factory.ex
  test/trento/activity_log_test.exs
  test/trento/release_test.exs
  test/trento/settings_test.exs
Labels: tech debt

#3232 change base image and update dependencies
  Dockerfile
  packaging/suse/container/Dockerfile
Labels: bug, env

#3219 Add page object structure for User creation tests
  test/e2e/cypress/e2e/users.cy.js
  test/e2e/cypress/pageObject/base-po.js
  test/e2e/cypress/pageObject/dashboard-po.js
  test/e2e/cypress/pageObject/login-po.js
  test/e2e/cypress/pageObject/users-po.js
Labels: test

#3222 Activity log severity levels
  lib/trento/activity_log.ex
  lib/trento/activity_logging/activity_log.ex
  lib/trento/activity_logging/parser/activity_parser.ex
  lib/trento/activity_logging/severity_level.ex
  priv/repo/migrations/20250109130009_add_activity_log_severity_field.exs
  test/support/factory.ex
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/severity_level_test.exs
Labels: enhancement, elixir

#3240 Expose abilities as jwt claims
  lib/trento_web/plugs/app_jwt_auth_plug.ex
  test/support/factory.ex
  test/trento/activity_logging/activity_logger_test.exs
  test/trento_web/controllers/session_controller_test.exs
  test/trento_web/plugs/app_jwt_auth_plug_test.exs
Labels: enhancement

#3229 Fix selected cluster type ui in Checks catalog view
  assets/js/common/Select/Select.jsx
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: bug, javascript, env

#3247 Refactor checks_catalog ui test
  test/e2e/cypress/e2e/checks_catalog.cy.js
Labels: enhancement, javascript

#3246 Update gen_rmq to cdimonaco/gen_rmq version 5
  mix.exs
  mix.lock
Labels: dependencies

#3248 Apply page object pattern to 'about' and 'check catalog' tests
  test/e2e/cypress/e2e/about.cy.js
  test/e2e/cypress/e2e/checks_catalog.cy.js
  test/e2e/cypress/pageObject/about-po.js
  test/e2e/cypress/pageObject/base-po.js
  test/e2e/cypress/pageObject/checks-catalog-po.js
  test/e2e/cypress/pageObject/login-po.js
  test/e2e/cypress/pageObject/users-po.js
Labels: test

#3242 Adds Encapsulation for Dashboard Page
  assets/js/common/HealthIcon/HealthIcon.jsx
  assets/js/common/HealthIcon/HealthIcon.stories.jsx
  assets/js/common/Table/Table.jsx
  assets/js/pages/HealthSummary/HomeHealthSummary.jsx
Labels: enhancement, chore, ux, env

#3254 Fix Jest warnings on FE tests
  assets/js/common/NotificationBox/NotificationBox.test.jsx
  assets/js/pages/ChecksCatalog/CatalogContainer.test.jsx
  assets/js/pages/ExecutionResults/CheckResultDetail/CheckDetailHeader.test.jsx
  assets/js/pages/ExecutionResults/CheckResultOutline.test.jsx
  assets/js/pages/ExecutionResults/TargetResult.test.jsx
  assets/js/pages/Guard/Guard.test.jsx
Labels: test

#3256 Add check customization call to action in checks selection
  assets/js/lib/test-utils/factories/index.js
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.test.jsx
Labels: enhancement, user story

#3259 Apply PageObject pattern 'activity log' e2e tests
  test/e2e/cypress/e2e/activity_log.cy.js
  test/e2e/cypress/pageObject/activity-log-po.js
  test/e2e/cypress/pageObject/base-po.js
Labels: wip, test
