Repository trento-project/web, pull requests merged in 2025-05, with the labels that each got.

#3476 Add checks execution with custom values test e2e
  assets/js/pages/ChecksSelection/ChecksSelectionItem.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.test.jsx
  test/e2e/cypress/e2e/checks_customization.cy.js
  test/e2e/cypress/pageObject/base_po.js
  test/e2e/cypress/pageObject/checks_customization_po.js
  test/e2e/cypress/pageObject/clusters_overview_po.js
Labels: javascript, test

#3487 Add cluster maintenance change modal
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.jsx
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.stories.jsx
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.test.jsx
  assets/js/common/OperationModals/OperationForbiddenModal.stories.jsx
  assets/js/common/OperationModals/SaptuneSolutionApplyModal.stories.jsx
Labels: enhancement

#3490 Bugfix for web as it fails to start when no IPV6 is available
  config/runtime.exs
Labels: bug, elixir

#3489 SMTP allows talking to unauthenticated servers
  config/runtime.exs
  lib/trento/infrastructure/alerting/emails/templates/api_key_expiration.html.eex
  lib/trento/infrastructure/alerting/emails/templates/critical.html.eex
Labels: enhancement, elixir, env

#3492 add .editorconfig
  .editorconfig
Labels: chore, dx

#3494 Remove legacy catalog list coming from `runner` implementation
  priv/data/catalog.json
Labels: chore, removal

#3499 Improve operations mapping
  lib/trento/activity_logging/parser/metadata_enricher.ex
  lib/trento/hosts.ex
  lib/trento/infrastructure/operations/operations.ex
  lib/trento/operations/host_operations.ex
  lib/trento_web/controllers/v1/host_controller.ex
  test/trento/infrastructure/operations/operations_test.exs
Labels: enhancement

#3496 Automate changelog generation
  .github/release_drafter.yaml
  .github/workflows/ci.yaml
  .github/workflows/post_release.yaml
  .github/workflows/pre_release.yaml
Labels: ci, dx, github_actions

#3502 Alerting settings from env coerced correcly
  config/runtime.exs
  lib/trento/settings.ex
  test/trento/settings_test.exs
Labels: bug, elixir

#3503 Add menu position to operations button
  assets/js/common/OperationsButton/OperationsButton.jsx
  assets/js/common/OperationsButton/OperationsButton.stories.jsx
Labels: chore

#3504 Reset modal options on cancel
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.jsx
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.test.jsx
Labels: enhancement

#3509 Version bump automation
  .github/workflows/build-containers.yaml
  .github/workflows/ci.yaml
  .github/workflows/obs.yaml
  .github/workflows/post_release.yaml
  .github/workflows/pr_env.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  Dockerfile
  VERSION
  hack/get_version_from_git.sh
  hack/gh_release_to_obs_changeset.py
  mix.exs
  test/e2e/cypress/pageObject/about_po.js
  test/e2e/package.json
Labels: tech debt, ci, dx, github_actions, env

#3482 Expose cluster resource parent api
  lib/trento_web/controllers/v2/cluster_json.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  test/trento_web/views/v2/cluster_view_json_test.exs
Labels: enhancement

#3516 More ci fixes
  .github/workflows/build-containers.yaml
  .github/workflows/ci.yaml
  .github/workflows/pr_env.yaml
  .github/workflows/release.yaml
Labels: ci, github_actions, env

#3488 Add the ability to request a saptune solution change
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.jsx
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.test.jsx
  assets/js/common/OperationModals/SaptuneSolutionApplyModal.test.jsx
  assets/js/common/OperationModals/SaptuneSolutionOperationModal.jsx
  assets/js/common/OperationModals/SaptuneSolutionOperationModal.stories.jsx
  assets/js/common/OperationModals/SaptuneSolutionOperationModal.test.jsx
  assets/js/common/OperationModals/index.js
  assets/js/common/OperationsButton/OperationsButton.jsx
  assets/js/lib/operations/ForbiddenMessages.jsx
  assets/js/lib/operations/index.js
  assets/js/lib/operations/operations.test.js
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/HostDetailsPage/HostDetails.stories.jsx
  assets/js/pages/HostDetailsPage/HostDetails.test.jsx
  lib/trento/activity_logging/parser/metadata_enricher.ex
  lib/trento/hosts.ex
  lib/trento/hosts/policy.ex
  lib/trento/infrastructure/operations/amqp/processor.ex
  lib/trento/infrastructure/operations/operations.ex
  lib/trento/operations/enums/host_operations.ex
  lib/trento/operations/host_policy.ex
  lib/trento_web/controllers/v1/host_controller.ex
  priv/repo/migrations/20250507155725_add_saptune_solution_change_abilities.exs
  test/trento/activity_logging/metadata_enricher_test.exs
  test/trento/hosts/policy_test.exs
  test/trento/hosts_test.exs
  test/trento/infrastructure/operations/operations_test.exs
  test/trento/infrastructure/operations/processor_test.exs
  test/trento/operations/host_policy_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement, user story, elixir

#3517 Table top margin
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/PatchList/PatchList.jsx
  assets/js/common/Table/Table.jsx
  assets/js/common/UpgradablePackagesList/UpgradablePackagesList.jsx
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/AttributesDetails.jsx
  assets/js/pages/ExecutionResults/ExecutionResults.jsx
  assets/js/pages/HostDetailsPage/HostDetails.jsx
  assets/js/pages/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/pages/Users/Users.jsx
Labels: ux, env

#3518 Add CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: enhancement, dependencies

#3521 Add fixed witdh to relevant patches synopsis
  assets/js/common/PatchList/PatchList.jsx
  assets/js/common/Table/Table.jsx
  assets/js/pages/HostRelevantPatches/HostRelevantPatchesPage.stories.jsx
Labels: enhancement, ux

#3528 Add `forwardRef` to button component
  assets/js/common/Button/Button.jsx
  assets/js/common/Tooltip/Tooltip.jsx
Labels: enhancement

#3514 Update host saptune status on SAP instances de/registration
  lib/trento/databases.ex
  lib/trento/event_handlers_supervisor.ex
  lib/trento/hosts/projections/host_read_model.ex
  lib/trento/infrastructure/commanded/event_handlers/saptune_status_update_event_handler.ex
  lib/trento/sap_systems.ex
  test/trento/databases_test.exs
  test/trento/hosts/projections/host_projector_test.exs
  test/trento/infrastructure/commanded/event_handlers/saptune_status_update_event_handler_test.exs
  test/trento/sap_systems_test.exs
Labels: enhancement, env

#3529 Cluster maintenance operation frontend
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.jsx
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.test.jsx
  assets/js/common/OperationModals/index.js
  assets/js/lib/api/operations.js
  assets/js/lib/operations/index.js
  assets/js/lib/operations/operations.test.js
  assets/js/pages/ClusterDetails/ClusterDetails.jsx
  assets/js/pages/ClusterDetails/ClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/state/sagas/operations.js
  assets/js/state/sagas/operations.test.js
Labels: enhancement

#3538 Request cluster discovery on operation complete event
  lib/trento/discovery.ex
  lib/trento/infrastructure/operations/amqp/processor.ex
  test/trento/discovery_test.exs
  test/trento/infrastructure/operations/processor_test.exs
Labels: enhancement

#3535 Harden saptune operation policy
  lib/trento/infrastructure/commanded/event_handlers/saptune_status_update_event_handler.ex
  lib/trento/operations/host_policy.ex
  lib/trento_web/openapi/v1/schema/saptune_status.ex
  test/support/factory.ex
  test/trento/hosts/host_test.exs
  test/trento/hosts/projections/host_projector_test.exs
  test/trento/infrastructure/commanded/event_handlers/saptune_status_update_event_handler_test.exs
  test/trento/operations/host_policy_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement

#3537 Fix start/stop AgentHeartbeat logic in before/after Each hooks in e2e tests
  .github/workflows/e2e-flaky-tests-detection.yaml
  test/e2e/cypress/e2e/hosts_overview.cy.js
Labels: test
