Repository trento-project/web, pull requests merged in 2025-09, with the labels that each got.

#3733 Prepare documentation for auto build process
  README.adoc
  guides/Alerting/alerting.adoc
  guides/Authentication/jwt-specification.adoc
  guides/Authentication/spa-flow.adoc
  guides/Development/environment-variables.adoc
  guides/Development/hack-on-the-trento.adoc
  guides/Integration/oidc.adoc
  guides/Monitoring/monitoring.adoc
Labels: documentation

#3701 Analytics Eula Modal
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/AnalyticsEula/AnalyticsEula.jsx
  assets/js/pages/AnalyticsEula/AnalyticsEulaModal.jsx
  assets/js/pages/AnalyticsEula/AnalyticsEulaModal.stories.jsx
  assets/js/pages/AnalyticsEula/AnalyticsEulaModal.test.jsx
  assets/js/pages/AnalyticsEula/index.js
  assets/js/pages/Layout/Layout.jsx
  assets/js/state/sagas/user.js
  assets/js/state/user.js
  assets/js/state/user.test.js
  lib/trento/users.ex
  lib/trento/users/user.ex
  lib/trento_web/controllers/v1/profile_json.ex
  lib/trento_web/openapi/v1/schema/user.ex
  priv/repo/migrations/20250728090509_add_analytics_eula_accepted_at_to_users.exs
  test/support/factory.ex
  test/trento/users/user_test.exs
  test/trento/users_test.exs
  test/trento_web/views/v1/profile_view_json_test.exs
Labels: enhancement, javascript, elixir, env

#3753 Fix failure rate calculation e2e flaky tests
  .github/workflows/e2e-flaky-tests-detection.yaml
Labels: test

#3760 [TRNT-3845] Run linters on the API spec and fix the errors (controllers: missing params)
  lib/trento_web/controllers/session_controller.ex
  lib/trento_web/controllers/v1/prometheus_controller.ex
Labels: enhancement

#3761 [TRNT-3845] Run linters on the API spec and fix the errors (controllers: improve schema)
  lib/trento_web/openapi/v1/schema/credentials.ex
Labels: enhancement

#3758 [TRNT-3845] Run linters on the API spec and fix the errors (controllers: type to schema)
  lib/trento_web/controllers/v1/chart_controller.ex
  lib/trento_web/controllers/v1/cluster_controller.ex
  lib/trento_web/controllers/v1/database_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/controllers/v1/sap_system_controller.ex
  lib/trento_web/controllers/v1/suse_manager_controller.ex
  lib/trento_web/controllers/v1/tags_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
Labels: bug, enhancement

#3757 [TRNT-3845] Run linters on the API spec and fix the errors (controllers, non-breaking changes)
  lib/trento/hosts/host.ex
  lib/trento/infrastructure/software_updates/adapter/mock_suma.ex
  lib/trento/infrastructure/software_updates/adapter/suma_http_executor.ex
  lib/trento/infrastructure/software_updates/auth/gen.ex
  lib/trento/infrastructure/software_updates/auth/state.ex
  lib/trento/infrastructure/software_updates/auth/suma_auth.ex
  lib/trento/infrastructure/software_updates/suma.ex
  lib/trento/infrastructure/software_updates/suma_api.ex
  lib/trento/settings.ex
  lib/trento/settings/suse_manager_settings.ex
  lib/trento_web/controllers/health_controller.ex
  lib/trento_web/controllers/session_controller.ex
  lib/trento_web/controllers/v1/ability_controller.ex
  lib/trento_web/controllers/v1/about_controller.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  lib/trento_web/controllers/v1/chart_controller.ex
  lib/trento_web/controllers/v1/cluster_controller.ex
  lib/trento_web/controllers/v1/database_controller.ex
  lib/trento_web/controllers/v1/discovery_controller.ex
  lib/trento_web/controllers/v1/health_overview_controller.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/controllers/v1/profile_controller.ex
  lib/trento_web/controllers/v1/prometheus_controller.ex
  lib/trento_web/controllers/v1/sap_system_controller.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/controllers/v1/suse_manager_controller.ex
  lib/trento_web/controllers/v1/tags_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/controllers/v2/cluster_controller.ex
  lib/trento_web/openapi/v1/schema/credentials.ex
  lib/trento_web/openapi/v1/schema/database_operation_params.ex
  lib/trento_web/openapi/v1/schema/platform.ex
Labels: enhancement

#3763 [TRNT-3845] Run linters on the API spec and fix the errors (controllers: properties)
  lib/trento_web/controllers/v1/activity_log_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/openapi/v1/schema/cluster.ex
  lib/trento_web/openapi/v1/schema/discovery_event.ex
  lib/trento_web/openapi/v1/schema/provider.ex
  lib/trento_web/openapi/v1/schema/user.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
Labels: enhancement

#3745 Retrieve user Personal Access Tokens
  lib/trento/users.ex
  lib/trento_web/controllers/v1/personal_access_tokens_json.ex
  lib/trento_web/controllers/v1/profile_json.ex
  lib/trento_web/controllers/v1/users_json.ex
  lib/trento_web/openapi/v1/schema/personal_access_token.ex
  lib/trento_web/openapi/v1/schema/user.ex
  test/trento/users_test.exs
  test/trento_web/views/v1/personal_access_tokens_view_json_test.exs
  test/trento_web/views/v1/profile_view_json_test.exs
  test/trento_web/views/v1/users_view_json_test.exs
Labels: enhancement

#3749 Revoke Personal Access Tokens
  lib/trento/personal_access_tokens.ex
  lib/trento_web/controllers/v1/personal_access_tokens_controller.ex
  lib/trento_web/router.ex
  test/trento/personal_access_tokens_test.exs
  test/trento_web/controllers/v1/personal_acces_tokens_controller_test.exs
Labels: enhancement

#3772 Update trento docs link in layout
  assets/js/pages/Layout/Layout.jsx
Labels: documentation, env

#3784 Fix Flaky test - Activity log should reset pagination when filters changed
  test/e2e/cypress/e2e/activity_log.cy.js
  test/e2e/cypress/pageObject/activity_log_po.js
Labels: test

#3790 UI Personal access tokens modals
  assets/js/common/ApiKeySettingsModal/ApiKeySettingsModal.jsx
  assets/js/common/PersonalAccessTokens/DeleteTokenModal.jsx
  assets/js/common/PersonalAccessTokens/DeleteTokenModal.stories.jsx
  assets/js/common/PersonalAccessTokens/DeleteTokenModal.test.jsx
  assets/js/common/PersonalAccessTokens/GenerateTokenModal.jsx
  assets/js/common/PersonalAccessTokens/GenerateTokenModal.stories.jsx
  assets/js/common/PersonalAccessTokens/GenerateTokenModal.test.jsx
  assets/js/common/PersonalAccessTokens/NewTokenModal.jsx
  assets/js/common/PersonalAccessTokens/NewTokenModal.stories.jsx
  assets/js/common/PersonalAccessTokens/NewTokenModal.test.jsx
  assets/js/lib/date/index.js
Labels: enhancement

#3764 [TRNT-3845] Run linters on the API spec and fix the errors (controllers: routes)
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/controllers/v1/tags_controller.ex
  lib/trento_web/controllers/v1/users_controller.ex
  lib/trento_web/router.ex
  test/trento/activity_logging/activity_catalog_test.exs
Labels: enhancement

#3793 Personal access tokens profile frontend
  assets/js/common/PersonalAccessTokens/PersonalAccessTokens.jsx
  assets/js/common/PersonalAccessTokens/PersonalAccessTokens.stories.jsx
  assets/js/common/PersonalAccessTokens/PersonalAccessTokens.test.jsx
  assets/js/common/PersonalAccessTokens/index.js
  assets/js/lib/api/users.js
  assets/js/lib/test-utils/factories/users.js
  assets/js/pages/Profile/ProfilePage.jsx
Labels: enhancement, env

#3803 Remove `canvas` from prod deps in ./assets
  assets/package-lock.json
  assets/package.json
Labels: dependencies, javascript
