Repository trento-project/web, pull requests merged in 2025-07, with the labels that each got.

#3600 Correlation of operations activity log entries
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/activity_logging/parser/queue_event_parser.ex
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/activity_logging/queue_event_parser_test.exs
Labels: enhancement, elixir, env

#3605 Expose cluster resources
  lib/trento/clusters.ex
  lib/trento/clusters/value_objects/ascs_ers_cluster_details.ex
  lib/trento/clusters/value_objects/ascs_ers_cluster_node.ex
  lib/trento/clusters/value_objects/cluster_resource.ex
  lib/trento/clusters/value_objects/hana_cluster_details.ex
  lib/trento/clusters/value_objects/hana_cluster_node.ex
  lib/trento/discovery/payloads/cluster/cib_discovery_payload.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento/operations/application_instance_policy.ex
  lib/trento/operations/database_instance_policy.ex
  lib/trento_web/controllers/v1/cluster_json.ex
  lib/trento_web/controllers/v2/cluster_json.ex
  lib/trento_web/openapi/v2/schema/cluster.ex
  test/support/factory.ex
  test/trento/clusters_test.exs
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento/operations/application_instance_policy_test.exs
  test/trento/operations/cluster_policy_test.exs
  test/trento/operations/database_instance_policy_test.exs
  test/trento/operations/host_policy_test.exs
  test/trento_web/views/v1/cluster_view_json_test.exs
  test/trento_web/views/v2/cluster_view_json_test.exs
Labels: enhancement

#3608 Resources table frontend
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.jsx
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.test.jsx
  assets/js/common/Table/CollapsibleTableRow.jsx
  assets/js/common/Table/Table.jsx
  assets/js/common/Table/Table.test.jsx
  assets/js/lib/test-utils/data/clusters.js
  assets/js/lib/test-utils/factories/clusters.js
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.jsx
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/AttributesDetails.jsx
  assets/js/pages/ClusterDetails/AttributesDetails.test.jsx
  assets/js/pages/ClusterDetails/ClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.stories.jsx
  assets/js/pages/ClusterDetails/HanaClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.test.jsx
  assets/js/pages/ClusterDetails/Resources.jsx
  assets/js/pages/ClusterDetails/Resources.test.jsx
  assets/js/pages/ClusterDetails/StoppedResources.jsx
  assets/js/pages/ClusterDetails/StoppedResources.test.jsx
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/fixtures/hana-cluster-details/available_hana_cluster.js
  test/e2e/cypress/pageObject/hana_cluster_details_po.js
Labels: enhancement, env

#3615 Cluster resource operations
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.jsx
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.stories.jsx
  assets/js/common/OperationModals/ClusterMaintenanceChangeModal.test.jsx
  assets/js/common/OperationModals/SimpleAcceptanceOperationModal.jsx
  assets/js/common/OperationModals/SimpleAcceptanceOperationModal.stories.jsx
  assets/js/common/OperationModals/SimpleAcceptanceOperationModal.test.jsx
  assets/js/common/OperationModals/index.js
  assets/js/pages/ClusterDetails/AscsErsClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/ClusterDetails.jsx
  assets/js/pages/ClusterDetails/ClusterDetails.test.jsx
  assets/js/pages/ClusterDetails/ClusterHostOperations.test.jsx
  assets/js/pages/ClusterDetails/HanaClusterSite.test.jsx
  assets/js/pages/ClusterDetails/Resources.jsx
  assets/js/pages/ClusterDetails/Resources.test.jsx
  assets/js/pages/ClusterDetails/clusterOperations.js
Labels: enhancement, env

#3606 Correlation of heartbeat entries after API key regeneration
  lib/trento/activity_log.ex
  lib/trento/activity_logging/correlations.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/application.ex
  lib/trento/heartbeats.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  mix.exs
  mix.lock
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/heartbeats_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
Labels: enhancement, elixir, env

#3652 Start/stop SAP system user policy
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.jsx
  assets/js/common/AbilitiesMultiSelect/AbilitiesMultiSelect.test.jsx
  lib/trento/sap_systems/policy.ex
  priv/repo/migrations/20250717085841_add_sap_system_start_stop_abilities.exs
  test/trento/sap_systems/policy_test.exs
  test/trento_web/controllers/v1/sap_system_controller_test.exs
Labels: enhancement

#3653 Fix Flaky test in activity log page when selecting every different refresh rate.
  test/e2e/cypress/pageObject/activity_log_po.js
  test/e2e/cypress/pageObject/base_po.js
Labels: test

#3659 Rescue on discovery exceptions
  lib/trento/discovery.ex
  lib/trento_web/controllers/fallback_controller.ex
  test/trento/discovery_test.exs
  test/trento_web/controllers/v1/discovery_controller_test.exs
Labels: elixir

#3669 Add system replication details
  assets/js/pages/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/pages/SapSystemDetails/GenericSystemDetails.test.jsx
  test/e2e/cypress/e2e/hana_database_details.cy.js
  test/e2e/cypress/fixtures/hana-database-details/selected_database.js
  test/e2e/cypress/pageObject/hana_database_details_po.js
Labels: enhancement, env

#3625 Analytics Add Version Code
  assets/js/lib/analytics/pageview.js
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/page_html/index.html.heex
Labels: enhancement
