Repository trento-project/web, pull requests merged in 2025-04, with the labels that each got.

#3422 Handle unmounted clustered sap instance
  lib/trento/clusters/value_objects/sap_instance.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento/discovery/policies/sap_system_policy.ex
  test/fixtures/discovery/ha_cluster_discovery_ascs_ers_simple_mount.json
  test/fixtures/discovery/ha_cluster_discovery_ascs_ers_unmounted.json
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento/discovery/policies/sap_system_policy_test.exs
Labels: enhancement

#3424 Log checks customizations activities
  assets/js/lib/model/activityLog.js
  assets/js/lib/model/activityLog.test.js
  config/config.exs
  config/dev.exs
  config/runtime.exs
  config/test.exs
  config/wanda.exs
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/metadata_enricher.ex
  lib/trento/activity_logging/parser/queue_event_parser.ex
  lib/trento/activity_logging/severity_level.ex
  lib/trento/application.ex
  lib/trento/infrastructure/catalog/amqp/consumer.ex
  lib/trento/infrastructure/catalog/amqp/processor.ex
  mix.exs
  mix.lock
  test/support/factory.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/metadata_enricher_test.exs
  test/trento/activity_logging/queue_event_parser_test.exs
  test/trento/infrastructure/catalog/processor_test.exs
Labels: enhancement, user story

#3426 Fix year range
  assets/js/pages/Layout/Layout.jsx
Labels: chore

#3372 Backend for User Analytics Settings
  lib/trento/users.ex
  lib/trento/users/user.ex
  lib/trento_web/controllers/v1/profile_json.ex
  lib/trento_web/controllers/v1/users_json.ex
  lib/trento_web/openapi/v1/schema/user.ex
  priv/repo/migrations/20250327095737_add_analytics_enabled_at_to_users.exs
  test/support/factory.ex
  test/trento/users/user_test.exs
  test/trento/users_test.exs
  test/trento_web/views/v1/profile_view_json_test.exs
  test/trento_web/views/v1/users_view_json_test.exs
Labels: enhancement, ux, elixir, proposal

#3428 Apply PO Pattern to Saptune-SSO-SUMA test suites
  test/e2e/cypress/e2e/saptune_details.cy.js
  test/e2e/cypress/e2e/sso_integration.cy.js
  test/e2e/cypress/e2e/suse_manager_overviews.cy.js
  test/e2e/cypress/pageObject/base_po.js
  test/e2e/cypress/pageObject/dashboard_po.js
  test/e2e/cypress/pageObject/host_details_po.js
  test/e2e/cypress/pageObject/login_po.js
  test/e2e/cypress/pageObject/saptune_details_po.js
  test/e2e/cypress/pageObject/users_po.js
Labels: test

#3439 Minor adjustments to check customization
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.test.jsx
  assets/js/common/CheckableWarningMessage/CheckableWarningMessage.stories.jsx
  lib/trento/activity_logging/severity_level.ex
Labels: chore

#3441 Differentiate checks execution requested label
  assets/js/lib/model/activityLog.js
Labels: chore

#3440 Log user coming from messages
  lib/trento/activity_logging/parser/activity_parser.ex
  lib/trento/activity_logging/parser/metadata_enricher.ex
  lib/trento/activity_logging/parser/queue_event_parser.ex
  lib/trento/infrastructure/catalog/amqp/processor.ex
  lib/trento/users/user.ex
  mix.exs
  mix.lock
  test/trento/activity_logging/queue_event_parser_test.exs
  test/trento/infrastructure/catalog/processor_test.exs
Labels: enhancement

#3445 Implements newly defined severity level conditions
  lib/trento/activity_logging/severity_level.ex
Labels: enhancement, elixir

#3442 Apply PO pattern to Settings test suite
  test/e2e/cypress/e2e/settings.cy.js
  test/e2e/cypress/e2e/users.cy.js
  test/e2e/cypress/pageObject/activity_log_po.js
  test/e2e/cypress/pageObject/base_po.js
  test/e2e/cypress/pageObject/checks_catalog_po.js
  test/e2e/cypress/pageObject/clusters_overview_po.js
  test/e2e/cypress/pageObject/databases_overview_po.js
  test/e2e/cypress/pageObject/hana_cluster_details_po.js
  test/e2e/cypress/pageObject/host_details_po.js
  test/e2e/cypress/pageObject/hosts_overview_po.js
  test/e2e/cypress/pageObject/sap_system_details_po.js
  test/e2e/cypress/pageObject/sap_systems_overview_po.js
  test/e2e/cypress/pageObject/settings_po.js
  test/e2e/cypress/pageObject/users_po.js
  test/e2e/cypress/support/commands.js
  test/e2e/cypress/support/e2e.js
Labels: test

#3447 Deduplicate targets for ascs cluster checks executions
  lib/trento/clusters.ex
  test/support/factory.ex
  test/trento/clusters/value_objects/sap_instance_test.exs
  test/trento/clusters_test.exs
Labels: bug, env

#3451 Use rolling checks image in demo
  .github/workflows/ci.yaml
Labels: ci

#3450 Log checks selected as connection activity
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/activity_logging/severity_level.ex
  test/support/commanded/commanded_case.ex
  test/support/factory.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/event_parser_test.exs
  test/trento/activity_logging/metadata_enricher_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
Labels: enhancement, env

#3443 Request saptune discovery when saptune solution apply operation is completed
  config/config.exs
  config/dev.exs
  config/runtime.exs
  config/test.exs
  config/wanda.exs
  lib/trento/application.ex
  lib/trento/discovery.ex
  lib/trento/infrastructure/discovery/amqp/publisher.ex
  lib/trento/infrastructure/operations/amqp/processor.ex
  mix.exs
  mix.lock
  test/trento/discovery_test.exs
  test/trento/infrastructure/operations/processor_test.exs
Labels: enhancement, env

#3463 Fix references to activity log settings
  lib/trento/settings/policy.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  test/trento/settings/policy_test.exs
Labels: bug, env

#3460 Checks customization e2e
  test/e2e/cypress.config.js
  test/e2e/cypress/e2e/checks_customization.cy.js
  test/e2e/cypress/pageObject/checks_customization_po.js
Labels: javascript, test

#3479 Fix wanda initdb permissions
  container_fixtures/postgres/init_wanda_db.sh
Labels: chore

#3462 Alerting Settings web API
  lib/trento/settings/policy.ex
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/controllers/v1/settings_controller.ex
  lib/trento_web/controllers/v1/settings_json.ex
  lib/trento_web/openapi/v1/schema/platform.ex
  lib/trento_web/router.ex
  test/trento/settings/policy_test.exs
  test/trento_web/controllers/v1/settings_controller_test.exs
  test/trento_web/views/v1/settings_view_json_test.exs
Labels: enhancement, elixir
