Repository trento-project/web, pull requests merged in 2025-02, with the labels that each got.

#3271 Remaps specific activity log type unconditionally to warning
  lib/trento/activity_logging/severity_level.ex
Labels: bug, elixir

#3272 Fix discovery dispatch accumulating errors
  lib/trento/discovery.ex
  test/trento/discovery_test.exs
Labels: bug

#3273 Fix cluster json view adapt_v1 function
  lib/trento/support/struct_helper.ex
  lib/trento_web/controllers/v1/cluster_json.ex
  lib/trento_web/controllers/v2/cluster_json.ex
  test/trento/clusters/projections/cluster_projector_test.exs
  test/trento/support/struct_helper_test.exs
  test/trento_web/views/v1/cluster_view_json_test.exs
  test/trento_web/views/v2/cluster_view_json_test.exs
Labels: bug

#3275 Use embeds software updates
  assets/js/state/sagas/softwareUpdates.js
  lib/trento/software_updates/discovery.ex
  lib/trento/software_updates/discovery/discovery_result.ex
  lib/trento_web/openapi/v1/schema/available_software_updates.ex
  test/support/factory.ex
  test/trento/infrastructure/software_updates/suma_test.exs
  test/trento/software_updates/discovery_test.exs
  test/trento/software_updates_test.exs
  test/trento_web/views/v1/suse_manager_view_json_test.exs
Labels: bug, enhancement, env

#3274 Add modified pill for customized checks
  assets/js/lib/test-utils/factories/checks.js
  assets/js/lib/test-utils/factories/index.js
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/js/pages/ChecksSelection/ChecksSelection.stories.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.test.jsx
Labels: enhancement

#3266 Apply PageObject pattern Clusters Overview tests.
  test/e2e/cypress/e2e/clusters_overview.cy.js
  test/e2e/cypress/pageObject/about-po.js
  test/e2e/cypress/pageObject/base-po.js
  test/e2e/cypress/pageObject/checks-catalog-po.js
  test/e2e/cypress/pageObject/clusters-overview-po.js
  test/e2e/cypress/support/commands.js
Labels: test

#3276 Add parent cluster resource
  lib/trento/clusters/value_objects/cluster_resource.ex
  lib/trento/clusters/value_objects/cluster_resource_parent.ex
  lib/trento/discovery/policies/cluster_policy.ex
  lib/trento_web/controllers/v1/cluster_json.ex
  lib/trento_web/controllers/v2/cluster_json.ex
  test/support/factory.ex
  test/trento/discovery/policies/cluster_policy_test.exs
  test/trento_web/views/v1/cluster_view_json_test.exs
  test/trento_web/views/v2/cluster_view_json_test.exs
Labels: enhancement

#3277 Add Checks customization modal
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.stories.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.test.jsx
  assets/js/common/CheckCustomizationModal/index.js
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.jsx
Labels: enhancement, javascript, env

#3285 Activity log severity levels filter
  assets/js/pages/ActivityLogPage/searchParams.js
  lib/trento/activity_log.ex
  lib/trento/activity_logging/severity_level.ex
  lib/trento_web/controllers/v1/activity_log_controller.ex
  lib/trento_web/controllers/v1/activity_log_json.ex
  lib/trento_web/openapi/v1/schema/activity_log.ex
  test/e2e/cypress/e2e/activity_log.cy.js
  test/trento/activity_log_test.exs
  test/trento_web/controllers/v1/activity_log_controller_test.exs
  test/trento_web/views/v1/activity_log_view_json_test.exs
Labels: enhancement, elixir

#3286 Parameterized ecto payload
  lib/trento/clusters.ex
  lib/trento/clusters/projections/cluster_read_model.ex
  lib/trento/support/ecto/payload.ex
  lib/trento/support/struct_helper.ex
  lib/trento_web/controllers/v1/cluster_json.ex
  lib/trento_web/controllers/v2/cluster_json.ex
  test/trento/clusters/projections/cluster_projector_test.exs
  test/trento_web/views/v1/cluster_view_json_test.exs
  test/trento_web/views/v2/cluster_view_json_test.exs
Labels: enhancement

#3292 Reduce modal padding
  assets/js/common/Modal/Modal.jsx
Labels: chore, env

#3281 Apply PageObject pattern to databases overview tests.
  test/e2e/cypress/e2e/clusters_overview.cy.js
  test/e2e/cypress/e2e/databases_overview.cy.js
  test/e2e/cypress/pageObject/base-po.js
  test/e2e/cypress/pageObject/clusters-overview-po.js
  test/e2e/cypress/pageObject/databases-overview-po.js
Labels: test

#3299 Adjust checks selection route
  assets/js/lib/api/checks.js
  assets/js/pages/ChecksSelection/hooks.test.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.test.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.test.jsx
Labels: enhancement

#3293 Operation policies
  lib/trento/clusters.ex
  lib/trento/clusters/projections/cluster_read_model.ex
  lib/trento/databases/projections/database_instance_read_model.ex
  lib/trento/hosts/projections/host_read_model.ex
  lib/trento/operations/application_instance_policy.ex
  lib/trento/operations/cluster_policy.ex
  lib/trento/operations/database_instance_policy.ex
  lib/trento/operations/host_policy.ex
  lib/trento/operations/policy_behaviour.ex
  lib/trento/sap_systems/projections/application_instance_read_model.ex
  test/trento/clusters_test.exs
  test/trento/operations/application_instance_policy_test.exs
  test/trento/operations/cluster_policy_test.exs
  test/trento/operations/database_instance_policy_test.exs
  test/trento/operations/host_policy_test.exs
Labels: enhancement

#3301 Foundation for Basic Analytics Implementation
  assets/js/lib/analytics/index.js
  assets/js/lib/analytics/index.test.js
  assets/js/lib/analytics/pageview.js
  assets/js/trento.jsx
  assets/package-lock.json
  assets/package.json
  config/config.exs
  lib/trento/settings/installation_settings.ex
  lib/trento_web/controllers/page_controller.ex
  lib/trento_web/controllers/page_html/index.html.heex
  test/support/factory.ex
Labels: enhancement, ux, proposal

#3304 Add operations policy plug
  lib/trento_web/controllers/fallback_controller.ex
  lib/trento_web/plugs/operations_policy_plug.ex
  test/trento_web/plugs/operations_policy_plug_test.exs
Labels: enhancement

#3308 Add reset customization cta
  assets/js/common/ResetCheckCustomizationModal/ResetCheckCustomizationModal.jsx
  assets/js/common/ResetCheckCustomizationModal/ResetCheckCustomizationModal.stories.jsx
  assets/js/common/ResetCheckCustomizationModal/ResetCheckCustomizationModal.test.jsx
  assets/js/common/ResetCheckCustomizationModal/index.js
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.jsx
  assets/js/pages/ChecksSelection/ChecksSelectionItem.test.jsx
Labels: enhancement

#3312 Update `date-fns` to 4.1.0 and DateFilter refactoring
  assets/js/common/ActivityLogOverview/ActivityLogOverview.jsx
  assets/js/common/DateFilter/DateFilter.jsx
  assets/js/common/DateFilter/DateFilter.test.jsx
  assets/js/pages/ActivityLogPage/searchParams.js
  assets/js/pages/ActivityLogPage/searchParams.test.js
  assets/package-lock.json
  assets/package.json
Labels: bug, chore, env

#3309 Wire up check customization reset
  assets/js/lib/api/checks.js
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/js/pages/ChecksSelection/ChecksSelection.stories.jsx
  assets/js/pages/ChecksSelection/hooks.js
  assets/js/pages/ChecksSelection/hooks.test.jsx
  assets/js/pages/ClusterSettingsPage/ClusterSettingsPage.jsx
  assets/js/pages/HostSettingsPage/HostSettingsPage.jsx
Labels: enhancement

#3313 Create checkable warning messages
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckableWarningMessage/CheckableWarningMessage.jsx
  assets/js/common/CheckableWarningMessage/CheckableWarningMessage.stories.jsx
  assets/js/common/CheckableWarningMessage/CheckableWarningMessage.test.jsx
  assets/js/common/CheckableWarningMessage/index.js
Labels: javascript

#3323 Add reset customization cta inside modal
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.stories.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.test.jsx
  assets/js/pages/ChecksSelection/ChecksSelection.jsx
  assets/js/pages/ChecksSelection/ChecksSelection.stories.jsx
  assets/js/pages/ChecksSelection/hooks.js
  assets/js/pages/ChecksSelection/hooks.test.jsx
Labels: enhancement, user story, javascript

#3311 Saptune solution apply modal
  assets/js/common/OperationModals/OperationModal.jsx
  assets/js/common/OperationModals/SaptuneSolutionApplyModal.jsx
  assets/js/common/OperationModals/SaptuneSolutionApplyModal.stories.jsx
  assets/js/common/OperationModals/SaptuneSolutionApplyModal.test.jsx
  assets/js/common/OperationModals/index.js
Labels: enhancement

#3319 Actions button
  assets/js/common/ActionsButton/ActionsButton.jsx
  assets/js/common/ActionsButton/ActionsButton.stories.jsx
  assets/js/common/ActionsButton/ActionsButton.test.jsx
  assets/js/common/ActionsButton/index.js
Labels: enhancement

#3328 Enable reset customization when check is customized
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.test.jsx
Labels: bug

#3300 Apply PageObject pattern Hana Cluster Details E2E tests
  test/e2e/cypress/e2e/hana_cluster_details.cy.js
  test/e2e/cypress/pageObject/databases-overview-po.js
  test/e2e/cypress/pageObject/hana-cluster-details-po.js
Labels: test

#3329 Rename ActionsButton to OperationsButton
  assets/js/common/ActionsButton/ActionsButton.stories.jsx
  assets/js/common/ActionsButton/index.js
  assets/js/common/OperationsButton/OperationsButton.jsx
  assets/js/common/OperationsButton/OperationsButton.stories.jsx
  assets/js/common/OperationsButton/OperationsButton.test.jsx
  assets/js/common/OperationsButton/index.js
Labels: chore, env

#3332 Refactor checkable warning message
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckableWarningMessage/CheckableWarningMessage.jsx
  assets/js/common/CheckableWarningMessage/CheckableWarningMessage.stories.jsx
  assets/js/common/CheckableWarningMessage/CheckableWarningMessage.test.jsx
  assets/js/common/OperationModals/OperationModal.jsx
Labels: javascript

#3343 Bump trento contracts 0.2.0
  mix.exs
  mix.lock
Labels: dependencies

#3333 Request and process operation events
  lib/trento/hosts.ex
  lib/trento/infrastructure/checks/checks.ex
  lib/trento/infrastructure/operations/amqp/processor.ex
  lib/trento/infrastructure/operations/operations.ex
  lib/trento/support/protobuf.ex
  lib/trento_web/controllers/v1/host_controller.ex
  lib/trento_web/openapi/v1/schema/operation_accepted.ex
  test/trento/clusters_test.exs
  test/trento/hosts_test.exs
  test/trento/infrastructure/operations/operations_test.exs
  test/trento/infrastructure/operations/processor_test.exs
  test/trento/support/protobuf_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
Labels: enhancement, env

#3339 Running operations redux
  assets/js/lib/api/operations.js
  assets/js/lib/operations/index.js
  assets/js/lib/operations/operations.test.js
  assets/js/state/index.js
  assets/js/state/runningOperations.js
  assets/js/state/runningOperations.test.js
  assets/js/state/sagas/channels.js
  assets/js/state/sagas/channels.test.js
  assets/js/state/sagas/index.js
  assets/js/state/sagas/operations.js
  assets/js/state/sagas/operations.test.js
Labels: enhancement

#3310 Add boolean input for checks customization modal
  assets/js/common/CheckCustomizationModal/CheckCustomizationInput.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.stories.jsx
  assets/js/common/CheckCustomizationModal/CheckCustomizationModal.test.jsx
Labels: enhancement
