Repository trento-project/web, pull requests merged in 2025-06, with the labels that each got.

#3539 Split host and cluster operation requested activity logging
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/activity_logging/severity_level.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/metadata_enricher_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/activity_logging/queue_event_parser_test.exs
Labels: enhancement

#3550 SAP system operation request
  lib/trento/infrastructure/operations/operations.ex
  lib/trento/operations/application_instance_policy.ex
  lib/trento/operations/enums/sap_instance_operations.ex
  lib/trento/sap_systems.ex
  lib/trento_web/controllers/v1/sap_system_controller.ex
  lib/trento_web/openapi/v1/schema/sap_instance_operation_params.ex
  lib/trento_web/router.ex
  test/trento/infrastructure/operations/operations_test.exs
  test/trento/operations/application_instance_policy_test.exs
  test/trento/sap_systems_test.exs
  test/trento_web/controllers/v1/cluster_controller_test.exs
  test/trento_web/controllers/v1/sap_system_controller_test.exs
Labels: enhancement

#3560 Fix settings tests before each failure
  .github/workflows/e2e-flaky-tests-detection.yaml
  assets/js/pages/SettingsPage/hooks.js
Labels: test

#3566 Add transparent prop to operations button
  assets/js/common/OperationsButton/OperationsButton.jsx
  assets/js/common/OperationsButton/OperationsButton.stories.jsx
  assets/js/common/OperationsButton/OperationsButton.test.jsx
Labels: enhancement

#3575 Add operations button to SAP instance in table
  assets/js/pages/SapSystemDetails/GenericSystemDetails.jsx
  assets/js/pages/SapSystemDetails/GenericSystemDetails.test.jsx
  assets/js/pages/SapSystemDetails/SapSystemDetails.jsx
  assets/js/pages/SapSystemDetails/SapSystemDetails.stories.jsx
  assets/js/pages/SapSystemDetails/sapOperations.js
  assets/js/pages/SapSystemDetails/tableConfigs.jsx
Labels: enhancement, env

#3583 Improve cluster controller policy related test
  test/trento_web/controllers/v1/cluster_controller_test.exs
Labels: enhancement

#3585 App instance operation activity log
  assets/js/lib/model/activityLog.js
  assets/js/lib/operations/index.js
  assets/js/lib/operations/operations.test.js
  assets/js/state/sagas/operations.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/metadata_enricher.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/activity_logging/parser/queue_event_parser.ex
  lib/trento/activity_logging/severity_level.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/metadata_enricher_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/activity_logging/queue_event_parser_test.exs
Labels: enhancement, env

#3591 Update running operations refresh
  assets/js/lib/operations/index.js
  assets/js/lib/operations/operations.test.js
  assets/js/pages/ClusterDetails/ClusterDetailsPage.jsx
  assets/js/pages/HostDetailsPage/HostDetailsPage.jsx
  assets/js/pages/SapSystemDetails/SapSystemDetails.jsx
  assets/js/state/runningOperations.js
  assets/js/state/sagas/operations.js
  assets/js/state/sagas/operations.test.js
Labels: enhancement

#3554 Activity log correlation for deregistration entries
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.jsx
  assets/js/common/ActivityLogDetailsModal/ActivityLogDetailModal.test.jsx
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/event_parser.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  lib/trento/activity_logging/severity_level.ex
  lib/trento/databases.ex
  lib/trento/hosts.ex
  lib/trento/sap_systems.ex
  lib/trento_web/plugs/activity_logging_plug.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/activity_logger_test.exs
  test/trento/activity_logging/event_parser_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
  test/trento/databases_test.exs
  test/trento/infrastructure/commanded/event_handlers/activity_log_event_handler_test.exs
  test/trento/sap_systems_test.exs
  test/trento_web/controllers/v1/database_controller_test.exs
  test/trento_web/controllers/v1/host_controller_test.exs
  test/trento_web/controllers/v1/sap_system_controller_test.exs
  test/trento_web/plugs/activity_logging_plug_test.exs
Labels: enhancement, javascript, elixir, env

#3602 Add pacemaker ops to activity log
  assets/js/lib/model/activityLog.js
  lib/trento/activity_logging/activity_catalog.ex
  lib/trento/activity_logging/parser/phoenix_conn_parser.ex
  test/trento/activity_logging/activity_catalog_test.exs
  test/trento/activity_logging/phoenix_conn_parser_test.exs
Labels: enhancement
